/* Application.c generated by valac 0.56.18, the Vala compiler
 * generated from Application.vala, do not modify */

/* Copyright 2016-2018 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gdk/gdk.h>
#include <json-glib/json-glib.h>
#include <glib/gstdio.h>
#include "config.h"

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_APPLICATION (xi_application_get_type ())
#define XI_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_APPLICATION, XiApplication))
#define XI_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_APPLICATION, XiApplicationClass))
#define XI_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_APPLICATION))
#define XI_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_APPLICATION))
#define XI_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_APPLICATION, XiApplicationClass))

typedef struct _XiApplication XiApplication;
typedef struct _XiApplicationClass XiApplicationClass;
typedef struct _XiApplicationPrivate XiApplicationPrivate;

#define XI_TYPE_CORE_CONNECTION (xi_core_connection_get_type ())
#define XI_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnection))
#define XI_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))
#define XI_IS_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_CORE_CONNECTION))
#define XI_IS_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_CORE_CONNECTION))
#define XI_CORE_CONNECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))

typedef struct _XiCoreConnection XiCoreConnection;
typedef struct _XiCoreConnectionClass XiCoreConnectionClass;
enum  {
	XI_APPLICATION_0_PROPERTY,
	XI_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* xi_application_properties[XI_APPLICATION_NUM_PROPERTIES];
#define _xi_core_connection_unref0(var) ((var == NULL) ? NULL : (var = (xi_core_connection_unref (var), NULL)))

#define XI_TYPE_WINDOW (xi_window_get_type ())
#define XI_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_WINDOW, XiWindow))
#define XI_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_WINDOW, XiWindowClass))
#define XI_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_WINDOW))
#define XI_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_WINDOW))
#define XI_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_WINDOW, XiWindowClass))

typedef struct _XiWindow XiWindow;
typedef struct _XiWindowClass XiWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define XI_TYPE_STYLE_MAP (xi_style_map_get_type ())
#define XI_STYLE_MAP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_STYLE_MAP, XiStyleMap))
#define XI_STYLE_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_STYLE_MAP, XiStyleMapClass))
#define XI_IS_STYLE_MAP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_STYLE_MAP))
#define XI_IS_STYLE_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_STYLE_MAP))
#define XI_STYLE_MAP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_STYLE_MAP, XiStyleMapClass))

typedef struct _XiStyleMap XiStyleMap;
typedef struct _XiStyleMapClass XiStyleMapClass;
#define _xi_style_map_unref0(var) ((var == NULL) ? NULL : (var = (xi_style_map_unref (var), NULL)))

#define XI_TYPE_THEME (xi_theme_get_type ())
#define XI_THEME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_THEME, XiTheme))
#define XI_THEME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_THEME, XiThemeClass))
#define XI_IS_THEME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_THEME))
#define XI_IS_THEME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_THEME))
#define XI_THEME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_THEME, XiThemeClass))

typedef struct _XiTheme XiTheme;
typedef struct _XiThemeClass XiThemeClass;
#define _xi_theme_unref0(var) ((var == NULL) ? NULL : (var = (xi_theme_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _XiApplication {
	GtkApplication parent_instance;
	XiApplicationPrivate * priv;
};

struct _XiApplicationClass {
	GtkApplicationClass parent_class;
};

struct _XiApplicationPrivate {
	XiCoreConnection* core_connection;
};

static gint XiApplication_private_offset;
static gpointer xi_application_parent_class = NULL;

VALA_EXTERN GType xi_application_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiApplication, g_object_unref)
VALA_EXTERN gpointer xi_core_connection_ref (gpointer instance);
VALA_EXTERN void xi_core_connection_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_core_connection (const gchar* name,
                                           const gchar* nick,
                                           const gchar* blurb,
                                           GType object_type,
                                           GParamFlags flags);
VALA_EXTERN void xi_value_set_core_connection (GValue* value,
                                   gpointer v_object);
VALA_EXTERN void xi_value_take_core_connection (GValue* value,
                                    gpointer v_object);
VALA_EXTERN gpointer xi_value_get_core_connection (const GValue* value);
VALA_EXTERN GType xi_core_connection_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiCoreConnection, xi_core_connection_unref)
VALA_EXTERN XiApplication* xi_application_new (void);
VALA_EXTERN XiApplication* xi_application_construct (GType object_type);
VALA_EXTERN GType xi_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiWindow, g_object_unref)
static XiWindow* xi_application_get_current_window (XiApplication* self);
static void xi_application_load_css (XiApplication* self,
                              const gchar* resource_path);
static void xi_application_real_startup (GApplication* base);
static void __lambda16_ (XiApplication* self);
static void ___lambda16__g_simple_action_activate (GSimpleAction* _sender,
                                            GVariant* parameter,
                                            gpointer self);
VALA_EXTERN XiCoreConnection* xi_core_connection_new (gchar** command,
                                          gint command_length1);
VALA_EXTERN XiCoreConnection* xi_core_connection_construct (GType object_type,
                                                gchar** command,
                                                gint command_length1);
static void __lambda17_ (XiApplication* self,
                  JsonObject* style);
VALA_EXTERN gpointer xi_style_map_ref (gpointer instance);
VALA_EXTERN void xi_style_map_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_style_map (const gchar* name,
                                     const gchar* nick,
                                     const gchar* blurb,
                                     GType object_type,
                                     GParamFlags flags);
VALA_EXTERN void xi_value_set_style_map (GValue* value,
                             gpointer v_object);
VALA_EXTERN void xi_value_take_style_map (GValue* value,
                              gpointer v_object);
VALA_EXTERN gpointer xi_value_get_style_map (const GValue* value);
VALA_EXTERN GType xi_style_map_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiStyleMap, xi_style_map_unref)
VALA_EXTERN XiStyleMap* xi_style_map_get_instance (void);
VALA_EXTERN void xi_style_map_def_style (XiStyleMap* self,
                             JsonObject* json_style);
static void ___lambda17__xi_core_connection_def_style_received (XiCoreConnection* _sender,
                                                         JsonObject* params,
                                                         gpointer self);
static void __lambda18_ (XiApplication* self,
                  const gchar* name,
                  JsonObject* theme);
VALA_EXTERN gpointer xi_theme_ref (gpointer instance);
VALA_EXTERN void xi_theme_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_theme (const gchar* name,
                                 const gchar* nick,
                                 const gchar* blurb,
                                 GType object_type,
                                 GParamFlags flags);
VALA_EXTERN void xi_value_set_theme (GValue* value,
                         gpointer v_object);
VALA_EXTERN void xi_value_take_theme (GValue* value,
                          gpointer v_object);
VALA_EXTERN gpointer xi_value_get_theme (const GValue* value);
VALA_EXTERN GType xi_theme_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiTheme, xi_theme_unref)
VALA_EXTERN XiTheme* xi_theme_get_instance (void);
VALA_EXTERN void xi_theme_set_from_json (XiTheme* self,
                             JsonObject* theme);
static void ___lambda18__xi_core_connection_theme_changed_received (XiCoreConnection* _sender,
                                                             const gchar* name,
                                                             JsonObject* theme,
                                                             gpointer self);
VALA_EXTERN void xi_core_connection_send_client_started (XiCoreConnection* self,
                                             const gchar* config_dir,
                                             const gchar* client_extras_dir);
VALA_EXTERN void xi_core_connection_send_set_theme (XiCoreConnection* self,
                                        const gchar* theme_name);
VALA_EXTERN XiWindow* xi_window_new (GtkApplication* application,
                         XiCoreConnection* core_connection);
VALA_EXTERN XiWindow* xi_window_construct (GType object_type,
                               GtkApplication* application,
                               XiCoreConnection* core_connection);
static void xi_application_real_activate (GApplication* base);
VALA_EXTERN void xi_window_add_new_tab (XiWindow* self,
                            GFile* file);
static void xi_application_real_open (GApplication* base,
                               GFile** files,
                               gint files_length1,
                               const gchar* hint);
static gint xi_application_main (gchar** args,
                          gint args_length1);
static void xi_application_finalize (GObject * obj);
static GType xi_application_get_type_once (void);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static inline gpointer
xi_application_get_instance_private (XiApplication* self)
{
	return G_STRUCT_MEMBER_P (self, XiApplication_private_offset);
}

XiApplication*
xi_application_construct (GType object_type)
{
	XiApplication * self = NULL;
	self = (XiApplication*) g_object_new (object_type, "application-id", "com.github.eyelash.xi-gtk", "flags", G_APPLICATION_HANDLES_OPEN, NULL);
	return self;
}

XiApplication*
xi_application_new (void)
{
	return xi_application_construct (XI_TYPE_APPLICATION);
}

static XiWindow*
xi_application_get_current_window (XiApplication* self)
{
	GtkWindow* _tmp0_;
	XiWindow* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = gtk_application_get_active_window ((GtkApplication*) self);
	result = XI_IS_WINDOW (_tmp0_) ? ((XiWindow*) _tmp0_) : NULL;
	return result;
}

static void
xi_application_load_css (XiApplication* self,
                         const gchar* resource_path)
{
	GtkCssProvider* css_provider = NULL;
	GtkCssProvider* _tmp0_;
	GdkScreen* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (resource_path != NULL);
	_tmp0_ = gtk_css_provider_new ();
	css_provider = _tmp0_;
	gtk_css_provider_load_from_resource (css_provider, resource_path);
	_tmp1_ = gdk_screen_get_default ();
	gtk_style_context_add_provider_for_screen (_tmp1_, (GtkStyleProvider*) css_provider, (guint) GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
	_g_object_unref0 (css_provider);
}

static void
__lambda16_ (XiApplication* self)
{
	GList* _tmp0_;
	_tmp0_ = gtk_application_get_windows ((GtkApplication*) self);
	{
		GList* window_collection = NULL;
		GList* window_it = NULL;
		window_collection = _tmp0_;
		for (window_it = window_collection; window_it != NULL; window_it = window_it->next) {
			GtkWindow* window = NULL;
			window = (GtkWindow*) window_it->data;
			{
				GtkWindow* _tmp1_;
				_tmp1_ = window;
				gtk_window_close (_tmp1_);
			}
		}
	}
}

static void
___lambda16__g_simple_action_activate (GSimpleAction* _sender,
                                       GVariant* parameter,
                                       gpointer self)
{
	__lambda16_ ((XiApplication*) self);
}

static void
__lambda17_ (XiApplication* self,
             JsonObject* style)
{
	XiStyleMap* _tmp0_;
	XiStyleMap* _tmp1_;
	g_return_if_fail (style != NULL);
	_tmp0_ = xi_style_map_get_instance ();
	_tmp1_ = _tmp0_;
	xi_style_map_def_style (_tmp1_, style);
	_xi_style_map_unref0 (_tmp1_);
}

static void
___lambda17__xi_core_connection_def_style_received (XiCoreConnection* _sender,
                                                    JsonObject* params,
                                                    gpointer self)
{
	__lambda17_ ((XiApplication*) self, params);
}

static void
__lambda18_ (XiApplication* self,
             const gchar* name,
             JsonObject* theme)
{
	XiTheme* _tmp0_;
	XiTheme* _tmp1_;
	g_return_if_fail (name != NULL);
	g_return_if_fail (theme != NULL);
	_tmp0_ = xi_theme_get_instance ();
	_tmp1_ = _tmp0_;
	xi_theme_set_from_json (_tmp1_, theme);
	_xi_theme_unref0 (_tmp1_);
}

static void
___lambda18__xi_core_connection_theme_changed_received (XiCoreConnection* _sender,
                                                        const gchar* name,
                                                        JsonObject* theme,
                                                        gpointer self)
{
	__lambda18_ ((XiApplication*) self, name, theme);
}

static void
xi_application_real_startup (GApplication* base)
{
	XiApplication * self;
	GSimpleAction* quit_action = NULL;
	GSimpleAction* _tmp0_;
	GSimpleAction* _tmp1_;
	GSimpleAction* _tmp2_;
	gchar* _tmp3_;
	gchar** _tmp4_;
	gchar** _tmp5_;
	gint _tmp5__length1;
	gchar* _tmp6_;
	gchar** _tmp7_;
	gchar** _tmp8_;
	gint _tmp8__length1;
	gchar* _tmp9_;
	gchar** _tmp10_;
	gchar** _tmp11_;
	gint _tmp11__length1;
	gchar* _tmp12_;
	gchar** _tmp13_;
	gchar** _tmp14_;
	gint _tmp14__length1;
	gchar* _tmp15_;
	gchar** _tmp16_;
	gchar** _tmp17_;
	gint _tmp17__length1;
	const gchar* core_binary = NULL;
	const gchar* _tmp18_;
	const gchar* _tmp19_;
	const gchar* _tmp20_;
	gchar* _tmp21_;
	gchar** _tmp22_;
	gchar** _tmp23_;
	gint _tmp23__length1;
	XiCoreConnection* _tmp24_;
	XiCoreConnection* _tmp25_;
	XiCoreConnection* _tmp26_;
	gchar* config_dir = NULL;
	const gchar* _tmp27_;
	gchar* _tmp28_;
	const gchar* _tmp29_;
	XiCoreConnection* _tmp30_;
	const gchar* _tmp31_;
	const gchar* theme = NULL;
	const gchar* _tmp32_;
	const gchar* _tmp33_;
	XiCoreConnection* _tmp34_;
	const gchar* _tmp35_;
	XiWindow* window = NULL;
	XiCoreConnection* _tmp36_;
	XiWindow* _tmp37_;
	self = (XiApplication*) base;
	G_APPLICATION_CLASS (xi_application_parent_class)->startup ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
	xi_application_load_css (self, "/com/github/eyelash/xi-gtk/key-bindings.css");
	xi_application_load_css (self, "/com/github/eyelash/xi-gtk/style.css");
	_tmp0_ = g_simple_action_new ("quit", NULL);
	quit_action = _tmp0_;
	_tmp1_ = quit_action;
	g_signal_connect_object (_tmp1_, "activate", (GCallback) ___lambda16__g_simple_action_activate, self, 0);
	_tmp2_ = quit_action;
	g_action_map_add_action ((GActionMap*) self, (GAction*) _tmp2_);
	_tmp3_ = g_strdup ("<Primary>N");
	_tmp4_ = g_new0 (gchar*, 1 + 1);
	_tmp4_[0] = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.new-tab", _tmp5_);
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) g_free), NULL);
	_tmp6_ = g_strdup ("<Primary>O");
	_tmp7_ = g_new0 (gchar*, 1 + 1);
	_tmp7_[0] = _tmp6_;
	_tmp8_ = _tmp7_;
	_tmp8__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.open", _tmp8_);
	_tmp8_ = (_vala_array_free (_tmp8_, _tmp8__length1, (GDestroyNotify) g_free), NULL);
	_tmp9_ = g_strdup ("<Primary>S");
	_tmp10_ = g_new0 (gchar*, 1 + 1);
	_tmp10_[0] = _tmp9_;
	_tmp11_ = _tmp10_;
	_tmp11__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.save", _tmp11_);
	_tmp11_ = (_vala_array_free (_tmp11_, _tmp11__length1, (GDestroyNotify) g_free), NULL);
	_tmp12_ = g_strdup ("<Primary><Shift>S");
	_tmp13_ = g_new0 (gchar*, 1 + 1);
	_tmp13_[0] = _tmp12_;
	_tmp14_ = _tmp13_;
	_tmp14__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.save-as", _tmp14_);
	_tmp14_ = (_vala_array_free (_tmp14_, _tmp14__length1, (GDestroyNotify) g_free), NULL);
	_tmp15_ = g_strdup ("<Primary>F");
	_tmp16_ = g_new0 (gchar*, 1 + 1);
	_tmp16_[0] = _tmp15_;
	_tmp17_ = _tmp16_;
	_tmp17__length1 = 1;
	gtk_application_set_accels_for_action ((GtkApplication*) self, "win.find", _tmp17_);
	_tmp17_ = (_vala_array_free (_tmp17_, _tmp17__length1, (GDestroyNotify) g_free), NULL);
	_tmp18_ = g_getenv ("XI_CORE");
	core_binary = _tmp18_;
	_tmp19_ = core_binary;
	if (_tmp19_ == NULL) {
		core_binary = "xi-core";
	}
	_tmp20_ = core_binary;
	_tmp21_ = g_strdup (_tmp20_);
	_tmp22_ = g_new0 (gchar*, 1 + 1);
	_tmp22_[0] = _tmp21_;
	_tmp23_ = _tmp22_;
	_tmp23__length1 = 1;
	_tmp24_ = xi_core_connection_new (_tmp23_, 1);
	_xi_core_connection_unref0 (self->priv->core_connection);
	self->priv->core_connection = _tmp24_;
	_tmp23_ = (_vala_array_free (_tmp23_, _tmp23__length1, (GDestroyNotify) g_free), NULL);
	_tmp25_ = self->priv->core_connection;
	g_signal_connect_object (_tmp25_, "def-style-received", (GCallback) ___lambda17__xi_core_connection_def_style_received, self, 0);
	_tmp26_ = self->priv->core_connection;
	g_signal_connect_object (_tmp26_, "theme-changed-received", (GCallback) ___lambda18__xi_core_connection_theme_changed_received, self, 0);
	_tmp27_ = g_get_user_config_dir ();
	_tmp28_ = g_build_filename (_tmp27_, "xi-gtk", NULL);
	config_dir = _tmp28_;
	_tmp29_ = config_dir;
	g_mkdir_with_parents (_tmp29_, 0777);
	_tmp30_ = self->priv->core_connection;
	_tmp31_ = config_dir;
	xi_core_connection_send_client_started (_tmp30_, _tmp31_, PLUGIN_DIR);
	_tmp32_ = g_getenv ("XI_THEME");
	theme = _tmp32_;
	_tmp33_ = theme;
	if (_tmp33_ == NULL) {
		theme = "InspiredGitHub";
	}
	_tmp34_ = self->priv->core_connection;
	_tmp35_ = theme;
	xi_core_connection_send_set_theme (_tmp34_, _tmp35_);
	_tmp36_ = self->priv->core_connection;
	_tmp37_ = xi_window_new ((GtkApplication*) self, _tmp36_);
	g_object_ref_sink (_tmp37_);
	window = _tmp37_;
	gtk_widget_show_all ((GtkWidget*) window);
	_g_object_unref0 (window);
	_g_free0 (config_dir);
	_g_object_unref0 (quit_action);
}

static void
xi_application_real_activate (GApplication* base)
{
	XiApplication * self;
	XiWindow* _tmp0_;
	self = (XiApplication*) base;
	_tmp0_ = xi_application_get_current_window (self);
	xi_window_add_new_tab (_tmp0_, NULL);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static void
xi_application_real_open (GApplication* base,
                          GFile** files,
                          gint files_length1,
                          const gchar* hint)
{
	XiApplication * self;
	self = (XiApplication*) base;
	g_return_if_fail (hint != NULL);
	{
		GFile** file_collection = NULL;
		gint file_collection_length1 = 0;
		gint _file_collection_size_ = 0;
		gint file_it = 0;
		file_collection = files;
		file_collection_length1 = files_length1;
		for (file_it = 0; file_it < file_collection_length1; file_it = file_it + 1) {
			GFile* _tmp0_;
			GFile* file = NULL;
			_tmp0_ = _g_object_ref0 (file_collection[file_it]);
			file = _tmp0_;
			{
				XiWindow* _tmp1_;
				GFile* _tmp2_;
				_tmp1_ = xi_application_get_current_window (self);
				_tmp2_ = file;
				xi_window_add_new_tab (_tmp1_, _tmp2_);
				_g_object_unref0 (file);
			}
		}
	}
}

static gint
xi_application_main (gchar** args,
                     gint args_length1)
{
	XiApplication* app = NULL;
	XiApplication* _tmp0_;
	gint result;
	_tmp0_ = xi_application_new ();
	app = _tmp0_;
	result = g_application_run ((GApplication*) app, (gint) args_length1, args);
	_g_object_unref0 (app);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return xi_application_main (argv, argc);
}

static void
xi_application_class_init (XiApplicationClass * klass,
                           gpointer klass_data)
{
	xi_application_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &XiApplication_private_offset);
	((GApplicationClass *) klass)->startup = (void (*) (GApplication*)) xi_application_real_startup;
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) xi_application_real_activate;
	((GApplicationClass *) klass)->open = (void (*) (GApplication*, GFile**, gint, const gchar*)) xi_application_real_open;
	G_OBJECT_CLASS (klass)->finalize = xi_application_finalize;
}

static void
xi_application_instance_init (XiApplication * self,
                              gpointer klass)
{
	self->priv = xi_application_get_instance_private (self);
}

static void
xi_application_finalize (GObject * obj)
{
	XiApplication * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_APPLICATION, XiApplication);
	_xi_core_connection_unref0 (self->priv->core_connection);
	G_OBJECT_CLASS (xi_application_parent_class)->finalize (obj);
}

static GType
xi_application_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (XiApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiApplication), 0, (GInstanceInitFunc) xi_application_instance_init, NULL };
	GType xi_application_type_id;
	xi_application_type_id = g_type_register_static (gtk_application_get_type (), "XiApplication", &g_define_type_info, 0);
	XiApplication_private_offset = g_type_add_instance_private (xi_application_type_id, sizeof (XiApplicationPrivate));
	return xi_application_type_id;
}

GType
xi_application_get_type (void)
{
	static volatile gsize xi_application_type_id__once = 0;
	if (g_once_init_enter (&xi_application_type_id__once)) {
		GType xi_application_type_id;
		xi_application_type_id = xi_application_get_type_once ();
		g_once_init_leave (&xi_application_type_id__once, xi_application_type_id);
	}
	return xi_application_type_id__once;
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

