/* Blinker.c generated by valac 0.56.18, the Vala compiler
 * generated from Blinker.vala, do not modify */

/* Copyright 2017 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <glib-object.h>
#include <glib.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_BLINKER (xi_blinker_get_type ())
#define XI_BLINKER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_BLINKER, XiBlinker))
#define XI_BLINKER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_BLINKER, XiBlinkerClass))
#define XI_IS_BLINKER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_BLINKER))
#define XI_IS_BLINKER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_BLINKER))
#define XI_BLINKER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_BLINKER, XiBlinkerClass))

typedef struct _XiBlinker XiBlinker;
typedef struct _XiBlinkerClass XiBlinkerClass;
typedef struct _XiBlinkerPrivate XiBlinkerPrivate;
#define _g_source_unref0(var) ((var == NULL) ? NULL : (var = (g_source_unref (var), NULL)))
typedef struct _XiParamSpecBlinker XiParamSpecBlinker;
enum  {
	XI_BLINKER_REDRAW_SIGNAL,
	XI_BLINKER_NUM_SIGNALS
};
static guint xi_blinker_signals[XI_BLINKER_NUM_SIGNALS] = {0};

struct _XiBlinker {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XiBlinkerPrivate * priv;
};

struct _XiBlinkerClass {
	GTypeClass parent_class;
	void (*finalize) (XiBlinker *self);
};

struct _XiBlinkerPrivate {
	guint interval;
	GSource* source;
	guint counter;
};

struct _XiParamSpecBlinker {
	GParamSpec parent_instance;
};

static gint XiBlinker_private_offset;
static gpointer xi_blinker_parent_class = NULL;

VALA_EXTERN gpointer xi_blinker_ref (gpointer instance);
VALA_EXTERN void xi_blinker_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_blinker (const gchar* name,
                                   const gchar* nick,
                                   const gchar* blurb,
                                   GType object_type,
                                   GParamFlags flags);
VALA_EXTERN void xi_value_set_blinker (GValue* value,
                           gpointer v_object);
VALA_EXTERN void xi_value_take_blinker (GValue* value,
                            gpointer v_object);
VALA_EXTERN gpointer xi_value_get_blinker (const GValue* value);
VALA_EXTERN GType xi_blinker_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiBlinker, xi_blinker_unref)
VALA_EXTERN XiBlinker* xi_blinker_new (guint interval);
VALA_EXTERN XiBlinker* xi_blinker_construct (GType object_type,
                                 guint interval);
static gboolean xi_blinker_blink (XiBlinker* self);
VALA_EXTERN void xi_blinker_stop (XiBlinker* self);
VALA_EXTERN void xi_blinker_restart (XiBlinker* self);
static gboolean _xi_blinker_blink_gsource_func (gpointer self);
VALA_EXTERN gboolean xi_blinker_draw_cursor (XiBlinker* self);
static void xi_blinker_finalize (XiBlinker * obj);
static GType xi_blinker_get_type_once (void);

static inline gpointer
xi_blinker_get_instance_private (XiBlinker* self)
{
	return G_STRUCT_MEMBER_P (self, XiBlinker_private_offset);
}

XiBlinker*
xi_blinker_construct (GType object_type,
                      guint interval)
{
	XiBlinker* self = NULL;
	self = (XiBlinker*) g_type_create_instance (object_type);
	self->priv->interval = interval;
	return self;
}

XiBlinker*
xi_blinker_new (guint interval)
{
	return xi_blinker_construct (XI_TYPE_BLINKER, interval);
}

static gboolean
xi_blinker_blink (XiBlinker* self)
{
	guint _tmp0_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->counter;
	self->priv->counter = _tmp0_ + 1;
	g_signal_emit (self, xi_blinker_signals[XI_BLINKER_REDRAW_SIGNAL], 0);
	result = self->priv->counter < ((guint) 18);
	return result;
}

void
xi_blinker_stop (XiBlinker* self)
{
	GSource* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->source;
	if (_tmp0_ != NULL) {
		GSource* _tmp1_;
		_tmp1_ = self->priv->source;
		g_source_destroy (_tmp1_);
	}
	self->priv->counter = (guint) 0;
}

static gboolean
_xi_blinker_blink_gsource_func (gpointer self)
{
	gboolean result;
	result = xi_blinker_blink ((XiBlinker*) self);
	return result;
}

void
xi_blinker_restart (XiBlinker* self)
{
	GSource* _tmp0_;
	GSource* _tmp1_;
	GSource* _tmp2_;
	g_return_if_fail (self != NULL);
	xi_blinker_stop (self);
	_tmp0_ = g_timeout_source_new (self->priv->interval);
	_g_source_unref0 (self->priv->source);
	self->priv->source = _tmp0_;
	_tmp1_ = self->priv->source;
	g_source_set_callback (_tmp1_, _xi_blinker_blink_gsource_func, xi_blinker_ref (self), xi_blinker_unref);
	_tmp2_ = self->priv->source;
	g_source_attach (_tmp2_, NULL);
}

gboolean
xi_blinker_draw_cursor (XiBlinker* self)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = (self->priv->counter % 2) == ((guint) 0);
	return result;
}

static void
xi_value_blinker_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
xi_value_blinker_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		xi_blinker_unref (value->data[0].v_pointer);
	}
}

static void
xi_value_blinker_copy_value (const GValue* src_value,
                             GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = xi_blinker_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
xi_value_blinker_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
xi_value_blinker_collect_value (GValue* value,
                                guint n_collect_values,
                                GTypeCValue* collect_values,
                                guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		XiBlinker * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = xi_blinker_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
xi_value_blinker_lcopy_value (const GValue* value,
                              guint n_collect_values,
                              GTypeCValue* collect_values,
                              guint collect_flags)
{
	XiBlinker ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = xi_blinker_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
xi_param_spec_blinker (const gchar* name,
                       const gchar* nick,
                       const gchar* blurb,
                       GType object_type,
                       GParamFlags flags)
{
	XiParamSpecBlinker* spec;
	g_return_val_if_fail (g_type_is_a (object_type, XI_TYPE_BLINKER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
xi_value_get_blinker (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_BLINKER), NULL);
	return value->data[0].v_pointer;
}

void
xi_value_set_blinker (GValue* value,
                      gpointer v_object)
{
	XiBlinker * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_BLINKER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_BLINKER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		xi_blinker_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_blinker_unref (old);
	}
}

void
xi_value_take_blinker (GValue* value,
                       gpointer v_object)
{
	XiBlinker * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_BLINKER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_BLINKER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_blinker_unref (old);
	}
}

static void
xi_blinker_class_init (XiBlinkerClass * klass,
                       gpointer klass_data)
{
	xi_blinker_parent_class = g_type_class_peek_parent (klass);
	((XiBlinkerClass *) klass)->finalize = xi_blinker_finalize;
	g_type_class_adjust_private_offset (klass, &XiBlinker_private_offset);
	xi_blinker_signals[XI_BLINKER_REDRAW_SIGNAL] = g_signal_new ("redraw", XI_TYPE_BLINKER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}

static void
xi_blinker_instance_init (XiBlinker * self,
                          gpointer klass)
{
	self->priv = xi_blinker_get_instance_private (self);
	self->ref_count = 1;
}

static void
xi_blinker_finalize (XiBlinker * obj)
{
	XiBlinker * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_BLINKER, XiBlinker);
	g_signal_handlers_destroy (self);
	_g_source_unref0 (self->priv->source);
}

static GType
xi_blinker_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { xi_value_blinker_init, xi_value_blinker_free_value, xi_value_blinker_copy_value, xi_value_blinker_peek_pointer, "p", xi_value_blinker_collect_value, "p", xi_value_blinker_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (XiBlinkerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_blinker_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiBlinker), 0, (GInstanceInitFunc) xi_blinker_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType xi_blinker_type_id;
	xi_blinker_type_id = g_type_register_fundamental (g_type_fundamental_next (), "XiBlinker", &g_define_type_info, &g_define_type_fundamental_info, 0);
	XiBlinker_private_offset = g_type_add_instance_private (xi_blinker_type_id, sizeof (XiBlinkerPrivate));
	return xi_blinker_type_id;
}

GType
xi_blinker_get_type (void)
{
	static volatile gsize xi_blinker_type_id__once = 0;
	if (g_once_init_enter (&xi_blinker_type_id__once)) {
		GType xi_blinker_type_id;
		xi_blinker_type_id = xi_blinker_get_type_once ();
		g_once_init_leave (&xi_blinker_type_id__once, xi_blinker_type_id);
	}
	return xi_blinker_type_id__once;
}

gpointer
xi_blinker_ref (gpointer instance)
{
	XiBlinker * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
xi_blinker_unref (gpointer instance)
{
	XiBlinker * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		XI_BLINKER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

