/* CoreConnection.c generated by valac 0.56.18, the Vala compiler
 * generated from CoreConnection.vala, do not modify */

/* Copyright 2016-2019 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <glib-object.h>
#include <gio/gio.h>
#include <glib.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_CORE_CONNECTION (xi_core_connection_get_type ())
#define XI_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnection))
#define XI_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))
#define XI_IS_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_CORE_CONNECTION))
#define XI_IS_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_CORE_CONNECTION))
#define XI_CORE_CONNECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))

typedef struct _XiCoreConnection XiCoreConnection;
typedef struct _XiCoreConnectionClass XiCoreConnectionClass;
typedef struct _XiCoreConnectionPrivate XiCoreConnectionPrivate;

#define XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER (xi_core_connection_response_handler_get_type ())
#define XI_CORE_CONNECTION_RESPONSE_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER, XiCoreConnectionResponseHandler))
#define XI_CORE_CONNECTION_RESPONSE_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER, XiCoreConnectionResponseHandlerClass))
#define XI_CORE_CONNECTION_IS_RESPONSE_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER))
#define XI_CORE_CONNECTION_IS_RESPONSE_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER))
#define XI_CORE_CONNECTION_RESPONSE_HANDLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER, XiCoreConnectionResponseHandlerClass))

typedef struct _XiCoreConnectionResponseHandler XiCoreConnectionResponseHandler;
typedef struct _XiCoreConnectionResponseHandlerClass XiCoreConnectionResponseHandlerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _xi_core_connection_unref0(var) ((var == NULL) ? NULL : (var = (xi_core_connection_unref (var), NULL)))
typedef struct _XiCoreConnectionResponseHandlerPrivate XiCoreConnectionResponseHandlerPrivate;
#define _xi_core_connection_response_handler_unref0(var) ((var == NULL) ? NULL : (var = (xi_core_connection_response_handler_unref (var), NULL)))
typedef struct _XiCoreConnectionSendRequestData XiCoreConnectionSendRequestData;
typedef struct _XiCoreConnectionSendEditRequestData XiCoreConnectionSendEditRequestData;
typedef struct _XiCoreConnectionSendNewViewData XiCoreConnectionSendNewViewData;
typedef struct _XiCoreConnectionSendCopyData XiCoreConnectionSendCopyData;
typedef struct _XiCoreConnectionSendCutData XiCoreConnectionSendCutData;
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))
typedef struct _XiCoreConnectionReceiveData XiCoreConnectionReceiveData;
typedef struct _XiCoreConnectionParamSpecResponseHandler XiCoreConnectionParamSpecResponseHandler;
typedef struct _XiParamSpecCoreConnection XiParamSpecCoreConnection;
enum  {
	XI_CORE_CONNECTION_UPDATE_RECEIVED_SIGNAL,
	XI_CORE_CONNECTION_SCROLL_TO_RECEIVED_SIGNAL,
	XI_CORE_CONNECTION_DEF_STYLE_RECEIVED_SIGNAL,
	XI_CORE_CONNECTION_THEME_CHANGED_RECEIVED_SIGNAL,
	XI_CORE_CONNECTION_ALERT_RECEIVED_SIGNAL,
	XI_CORE_CONNECTION_NUM_SIGNALS
};
static guint xi_core_connection_signals[XI_CORE_CONNECTION_NUM_SIGNALS] = {0};

struct _XiCoreConnection {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XiCoreConnectionPrivate * priv;
};

struct _XiCoreConnectionClass {
	GTypeClass parent_class;
	void (*finalize) (XiCoreConnection *self);
};

struct _XiCoreConnectionPrivate {
	GSubprocess* core_process;
	gint id;
	GHashTable* response_handlers;
};

struct _XiCoreConnectionResponseHandler {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XiCoreConnectionResponseHandlerPrivate * priv;
	GSourceFunc callback;
	gpointer callback_target;
	GDestroyNotify callback_target_destroy_notify;
	JsonNode* result;
};

struct _XiCoreConnectionResponseHandlerClass {
	GTypeClass parent_class;
	void (*finalize) (XiCoreConnectionResponseHandler *self);
};

struct _XiCoreConnectionSendRequestData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	XiCoreConnection* self;
	gchar* method;
	JsonObject* params;
	JsonNode* result;
	XiCoreConnectionResponseHandler* response_handler;
	XiCoreConnectionResponseHandler* _tmp0_;
	GHashTable* _tmp1_;
	XiCoreConnectionResponseHandler* _tmp2_;
	JsonObject* root;
	JsonObject* _tmp3_;
	gint _tmp4_;
	JsonObject* _tmp5_;
	JsonNode* _tmp6_;
	JsonNode* _tmp7_;
};

struct _XiCoreConnectionSendEditRequestData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	XiCoreConnection* self;
	gchar* view_id;
	gchar* method;
	JsonObject* edit_params;
	JsonNode* result;
	JsonObject* params;
	JsonObject* _tmp0_;
	JsonObject* _tmp1_;
	JsonNode* _tmp2_;
};

struct _XiCoreConnectionSendNewViewData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	XiCoreConnection* self;
	gchar* file_path;
	gchar* result;
	JsonObject* params;
	JsonObject* _tmp0_;
	JsonObject* _tmp1_;
	JsonNode* _result_;
	JsonObject* _tmp2_;
	JsonNode* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
};

struct _XiCoreConnectionSendCopyData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	XiCoreConnection* self;
	gchar* view_id;
	gchar* result;
	JsonNode* _result_;
	JsonObject* _tmp0_;
	JsonObject* _tmp1_;
	JsonNode* _tmp2_;
	JsonNode* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
};

struct _XiCoreConnectionSendCutData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	XiCoreConnection* self;
	gchar* view_id;
	gchar* result;
	JsonNode* _result_;
	JsonObject* _tmp0_;
	JsonObject* _tmp1_;
	JsonNode* _tmp2_;
	JsonNode* _tmp3_;
	const gchar* _tmp4_;
	gchar* _tmp5_;
};

struct _XiCoreConnectionReceiveData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	XiCoreConnection* self;
	GDataInputStream* core_stdout;
	GSubprocess* _tmp0_;
	GInputStream* _tmp1_;
	GDataInputStream* _tmp2_;
	gchar* line;
	GDataInputStream* _tmp3_;
	gchar* _tmp4_;
	const gchar* _tmp5_;
	JsonParser* parser;
	JsonParser* _tmp6_;
	JsonParser* _tmp7_;
	const gchar* _tmp8_;
	JsonObject* root;
	JsonParser* _tmp9_;
	JsonNode* _tmp10_;
	JsonObject* _tmp11_;
	JsonObject* _tmp12_;
	JsonObject* _tmp13_;
	JsonObject* _tmp14_;
	JsonObject* _tmp15_;
	gchar* _tmp16_;
	GDataInputStream* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	GError* _error_;
	GError* _tmp20_;
	const gchar* _tmp21_;
	GError* _inner_error0_;
};

struct _XiCoreConnectionParamSpecResponseHandler {
	GParamSpec parent_instance;
};

struct _XiParamSpecCoreConnection {
	GParamSpec parent_instance;
};

static gint XiCoreConnection_private_offset;
static gpointer xi_core_connection_parent_class = NULL;
static gpointer xi_core_connection_response_handler_parent_class = NULL;

VALA_EXTERN gpointer xi_core_connection_ref (gpointer instance);
VALA_EXTERN void xi_core_connection_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_core_connection (const gchar* name,
                                           const gchar* nick,
                                           const gchar* blurb,
                                           GType object_type,
                                           GParamFlags flags);
VALA_EXTERN void xi_value_set_core_connection (GValue* value,
                                   gpointer v_object);
VALA_EXTERN void xi_value_take_core_connection (GValue* value,
                                    gpointer v_object);
VALA_EXTERN gpointer xi_value_get_core_connection (const GValue* value);
VALA_EXTERN GType xi_core_connection_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiCoreConnection, xi_core_connection_unref)
static gpointer xi_core_connection_response_handler_ref (gpointer instance);
static void xi_core_connection_response_handler_unref (gpointer instance);
static GParamSpec* xi_core_connection_param_spec_response_handler (const gchar* name,
                                                            const gchar* nick,
                                                            const gchar* blurb,
                                                            GType object_type,
                                                            GParamFlags flags) G_GNUC_UNUSED ;
static void xi_core_connection_value_set_response_handler (GValue* value,
                                                    gpointer v_object) G_GNUC_UNUSED ;
static void xi_core_connection_value_take_response_handler (GValue* value,
                                                     gpointer v_object) G_GNUC_UNUSED ;
static gpointer xi_core_connection_value_get_response_handler (const GValue* value) G_GNUC_UNUSED ;
static GType xi_core_connection_response_handler_get_type (void) G_GNUC_CONST  G_GNUC_UNUSED ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiCoreConnectionResponseHandler, xi_core_connection_response_handler_unref)
static void xi_core_connection_send (XiCoreConnection* self,
                              JsonObject* root);
static void _vala_JsonNode_free (JsonNode* self);
static void xi_core_connection_send_notification (XiCoreConnection* self,
                                           const gchar* method,
                                           JsonObject* params);
static void xi_core_connection_send_request_data_free (gpointer _data);
static void xi_core_connection_send_request (XiCoreConnection* self,
                                      const gchar* method,
                                      JsonObject* params,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_);
static JsonNode* xi_core_connection_send_request_finish (XiCoreConnection* self,
                                                  GAsyncResult* _res_);
static gboolean xi_core_connection_send_request_co (XiCoreConnectionSendRequestData* _data_);
static XiCoreConnectionResponseHandler* xi_core_connection_response_handler_new (void);
static XiCoreConnectionResponseHandler* xi_core_connection_response_handler_construct (GType object_type);
static gboolean _xi_core_connection_send_request_co_gsource_func (gpointer self);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
VALA_EXTERN void xi_core_connection_send_edit (XiCoreConnection* self,
                                   const gchar* view_id,
                                   const gchar* method,
                                   JsonObject* edit_params);
static void xi_core_connection_send_edit_array (XiCoreConnection* self,
                                         const gchar* view_id,
                                         const gchar* method,
                                         JsonArray* edit_params);
static void xi_core_connection_send_edit_request_data_free (gpointer _data);
static void xi_core_connection_send_edit_request (XiCoreConnection* self,
                                           const gchar* view_id,
                                           const gchar* method,
                                           JsonObject* edit_params,
                                           GAsyncReadyCallback _callback_,
                                           gpointer _user_data_);
static JsonNode* xi_core_connection_send_edit_request_finish (XiCoreConnection* self,
                                                       GAsyncResult* _res_);
static gboolean xi_core_connection_send_edit_request_co (XiCoreConnectionSendEditRequestData* _data_);
static void xi_core_connection_send_edit_request_ready (GObject* source_object,
                                                 GAsyncResult* _res_,
                                                 gpointer _user_data_);
VALA_EXTERN void xi_core_connection_send_client_started (XiCoreConnection* self,
                                             const gchar* config_dir,
                                             const gchar* client_extras_dir);
static void xi_core_connection_send_new_view_data_free (gpointer _data);
VALA_EXTERN void xi_core_connection_send_new_view (XiCoreConnection* self,
                                       const gchar* file_path,
                                       GAsyncReadyCallback _callback_,
                                       gpointer _user_data_);
VALA_EXTERN gchar* xi_core_connection_send_new_view_finish (XiCoreConnection* self,
                                                GAsyncResult* _res_);
static gboolean xi_core_connection_send_new_view_co (XiCoreConnectionSendNewViewData* _data_);
static void xi_core_connection_send_new_view_ready (GObject* source_object,
                                             GAsyncResult* _res_,
                                             gpointer _user_data_);
VALA_EXTERN void xi_core_connection_send_close_view (XiCoreConnection* self,
                                         const gchar* view_id);
VALA_EXTERN void xi_core_connection_send_insert (XiCoreConnection* self,
                                     const gchar* view_id,
                                     const gchar* chars);
VALA_EXTERN void xi_core_connection_send_paste (XiCoreConnection* self,
                                    const gchar* view_id,
                                    const gchar* chars);
static void xi_core_connection_send_copy_data_free (gpointer _data);
VALA_EXTERN void xi_core_connection_send_copy (XiCoreConnection* self,
                                   const gchar* view_id,
                                   GAsyncReadyCallback _callback_,
                                   gpointer _user_data_);
VALA_EXTERN gchar* xi_core_connection_send_copy_finish (XiCoreConnection* self,
                                            GAsyncResult* _res_);
static gboolean xi_core_connection_send_copy_co (XiCoreConnectionSendCopyData* _data_);
static void xi_core_connection_send_copy_ready (GObject* source_object,
                                         GAsyncResult* _res_,
                                         gpointer _user_data_);
static void xi_core_connection_send_cut_data_free (gpointer _data);
VALA_EXTERN void xi_core_connection_send_cut (XiCoreConnection* self,
                                  const gchar* view_id,
                                  GAsyncReadyCallback _callback_,
                                  gpointer _user_data_);
VALA_EXTERN gchar* xi_core_connection_send_cut_finish (XiCoreConnection* self,
                                           GAsyncResult* _res_);
static gboolean xi_core_connection_send_cut_co (XiCoreConnectionSendCutData* _data_);
static void xi_core_connection_send_cut_ready (GObject* source_object,
                                        GAsyncResult* _res_,
                                        gpointer _user_data_);
VALA_EXTERN void xi_core_connection_send_save (XiCoreConnection* self,
                                   const gchar* view_id,
                                   const gchar* file_path);
VALA_EXTERN void xi_core_connection_send_set_theme (XiCoreConnection* self,
                                        const gchar* theme_name);
VALA_EXTERN void xi_core_connection_send_scroll (XiCoreConnection* self,
                                     const gchar* view_id,
                                     gint64 first_line,
                                     gint64 last_line);
VALA_EXTERN void xi_core_connection_send_gesture (XiCoreConnection* self,
                                      const gchar* view_id,
                                      gint64 line,
                                      gint64 col,
                                      JsonObject* ty);
VALA_EXTERN void xi_core_connection_send_gesture_select (XiCoreConnection* self,
                                             const gchar* view_id,
                                             gint64 line,
                                             gint64 col,
                                             const gchar* granularity,
                                             gboolean multi);
VALA_EXTERN void xi_core_connection_send_gesture_select_extend (XiCoreConnection* self,
                                                    const gchar* view_id,
                                                    gint64 line,
                                                    gint64 col,
                                                    const gchar* granularity);
VALA_EXTERN void xi_core_connection_send_gesture_drag (XiCoreConnection* self,
                                           const gchar* view_id,
                                           gint64 line,
                                           gint64 col);
VALA_EXTERN void xi_core_connection_send_find (XiCoreConnection* self,
                                   const gchar* view_id,
                                   const gchar* chars,
                                   gboolean case_sensitive,
                                   gboolean regex,
                                   gboolean whole_words);
VALA_EXTERN void xi_core_connection_send_find_next (XiCoreConnection* self,
                                        const gchar* view_id,
                                        gboolean wrap_around,
                                        gboolean allow_same,
                                        const gchar* modify_selection);
VALA_EXTERN void xi_core_connection_send_find_previous (XiCoreConnection* self,
                                            const gchar* view_id,
                                            gboolean wrap_around,
                                            gboolean allow_same,
                                            const gchar* modify_selection);
VALA_EXTERN void xi_core_connection_send_replace (XiCoreConnection* self,
                                      const gchar* view_id,
                                      const gchar* chars);
VALA_EXTERN void xi_core_connection_send_highlight_find (XiCoreConnection* self,
                                             const gchar* view_id,
                                             gboolean visible);
VALA_EXTERN void xi_core_connection_send_selection_for_find (XiCoreConnection* self,
                                                 const gchar* view_id,
                                                 gboolean case_sensitive);
static void xi_core_connection_receive_response (XiCoreConnection* self,
                                          JsonObject* root);
static void xi_core_connection_receive_notification (XiCoreConnection* self,
                                              JsonObject* root);
static void xi_core_connection_receive_data_free (gpointer _data);
static void xi_core_connection_receive (XiCoreConnection* self,
                                 GAsyncReadyCallback _callback_,
                                 gpointer _user_data_);
static void xi_core_connection_receive_finish (XiCoreConnection* self,
                                        GAsyncResult* _res_);
static gboolean xi_core_connection_receive_co (XiCoreConnectionReceiveData* _data_);
static void xi_core_connection_receive_ready (GObject* source_object,
                                       GAsyncResult* _res_,
                                       gpointer _user_data_);
VALA_EXTERN XiCoreConnection* xi_core_connection_new (gchar** command,
                                          gint command_length1);
VALA_EXTERN XiCoreConnection* xi_core_connection_construct (GType object_type,
                                                gchar** command,
                                                gint command_length1);
static void _xi_core_connection_response_handler_unref0_ (gpointer var);
static void g_cclosure_user_marshal_VOID__INT64_INT64 (GClosure * closure,
                                                GValue * return_value,
                                                guint n_param_values,
                                                const GValue * param_values,
                                                gpointer invocation_hint,
                                                gpointer marshal_data);
static void g_cclosure_user_marshal_VOID__STRING_BOXED (GClosure * closure,
                                                 GValue * return_value,
                                                 guint n_param_values,
                                                 const GValue * param_values,
                                                 gpointer invocation_hint,
                                                 gpointer marshal_data);
static void xi_core_connection_response_handler_finalize (XiCoreConnectionResponseHandler * obj);
static GType xi_core_connection_response_handler_get_type_once (void);
static void xi_core_connection_finalize (XiCoreConnection * obj);
static GType xi_core_connection_get_type_once (void);

static inline gpointer
xi_core_connection_get_instance_private (XiCoreConnection* self)
{
	return G_STRUCT_MEMBER_P (self, XiCoreConnection_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static guint8*
string_get_data (const gchar* self,
                 gint* result_length1)
{
	guint8* result;
	guint8* res = NULL;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	gint _tmp1_;
	guint8* _tmp2_;
	gint _tmp2__length1;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res;
	_tmp2__length1 = res_length1;
	if (result_length1) {
		*result_length1 = _tmp2__length1;
	}
	result = _tmp2_;
	return result;
}

static void
_vala_JsonNode_free (JsonNode* self)
{
	g_boxed_free (json_node_get_type (), self);
}

static void
xi_core_connection_send (XiCoreConnection* self,
                         JsonObject* root)
{
	JsonNode* root_node = NULL;
	JsonNode* _tmp0_;
	JsonNode* _tmp1_;
	JsonGenerator* generator = NULL;
	JsonGenerator* _tmp2_;
	JsonGenerator* _tmp3_;
	JsonNode* _tmp4_;
	GOutputStream* core_stdin = NULL;
	GSubprocess* _tmp5_;
	GOutputStream* _tmp6_;
	GOutputStream* _tmp7_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (root != NULL);
	_tmp0_ = json_node_new (JSON_NODE_OBJECT);
	root_node = _tmp0_;
	_tmp1_ = root_node;
	json_node_set_object (_tmp1_, root);
	_tmp2_ = json_generator_new ();
	generator = _tmp2_;
	_tmp3_ = generator;
	_tmp4_ = root_node;
	json_generator_set_root (_tmp3_, _tmp4_);
	_tmp5_ = self->priv->core_process;
	_tmp6_ = g_subprocess_get_stdin_pipe (_tmp5_);
	_tmp7_ = _g_object_ref0 (_tmp6_);
	core_stdin = _tmp7_;
	{
		JsonGenerator* _tmp8_;
		GOutputStream* _tmp9_;
		GOutputStream* _tmp10_;
		guint8* _tmp11_;
		gint _tmp11__length1;
		gint _tmp12_ = 0;
		guint8* _tmp13_;
		gint _tmp13__length1;
		GOutputStream* _tmp14_;
		_tmp8_ = generator;
		_tmp9_ = core_stdin;
		json_generator_to_stream (_tmp8_, _tmp9_, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp10_ = core_stdin;
		_tmp11_ = string_get_data ("\n", &_tmp12_);
		_tmp11__length1 = _tmp12_;
		_tmp13_ = _tmp11_;
		_tmp13__length1 = _tmp11__length1;
		g_output_stream_write (_tmp10_, _tmp13_, (gsize) _tmp13__length1, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp14_ = core_stdin;
		g_output_stream_flush (_tmp14_, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* _error_ = NULL;
		GError* _tmp15_;
		const gchar* _tmp16_;
		_error_ = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp15_ = _error_;
		_tmp16_ = _tmp15_->message;
		g_critical ("CoreConnection.vala:46: %s", _tmp16_);
		_g_error_free0 (_error_);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (core_stdin);
		_g_object_unref0 (generator);
		__vala_JsonNode_free0 (root_node);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	_g_object_unref0 (core_stdin);
	_g_object_unref0 (generator);
	__vala_JsonNode_free0 (root_node);
}

static gpointer
_json_object_ref0 (gpointer self)
{
	return self ? json_object_ref (self) : NULL;
}

static void
xi_core_connection_send_notification (XiCoreConnection* self,
                                      const gchar* method,
                                      JsonObject* params)
{
	JsonObject* root = NULL;
	JsonObject* _tmp0_;
	JsonObject* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (method != NULL);
	g_return_if_fail (params != NULL);
	_tmp0_ = json_object_new ();
	root = _tmp0_;
	json_object_set_string_member (root, "method", method);
	_tmp1_ = _json_object_ref0 (params);
	json_object_set_object_member (root, "params", _tmp1_);
	xi_core_connection_send (self, root);
	_json_object_unref0 (root);
}

static void
xi_core_connection_send_request_data_free (gpointer _data)
{
	XiCoreConnectionSendRequestData* _data_;
	_data_ = _data;
	_g_free0 (_data_->method);
	_json_object_unref0 (_data_->params);
	__vala_JsonNode_free0 (_data_->result);
	_xi_core_connection_unref0 (_data_->self);
	g_slice_free (XiCoreConnectionSendRequestData, _data_);
}

static gpointer
_xi_core_connection_ref0 (gpointer self)
{
	return self ? xi_core_connection_ref (self) : NULL;
}

static void
xi_core_connection_send_request (XiCoreConnection* self,
                                 const gchar* method,
                                 JsonObject* params,
                                 GAsyncReadyCallback _callback_,
                                 gpointer _user_data_)
{
	XiCoreConnectionSendRequestData* _data_;
	XiCoreConnection* _tmp0_;
	gchar* _tmp1_;
	JsonObject* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (method != NULL);
	g_return_if_fail (params != NULL);
	_data_ = g_slice_new0 (XiCoreConnectionSendRequestData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, xi_core_connection_send_request_data_free);
	_tmp0_ = _xi_core_connection_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = g_strdup (method);
	_g_free0 (_data_->method);
	_data_->method = _tmp1_;
	_tmp2_ = _json_object_ref0 (params);
	_json_object_unref0 (_data_->params);
	_data_->params = _tmp2_;
	xi_core_connection_send_request_co (_data_);
}

static JsonNode*
xi_core_connection_send_request_finish (XiCoreConnection* self,
                                        GAsyncResult* _res_)
{
	JsonNode* result;
	XiCoreConnectionSendRequestData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static gboolean
_xi_core_connection_send_request_co_gsource_func (gpointer self)
{
	gboolean result;
	result = xi_core_connection_send_request_co (self);
	return result;
}

static gpointer
_xi_core_connection_response_handler_ref0 (gpointer self)
{
	return self ? xi_core_connection_response_handler_ref (self) : NULL;
}

static JsonNode*
_vala_JsonNode_copy (JsonNode* self)
{
	return g_boxed_copy (json_node_get_type (), self);
}

static gpointer
__vala_JsonNode_copy0 (gpointer self)
{
	return self ? _vala_JsonNode_copy (self) : NULL;
}

static gboolean
xi_core_connection_send_request_co (XiCoreConnectionSendRequestData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = xi_core_connection_response_handler_new ();
	_data_->response_handler = _data_->_tmp0_;
	(_data_->response_handler->callback_target_destroy_notify == NULL) ? NULL : (_data_->response_handler->callback_target_destroy_notify (_data_->response_handler->callback_target), NULL);
	_data_->response_handler->callback = NULL;
	_data_->response_handler->callback_target = NULL;
	_data_->response_handler->callback_target_destroy_notify = NULL;
	_data_->response_handler->callback = _xi_core_connection_send_request_co_gsource_func;
	_data_->response_handler->callback_target = _data_;
	_data_->response_handler->callback_target_destroy_notify = NULL;
	_data_->_tmp1_ = _data_->self->priv->response_handlers;
	_data_->_tmp2_ = _xi_core_connection_response_handler_ref0 (_data_->response_handler);
	g_hash_table_insert (_data_->_tmp1_, (gpointer) ((gintptr) _data_->self->priv->id), _data_->_tmp2_);
	_data_->_tmp3_ = json_object_new ();
	_data_->root = _data_->_tmp3_;
	_data_->_tmp4_ = _data_->self->priv->id;
	_data_->self->priv->id = _data_->_tmp4_ + 1;
	json_object_set_int_member (_data_->root, "id", (gint64) _data_->_tmp4_);
	json_object_set_string_member (_data_->root, "method", _data_->method);
	_data_->_tmp5_ = _json_object_ref0 (_data_->params);
	json_object_set_object_member (_data_->root, "params", _data_->_tmp5_);
	xi_core_connection_send (_data_->self, _data_->root);
	_data_->_state_ = 1;
	return FALSE;
	_state_1:
	;
	_data_->_tmp6_ = _data_->response_handler->result;
	_data_->_tmp7_ = __vala_JsonNode_copy0 (_data_->_tmp6_);
	_data_->result = _data_->_tmp7_;
	_json_object_unref0 (_data_->root);
	_xi_core_connection_response_handler_unref0 (_data_->response_handler);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

void
xi_core_connection_send_edit (XiCoreConnection* self,
                              const gchar* view_id,
                              const gchar* method,
                              JsonObject* edit_params)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	JsonObject* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (method != NULL);
	g_return_if_fail (edit_params != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_string_member (params, "method", method);
	json_object_set_string_member (params, "view_id", view_id);
	_tmp1_ = _json_object_ref0 (edit_params);
	json_object_set_object_member (params, "params", _tmp1_);
	xi_core_connection_send_notification (self, "edit", params);
	_json_object_unref0 (params);
}

static gpointer
_json_array_ref0 (gpointer self)
{
	return self ? json_array_ref (self) : NULL;
}

static void
xi_core_connection_send_edit_array (XiCoreConnection* self,
                                    const gchar* view_id,
                                    const gchar* method,
                                    JsonArray* edit_params)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	JsonArray* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (method != NULL);
	g_return_if_fail (edit_params != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_string_member (params, "method", method);
	json_object_set_string_member (params, "view_id", view_id);
	_tmp1_ = _json_array_ref0 (edit_params);
	json_object_set_array_member (params, "params", _tmp1_);
	xi_core_connection_send_notification (self, "edit", params);
	_json_object_unref0 (params);
}

static void
xi_core_connection_send_edit_request_data_free (gpointer _data)
{
	XiCoreConnectionSendEditRequestData* _data_;
	_data_ = _data;
	_g_free0 (_data_->view_id);
	_g_free0 (_data_->method);
	_json_object_unref0 (_data_->edit_params);
	__vala_JsonNode_free0 (_data_->result);
	_xi_core_connection_unref0 (_data_->self);
	g_slice_free (XiCoreConnectionSendEditRequestData, _data_);
}

static void
xi_core_connection_send_edit_request (XiCoreConnection* self,
                                      const gchar* view_id,
                                      const gchar* method,
                                      JsonObject* edit_params,
                                      GAsyncReadyCallback _callback_,
                                      gpointer _user_data_)
{
	XiCoreConnectionSendEditRequestData* _data_;
	XiCoreConnection* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	JsonObject* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (method != NULL);
	g_return_if_fail (edit_params != NULL);
	_data_ = g_slice_new0 (XiCoreConnectionSendEditRequestData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, xi_core_connection_send_edit_request_data_free);
	_tmp0_ = _xi_core_connection_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = g_strdup (view_id);
	_g_free0 (_data_->view_id);
	_data_->view_id = _tmp1_;
	_tmp2_ = g_strdup (method);
	_g_free0 (_data_->method);
	_data_->method = _tmp2_;
	_tmp3_ = _json_object_ref0 (edit_params);
	_json_object_unref0 (_data_->edit_params);
	_data_->edit_params = _tmp3_;
	xi_core_connection_send_edit_request_co (_data_);
}

static JsonNode*
xi_core_connection_send_edit_request_finish (XiCoreConnection* self,
                                             GAsyncResult* _res_)
{
	JsonNode* result;
	XiCoreConnectionSendEditRequestData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
xi_core_connection_send_edit_request_ready (GObject* source_object,
                                            GAsyncResult* _res_,
                                            gpointer _user_data_)
{
	XiCoreConnectionSendEditRequestData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	xi_core_connection_send_edit_request_co (_data_);
}

static gboolean
xi_core_connection_send_edit_request_co (XiCoreConnectionSendEditRequestData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = json_object_new ();
	_data_->params = _data_->_tmp0_;
	json_object_set_string_member (_data_->params, "method", _data_->method);
	json_object_set_string_member (_data_->params, "view_id", _data_->view_id);
	_data_->_tmp1_ = _json_object_ref0 (_data_->edit_params);
	json_object_set_object_member (_data_->params, "params", _data_->_tmp1_);
	_data_->_state_ = 1;
	xi_core_connection_send_request (_data_->self, "edit", _data_->params, xi_core_connection_send_edit_request_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp2_ = xi_core_connection_send_request_finish (_data_->self, _data_->_res_);
	_data_->result = _data_->_tmp2_;
	_json_object_unref0 (_data_->params);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

void
xi_core_connection_send_client_started (XiCoreConnection* self,
                                        const gchar* config_dir,
                                        const gchar* client_extras_dir)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (config_dir != NULL);
	g_return_if_fail (client_extras_dir != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_string_member (params, "config_dir", config_dir);
	json_object_set_string_member (params, "client_extras_dir", client_extras_dir);
	xi_core_connection_send_notification (self, "client_started", params);
	_json_object_unref0 (params);
}

static void
xi_core_connection_send_new_view_data_free (gpointer _data)
{
	XiCoreConnectionSendNewViewData* _data_;
	_data_ = _data;
	_g_free0 (_data_->file_path);
	_g_free0 (_data_->result);
	_xi_core_connection_unref0 (_data_->self);
	g_slice_free (XiCoreConnectionSendNewViewData, _data_);
}

void
xi_core_connection_send_new_view (XiCoreConnection* self,
                                  const gchar* file_path,
                                  GAsyncReadyCallback _callback_,
                                  gpointer _user_data_)
{
	XiCoreConnectionSendNewViewData* _data_;
	XiCoreConnection* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (XiCoreConnectionSendNewViewData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, xi_core_connection_send_new_view_data_free);
	_tmp0_ = _xi_core_connection_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = g_strdup (file_path);
	_g_free0 (_data_->file_path);
	_data_->file_path = _tmp1_;
	xi_core_connection_send_new_view_co (_data_);
}

gchar*
xi_core_connection_send_new_view_finish (XiCoreConnection* self,
                                         GAsyncResult* _res_)
{
	gchar* result;
	XiCoreConnectionSendNewViewData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
xi_core_connection_send_new_view_ready (GObject* source_object,
                                        GAsyncResult* _res_,
                                        gpointer _user_data_)
{
	XiCoreConnectionSendNewViewData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	xi_core_connection_send_new_view_co (_data_);
}

static gboolean
xi_core_connection_send_new_view_co (XiCoreConnectionSendNewViewData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = json_object_new ();
	_data_->params = _data_->_tmp0_;
	if (_data_->file_path != NULL) {
		_data_->_tmp1_ = _data_->params;
		json_object_set_string_member (_data_->_tmp1_, "file_path", _data_->file_path);
	}
	_data_->_tmp2_ = _data_->params;
	_data_->_state_ = 1;
	xi_core_connection_send_request (_data_->self, "new_view", _data_->_tmp2_, xi_core_connection_send_new_view_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp3_ = xi_core_connection_send_request_finish (_data_->self, _data_->_res_);
	_data_->_result_ = _data_->_tmp3_;
	_data_->_tmp4_ = json_node_get_string (_data_->_result_);
	_data_->_tmp5_ = g_strdup (_data_->_tmp4_);
	_data_->result = _data_->_tmp5_;
	__vala_JsonNode_free0 (_data_->_result_);
	_json_object_unref0 (_data_->params);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

void
xi_core_connection_send_close_view (XiCoreConnection* self,
                                    const gchar* view_id)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_string_member (params, "view_id", view_id);
	xi_core_connection_send_notification (self, "close_view", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_insert (XiCoreConnection* self,
                                const gchar* view_id,
                                const gchar* chars)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (chars != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_string_member (params, "chars", chars);
	xi_core_connection_send_edit (self, view_id, "insert", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_paste (XiCoreConnection* self,
                               const gchar* view_id,
                               const gchar* chars)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (chars != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_string_member (params, "chars", chars);
	xi_core_connection_send_edit (self, view_id, "paste", params);
	_json_object_unref0 (params);
}

static void
xi_core_connection_send_copy_data_free (gpointer _data)
{
	XiCoreConnectionSendCopyData* _data_;
	_data_ = _data;
	_g_free0 (_data_->view_id);
	_g_free0 (_data_->result);
	_xi_core_connection_unref0 (_data_->self);
	g_slice_free (XiCoreConnectionSendCopyData, _data_);
}

void
xi_core_connection_send_copy (XiCoreConnection* self,
                              const gchar* view_id,
                              GAsyncReadyCallback _callback_,
                              gpointer _user_data_)
{
	XiCoreConnectionSendCopyData* _data_;
	XiCoreConnection* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	_data_ = g_slice_new0 (XiCoreConnectionSendCopyData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, xi_core_connection_send_copy_data_free);
	_tmp0_ = _xi_core_connection_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = g_strdup (view_id);
	_g_free0 (_data_->view_id);
	_data_->view_id = _tmp1_;
	xi_core_connection_send_copy_co (_data_);
}

gchar*
xi_core_connection_send_copy_finish (XiCoreConnection* self,
                                     GAsyncResult* _res_)
{
	gchar* result;
	XiCoreConnectionSendCopyData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
xi_core_connection_send_copy_ready (GObject* source_object,
                                    GAsyncResult* _res_,
                                    gpointer _user_data_)
{
	XiCoreConnectionSendCopyData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	xi_core_connection_send_copy_co (_data_);
}

static gboolean
xi_core_connection_send_copy_co (XiCoreConnectionSendCopyData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = json_object_new ();
	_data_->_tmp1_ = _data_->_tmp0_;
	_data_->_state_ = 1;
	xi_core_connection_send_edit_request (_data_->self, _data_->view_id, "copy", _data_->_tmp1_, xi_core_connection_send_copy_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp2_ = xi_core_connection_send_edit_request_finish (_data_->self, _data_->_res_);
	_data_->_tmp3_ = _data_->_tmp2_;
	_json_object_unref0 (_data_->_tmp1_);
	_data_->_result_ = _data_->_tmp3_;
	_data_->_tmp4_ = json_node_get_string (_data_->_result_);
	_data_->_tmp5_ = g_strdup (_data_->_tmp4_);
	_data_->result = _data_->_tmp5_;
	__vala_JsonNode_free0 (_data_->_result_);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
xi_core_connection_send_cut_data_free (gpointer _data)
{
	XiCoreConnectionSendCutData* _data_;
	_data_ = _data;
	_g_free0 (_data_->view_id);
	_g_free0 (_data_->result);
	_xi_core_connection_unref0 (_data_->self);
	g_slice_free (XiCoreConnectionSendCutData, _data_);
}

void
xi_core_connection_send_cut (XiCoreConnection* self,
                             const gchar* view_id,
                             GAsyncReadyCallback _callback_,
                             gpointer _user_data_)
{
	XiCoreConnectionSendCutData* _data_;
	XiCoreConnection* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	_data_ = g_slice_new0 (XiCoreConnectionSendCutData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, xi_core_connection_send_cut_data_free);
	_tmp0_ = _xi_core_connection_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = g_strdup (view_id);
	_g_free0 (_data_->view_id);
	_data_->view_id = _tmp1_;
	xi_core_connection_send_cut_co (_data_);
}

gchar*
xi_core_connection_send_cut_finish (XiCoreConnection* self,
                                    GAsyncResult* _res_)
{
	gchar* result;
	XiCoreConnectionSendCutData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
	result = _data_->result;
	_data_->result = NULL;
	return result;
}

static void
xi_core_connection_send_cut_ready (GObject* source_object,
                                   GAsyncResult* _res_,
                                   gpointer _user_data_)
{
	XiCoreConnectionSendCutData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	xi_core_connection_send_cut_co (_data_);
}

static gboolean
xi_core_connection_send_cut_co (XiCoreConnectionSendCutData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = json_object_new ();
	_data_->_tmp1_ = _data_->_tmp0_;
	_data_->_state_ = 1;
	xi_core_connection_send_edit_request (_data_->self, _data_->view_id, "cut", _data_->_tmp1_, xi_core_connection_send_cut_ready, _data_);
	return FALSE;
	_state_1:
	_data_->_tmp2_ = xi_core_connection_send_edit_request_finish (_data_->self, _data_->_res_);
	_data_->_tmp3_ = _data_->_tmp2_;
	_json_object_unref0 (_data_->_tmp1_);
	_data_->_result_ = _data_->_tmp3_;
	_data_->_tmp4_ = json_node_get_string (_data_->_result_);
	_data_->_tmp5_ = g_strdup (_data_->_tmp4_);
	_data_->result = _data_->_tmp5_;
	__vala_JsonNode_free0 (_data_->_result_);
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

void
xi_core_connection_send_save (XiCoreConnection* self,
                              const gchar* view_id,
                              const gchar* file_path)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (file_path != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_string_member (params, "view_id", view_id);
	json_object_set_string_member (params, "file_path", file_path);
	xi_core_connection_send_notification (self, "save", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_set_theme (XiCoreConnection* self,
                                   const gchar* theme_name)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (theme_name != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_string_member (params, "theme_name", theme_name);
	xi_core_connection_send_notification (self, "set_theme", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_scroll (XiCoreConnection* self,
                                const gchar* view_id,
                                gint64 first_line,
                                gint64 last_line)
{
	JsonArray* params = NULL;
	JsonArray* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	_tmp0_ = json_array_new ();
	params = _tmp0_;
	json_array_add_int_element (params, first_line);
	json_array_add_int_element (params, last_line);
	xi_core_connection_send_edit_array (self, view_id, "scroll", params);
	_json_array_unref0 (params);
}

void
xi_core_connection_send_gesture (XiCoreConnection* self,
                                 const gchar* view_id,
                                 gint64 line,
                                 gint64 col,
                                 JsonObject* ty)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	JsonObject* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (ty != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_int_member (params, "line", line);
	json_object_set_int_member (params, "col", col);
	_tmp1_ = _json_object_ref0 (ty);
	json_object_set_object_member (params, "ty", _tmp1_);
	xi_core_connection_send_edit (self, view_id, "gesture", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_gesture_select (XiCoreConnection* self,
                                        const gchar* view_id,
                                        gint64 line,
                                        gint64 col,
                                        const gchar* granularity,
                                        gboolean multi)
{
	JsonObject* select = NULL;
	JsonObject* _tmp0_;
	JsonObject* ty = NULL;
	JsonObject* _tmp1_;
	JsonObject* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (granularity != NULL);
	_tmp0_ = json_object_new ();
	select = _tmp0_;
	json_object_set_string_member (select, "granularity", granularity);
	json_object_set_boolean_member (select, "multi", multi);
	_tmp1_ = json_object_new ();
	ty = _tmp1_;
	_tmp2_ = _json_object_ref0 (select);
	json_object_set_object_member (ty, "select", _tmp2_);
	xi_core_connection_send_gesture (self, view_id, line, col, ty);
	_json_object_unref0 (ty);
	_json_object_unref0 (select);
}

void
xi_core_connection_send_gesture_select_extend (XiCoreConnection* self,
                                               const gchar* view_id,
                                               gint64 line,
                                               gint64 col,
                                               const gchar* granularity)
{
	JsonObject* select = NULL;
	JsonObject* _tmp0_;
	JsonObject* ty = NULL;
	JsonObject* _tmp1_;
	JsonObject* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (granularity != NULL);
	_tmp0_ = json_object_new ();
	select = _tmp0_;
	json_object_set_string_member (select, "granularity", granularity);
	_tmp1_ = json_object_new ();
	ty = _tmp1_;
	_tmp2_ = _json_object_ref0 (select);
	json_object_set_object_member (ty, "select_extend", _tmp2_);
	xi_core_connection_send_gesture (self, view_id, line, col, ty);
	_json_object_unref0 (ty);
	_json_object_unref0 (select);
}

void
xi_core_connection_send_gesture_drag (XiCoreConnection* self,
                                      const gchar* view_id,
                                      gint64 line,
                                      gint64 col)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_int_member (params, "line", line);
	json_object_set_int_member (params, "col", col);
	json_object_set_string_member (params, "ty", "drag");
	xi_core_connection_send_edit (self, view_id, "gesture", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_find (XiCoreConnection* self,
                              const gchar* view_id,
                              const gchar* chars,
                              gboolean case_sensitive,
                              gboolean regex,
                              gboolean whole_words)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (chars != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_string_member (params, "chars", chars);
	json_object_set_boolean_member (params, "case_sensitive", case_sensitive);
	json_object_set_boolean_member (params, "regex", regex);
	json_object_set_boolean_member (params, "whole_words", whole_words);
	xi_core_connection_send_edit (self, view_id, "find", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_find_next (XiCoreConnection* self,
                                   const gchar* view_id,
                                   gboolean wrap_around,
                                   gboolean allow_same,
                                   const gchar* modify_selection)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (modify_selection != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_boolean_member (params, "wrap_around", wrap_around);
	json_object_set_boolean_member (params, "allow_same", allow_same);
	json_object_set_string_member (params, "modify_selection", modify_selection);
	xi_core_connection_send_edit (self, view_id, "find_next", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_find_previous (XiCoreConnection* self,
                                       const gchar* view_id,
                                       gboolean wrap_around,
                                       gboolean allow_same,
                                       const gchar* modify_selection)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (modify_selection != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_boolean_member (params, "wrap_around", wrap_around);
	json_object_set_boolean_member (params, "allow_same", allow_same);
	json_object_set_string_member (params, "modify_selection", modify_selection);
	xi_core_connection_send_edit (self, view_id, "find_previous", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_replace (XiCoreConnection* self,
                                 const gchar* view_id,
                                 const gchar* chars)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	g_return_if_fail (chars != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_string_member (params, "chars", chars);
	xi_core_connection_send_edit (self, view_id, "replace", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_highlight_find (XiCoreConnection* self,
                                        const gchar* view_id,
                                        gboolean visible)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_boolean_member (params, "visible", visible);
	xi_core_connection_send_edit (self, view_id, "highlight_find", params);
	_json_object_unref0 (params);
}

void
xi_core_connection_send_selection_for_find (XiCoreConnection* self,
                                            const gchar* view_id,
                                            gboolean case_sensitive)
{
	JsonObject* params = NULL;
	JsonObject* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (view_id != NULL);
	_tmp0_ = json_object_new ();
	params = _tmp0_;
	json_object_set_boolean_member (params, "case_sensitive", case_sensitive);
	xi_core_connection_send_edit (self, view_id, "selection_for_find", params);
	_json_object_unref0 (params);
}

static void
xi_core_connection_receive_response (XiCoreConnection* self,
                                     JsonObject* root)
{
	gint id = 0;
	XiCoreConnectionResponseHandler* handler = NULL;
	GHashTable* _tmp0_;
	gconstpointer _tmp1_;
	XiCoreConnectionResponseHandler* _tmp2_;
	XiCoreConnectionResponseHandler* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (root != NULL);
	id = (gint) json_object_get_int_member (root, "id");
	_tmp0_ = self->priv->response_handlers;
	_tmp1_ = g_hash_table_lookup (_tmp0_, (gpointer) ((gintptr) id));
	_tmp2_ = _xi_core_connection_response_handler_ref0 ((XiCoreConnectionResponseHandler*) _tmp1_);
	handler = _tmp2_;
	_tmp3_ = handler;
	if (_tmp3_ != NULL) {
		GHashTable* _tmp4_;
		XiCoreConnectionResponseHandler* _tmp5_;
		JsonNode* _tmp6_;
		JsonNode* _tmp7_;
		XiCoreConnectionResponseHandler* _tmp8_;
		GSourceFunc _tmp9_;
		gpointer _tmp9__target;
		_tmp4_ = self->priv->response_handlers;
		g_hash_table_remove (_tmp4_, (gpointer) ((gintptr) id));
		_tmp5_ = handler;
		_tmp6_ = json_object_get_member (root, "result");
		_tmp7_ = __vala_JsonNode_copy0 (_tmp6_);
		__vala_JsonNode_free0 (_tmp5_->result);
		_tmp5_->result = _tmp7_;
		_tmp8_ = handler;
		_tmp9_ = _tmp8_->callback;
		_tmp9__target = _tmp8_->callback_target;
		_tmp9_ (_tmp9__target);
	}
	_xi_core_connection_response_handler_unref0 (handler);
}

static void
xi_core_connection_receive_notification (XiCoreConnection* self,
                                         JsonObject* root)
{
	gchar* method = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	JsonObject* params = NULL;
	JsonObject* _tmp2_;
	JsonObject* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	GQuark _tmp7_ = 0U;
	static GQuark _tmp6_label0 = 0;
	static GQuark _tmp6_label1 = 0;
	static GQuark _tmp6_label2 = 0;
	static GQuark _tmp6_label3 = 0;
	static GQuark _tmp6_label4 = 0;
	static GQuark _tmp6_label5 = 0;
	static GQuark _tmp6_label6 = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (root != NULL);
	_tmp0_ = json_object_get_string_member (root, "method");
	_tmp1_ = g_strdup (_tmp0_);
	method = _tmp1_;
	_tmp2_ = json_object_get_object_member (root, "params");
	_tmp3_ = _json_object_ref0 (_tmp2_);
	params = _tmp3_;
	_tmp4_ = method;
	_tmp5_ = _tmp4_;
	_tmp7_ = (NULL == _tmp5_) ? 0 : g_quark_from_string (_tmp5_);
	if (_tmp7_ == ((0 != _tmp6_label0) ? _tmp6_label0 : (_tmp6_label0 = g_quark_from_static_string ("update")))) {
		switch (0) {
			default:
			{
				gchar* view_id = NULL;
				JsonObject* _tmp8_;
				const gchar* _tmp9_;
				gchar* _tmp10_;
				JsonObject* update = NULL;
				JsonObject* _tmp11_;
				JsonObject* _tmp12_;
				JsonObject* _tmp13_;
				const gchar* _tmp14_;
				JsonObject* _tmp15_;
				_tmp8_ = params;
				_tmp9_ = json_object_get_string_member (_tmp8_, "view_id");
				_tmp10_ = g_strdup (_tmp9_);
				view_id = _tmp10_;
				_tmp11_ = params;
				_tmp12_ = json_object_get_object_member (_tmp11_, "update");
				_tmp13_ = _json_object_ref0 (_tmp12_);
				update = _tmp13_;
				_tmp14_ = view_id;
				_tmp15_ = update;
				g_signal_emit (self, xi_core_connection_signals[XI_CORE_CONNECTION_UPDATE_RECEIVED_SIGNAL], g_quark_from_string (_tmp14_), _tmp15_);
				_json_object_unref0 (update);
				_g_free0 (view_id);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label1) ? _tmp6_label1 : (_tmp6_label1 = g_quark_from_static_string ("scroll_to")))) {
		switch (0) {
			default:
			{
				gchar* view_id = NULL;
				JsonObject* _tmp16_;
				const gchar* _tmp17_;
				gchar* _tmp18_;
				gint64 scroll_to_line = 0LL;
				JsonObject* _tmp19_;
				gint64 scroll_to_col = 0LL;
				JsonObject* _tmp20_;
				const gchar* _tmp21_;
				_tmp16_ = params;
				_tmp17_ = json_object_get_string_member (_tmp16_, "view_id");
				_tmp18_ = g_strdup (_tmp17_);
				view_id = _tmp18_;
				_tmp19_ = params;
				scroll_to_line = json_object_get_int_member (_tmp19_, "line");
				_tmp20_ = params;
				scroll_to_col = json_object_get_int_member (_tmp20_, "col");
				_tmp21_ = view_id;
				g_signal_emit (self, xi_core_connection_signals[XI_CORE_CONNECTION_SCROLL_TO_RECEIVED_SIGNAL], g_quark_from_string (_tmp21_), scroll_to_line, scroll_to_col);
				_g_free0 (view_id);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label2) ? _tmp6_label2 : (_tmp6_label2 = g_quark_from_static_string ("def_style")))) {
		switch (0) {
			default:
			{
				JsonObject* _tmp22_;
				_tmp22_ = params;
				g_signal_emit (self, xi_core_connection_signals[XI_CORE_CONNECTION_DEF_STYLE_RECEIVED_SIGNAL], 0, _tmp22_);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label3) ? _tmp6_label3 : (_tmp6_label3 = g_quark_from_static_string ("config_changed")))) {
		switch (0) {
			default:
			{
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label4) ? _tmp6_label4 : (_tmp6_label4 = g_quark_from_static_string ("available_themes")))) {
		switch (0) {
			default:
			{
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label5) ? _tmp6_label5 : (_tmp6_label5 = g_quark_from_static_string ("theme_changed")))) {
		switch (0) {
			default:
			{
				gchar* name = NULL;
				JsonObject* _tmp23_;
				const gchar* _tmp24_;
				gchar* _tmp25_;
				JsonObject* theme = NULL;
				JsonObject* _tmp26_;
				JsonObject* _tmp27_;
				JsonObject* _tmp28_;
				const gchar* _tmp29_;
				JsonObject* _tmp30_;
				_tmp23_ = params;
				_tmp24_ = json_object_get_string_member (_tmp23_, "name");
				_tmp25_ = g_strdup (_tmp24_);
				name = _tmp25_;
				_tmp26_ = params;
				_tmp27_ = json_object_get_object_member (_tmp26_, "theme");
				_tmp28_ = _json_object_ref0 (_tmp27_);
				theme = _tmp28_;
				_tmp29_ = name;
				_tmp30_ = theme;
				g_signal_emit (self, xi_core_connection_signals[XI_CORE_CONNECTION_THEME_CHANGED_RECEIVED_SIGNAL], 0, _tmp29_, _tmp30_);
				_json_object_unref0 (theme);
				_g_free0 (name);
				break;
			}
		}
	} else if (_tmp7_ == ((0 != _tmp6_label6) ? _tmp6_label6 : (_tmp6_label6 = g_quark_from_static_string ("alert")))) {
		switch (0) {
			default:
			{
				gchar* msg = NULL;
				JsonObject* _tmp31_;
				const gchar* _tmp32_;
				gchar* _tmp33_;
				const gchar* _tmp34_;
				_tmp31_ = params;
				_tmp32_ = json_object_get_string_member (_tmp31_, "msg");
				_tmp33_ = g_strdup (_tmp32_);
				msg = _tmp33_;
				_tmp34_ = msg;
				g_signal_emit (self, xi_core_connection_signals[XI_CORE_CONNECTION_ALERT_RECEIVED_SIGNAL], 0, _tmp34_);
				_g_free0 (msg);
				break;
			}
		}
	}
	_json_object_unref0 (params);
	_g_free0 (method);
}

static void
xi_core_connection_receive_data_free (gpointer _data)
{
	XiCoreConnectionReceiveData* _data_;
	_data_ = _data;
	_xi_core_connection_unref0 (_data_->self);
	g_slice_free (XiCoreConnectionReceiveData, _data_);
}

static void
xi_core_connection_receive (XiCoreConnection* self,
                            GAsyncReadyCallback _callback_,
                            gpointer _user_data_)
{
	XiCoreConnectionReceiveData* _data_;
	XiCoreConnection* _tmp0_;
	g_return_if_fail (self != NULL);
	_data_ = g_slice_new0 (XiCoreConnectionReceiveData);
	_data_->_async_result = g_task_new (NULL, NULL, _callback_, _user_data_);
	g_task_set_task_data (_data_->_async_result, _data_, xi_core_connection_receive_data_free);
	_tmp0_ = _xi_core_connection_ref0 (self);
	_data_->self = _tmp0_;
	xi_core_connection_receive_co (_data_);
}

static void
xi_core_connection_receive_finish (XiCoreConnection* self,
                                   GAsyncResult* _res_)
{
	XiCoreConnectionReceiveData* _data_;
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
}

static void
xi_core_connection_receive_ready (GObject* source_object,
                                  GAsyncResult* _res_,
                                  gpointer _user_data_)
{
	XiCoreConnectionReceiveData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	xi_core_connection_receive_co (_data_);
}

static gboolean
xi_core_connection_receive_co (XiCoreConnectionReceiveData* _data_)
{
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		case 2:
		goto _state_2;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	{
		_data_->_tmp0_ = _data_->self->priv->core_process;
		_data_->_tmp1_ = g_subprocess_get_stdout_pipe (_data_->_tmp0_);
		_data_->_tmp2_ = g_data_input_stream_new (_data_->_tmp1_);
		_data_->core_stdout = _data_->_tmp2_;
		_data_->_tmp3_ = _data_->core_stdout;
		_data_->_state_ = 1;
		g_data_input_stream_read_line_async (_data_->_tmp3_, G_PRIORITY_DEFAULT, NULL, xi_core_connection_receive_ready, _data_);
		return FALSE;
		_state_1:
		_data_->_tmp4_ = g_data_input_stream_read_line_finish_utf8 (_data_->_tmp3_, _data_->_res_, NULL, &_data_->_inner_error0_);
		_data_->line = _data_->_tmp4_;
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
			_g_object_unref0 (_data_->core_stdout);
			goto __catch0_g_error;
		}
		while (TRUE) {
			_data_->_tmp5_ = _data_->line;
			if (!(_data_->_tmp5_ != NULL)) {
				break;
			}
			_data_->_tmp6_ = json_parser_new ();
			_data_->parser = _data_->_tmp6_;
			_data_->_tmp7_ = _data_->parser;
			_data_->_tmp8_ = _data_->line;
			json_parser_load_from_data (_data_->_tmp7_, _data_->_tmp8_, (gssize) -1, &_data_->_inner_error0_);
			if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
				_g_object_unref0 (_data_->parser);
				_g_free0 (_data_->line);
				_g_object_unref0 (_data_->core_stdout);
				goto __catch0_g_error;
			}
			_data_->_tmp9_ = _data_->parser;
			_data_->_tmp10_ = json_parser_get_root (_data_->_tmp9_);
			_data_->_tmp11_ = json_node_get_object (_data_->_tmp10_);
			_data_->_tmp12_ = _json_object_ref0 (_data_->_tmp11_);
			_data_->root = _data_->_tmp12_;
			_data_->_tmp13_ = _data_->root;
			if (json_object_has_member (_data_->_tmp13_, "id")) {
				_data_->_tmp14_ = _data_->root;
				xi_core_connection_receive_response (_data_->self, _data_->_tmp14_);
			} else {
				_data_->_tmp15_ = _data_->root;
				xi_core_connection_receive_notification (_data_->self, _data_->_tmp15_);
			}
			_data_->_tmp17_ = _data_->core_stdout;
			_data_->_state_ = 2;
			g_data_input_stream_read_line_async (_data_->_tmp17_, G_PRIORITY_DEFAULT, NULL, xi_core_connection_receive_ready, _data_);
			return FALSE;
			_state_2:
			_data_->_tmp18_ = g_data_input_stream_read_line_finish_utf8 (_data_->_tmp17_, _data_->_res_, NULL, &_data_->_inner_error0_);
			_data_->_tmp16_ = _data_->_tmp18_;
			if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
				_json_object_unref0 (_data_->root);
				_g_object_unref0 (_data_->parser);
				_g_free0 (_data_->line);
				_g_object_unref0 (_data_->core_stdout);
				goto __catch0_g_error;
			}
			_data_->_tmp19_ = _data_->_tmp16_;
			_data_->_tmp16_ = NULL;
			_g_free0 (_data_->line);
			_data_->line = _data_->_tmp19_;
			_g_free0 (_data_->_tmp16_);
			_json_object_unref0 (_data_->root);
			_g_object_unref0 (_data_->parser);
		}
		_g_free0 (_data_->line);
		_g_object_unref0 (_data_->core_stdout);
	}
	goto __finally0;
	__catch0_g_error:
	{
		_data_->_error_ = _data_->_inner_error0_;
		_data_->_inner_error0_ = NULL;
		_data_->_tmp20_ = _data_->_error_;
		_data_->_tmp21_ = _data_->_tmp20_->message;
		g_critical ("CoreConnection.vala:299: %s", _data_->_tmp21_);
		_g_error_free0 (_data_->_error_);
	}
	__finally0:
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
		g_clear_error (&_data_->_inner_error0_);
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
	if (_data_->_state_ != 0) {
		while (!g_task_get_completed (_data_->_async_result)) {
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
		}
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}

static void
_xi_core_connection_response_handler_unref0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (xi_core_connection_response_handler_unref (var), NULL));
}

XiCoreConnection*
xi_core_connection_construct (GType object_type,
                              gchar** command,
                              gint command_length1)
{
	XiCoreConnection* self = NULL;
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GHashTable* _tmp2_;
	GError* _inner_error0_ = NULL;
	self = (XiCoreConnection*) g_type_create_instance (object_type);
	_tmp0_ = g_direct_hash;
	_tmp1_ = g_direct_equal;
	_tmp2_ = g_hash_table_new_full (_tmp0_, _tmp1_, NULL, _xi_core_connection_response_handler_unref0_);
	_g_hash_table_unref0 (self->priv->response_handlers);
	self->priv->response_handlers = _tmp2_;
	{
		GSubprocess* _tmp3_ = NULL;
		GSubprocess* _tmp4_;
		GSubprocess* _tmp5_;
		_tmp4_ = g_subprocess_newv (command, G_SUBPROCESS_FLAGS_STDIN_PIPE | G_SUBPROCESS_FLAGS_STDOUT_PIPE, &_inner_error0_);
		_tmp3_ = _tmp4_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp5_ = _tmp3_;
		_tmp3_ = NULL;
		_g_object_unref0 (self->priv->core_process);
		self->priv->core_process = _tmp5_;
		xi_core_connection_receive (self, NULL, NULL);
		_g_object_unref0 (_tmp3_);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* _error_ = NULL;
		GError* _tmp6_;
		const gchar* _tmp7_;
		_error_ = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp6_ = _error_;
		_tmp7_ = _tmp6_->message;
		g_critical ("CoreConnection.vala:309: %s", _tmp7_);
		_g_error_free0 (_error_);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	return self;
}

XiCoreConnection*
xi_core_connection_new (gchar** command,
                        gint command_length1)
{
	return xi_core_connection_construct (XI_TYPE_CORE_CONNECTION, command, command_length1);
}

static void
g_cclosure_user_marshal_VOID__INT64_INT64 (GClosure * closure,
                                           GValue * return_value,
                                           guint n_param_values,
                                           const GValue * param_values,
                                           gpointer invocation_hint,
                                           gpointer marshal_data)
{
	typedef void (*GMarshalFunc_VOID__INT64_INT64) (gpointer data1, gint64 arg_1, gint64 arg_2, gpointer data2);
	register GMarshalFunc_VOID__INT64_INT64 callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__INT64_INT64) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_int64 (param_values + 1), g_value_get_int64 (param_values + 2), data2);
}

static void
g_cclosure_user_marshal_VOID__STRING_BOXED (GClosure * closure,
                                            GValue * return_value,
                                            guint n_param_values,
                                            const GValue * param_values,
                                            gpointer invocation_hint,
                                            gpointer marshal_data)
{
	typedef void (*GMarshalFunc_VOID__STRING_BOXED) (gpointer data1, const char* arg_1, gpointer arg_2, gpointer data2);
	register GMarshalFunc_VOID__STRING_BOXED callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__STRING_BOXED) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_string (param_values + 1), g_value_get_boxed (param_values + 2), data2);
}

static XiCoreConnectionResponseHandler*
xi_core_connection_response_handler_construct (GType object_type)
{
	XiCoreConnectionResponseHandler* self = NULL;
	self = (XiCoreConnectionResponseHandler*) g_type_create_instance (object_type);
	return self;
}

static XiCoreConnectionResponseHandler*
xi_core_connection_response_handler_new (void)
{
	return xi_core_connection_response_handler_construct (XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER);
}

static void
xi_core_connection_value_response_handler_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
xi_core_connection_value_response_handler_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		xi_core_connection_response_handler_unref (value->data[0].v_pointer);
	}
}

static void
xi_core_connection_value_response_handler_copy_value (const GValue* src_value,
                                                      GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = xi_core_connection_response_handler_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
xi_core_connection_value_response_handler_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
xi_core_connection_value_response_handler_collect_value (GValue* value,
                                                         guint n_collect_values,
                                                         GTypeCValue* collect_values,
                                                         guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		XiCoreConnectionResponseHandler * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = xi_core_connection_response_handler_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
xi_core_connection_value_response_handler_lcopy_value (const GValue* value,
                                                       guint n_collect_values,
                                                       GTypeCValue* collect_values,
                                                       guint collect_flags)
{
	XiCoreConnectionResponseHandler ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = xi_core_connection_response_handler_ref (value->data[0].v_pointer);
	}
	return NULL;
}

static GParamSpec*
xi_core_connection_param_spec_response_handler (const gchar* name,
                                                const gchar* nick,
                                                const gchar* blurb,
                                                GType object_type,
                                                GParamFlags flags)
{
	XiCoreConnectionParamSpecResponseHandler* spec;
	g_return_val_if_fail (g_type_is_a (object_type, XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

static gpointer
xi_core_connection_value_get_response_handler (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER), NULL);
	return value->data[0].v_pointer;
}

static void
xi_core_connection_value_set_response_handler (GValue* value,
                                               gpointer v_object)
{
	XiCoreConnectionResponseHandler * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		xi_core_connection_response_handler_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_core_connection_response_handler_unref (old);
	}
}

static void
xi_core_connection_value_take_response_handler (GValue* value,
                                                gpointer v_object)
{
	XiCoreConnectionResponseHandler * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_core_connection_response_handler_unref (old);
	}
}

static void
xi_core_connection_response_handler_class_init (XiCoreConnectionResponseHandlerClass * klass,
                                                gpointer klass_data)
{
	xi_core_connection_response_handler_parent_class = g_type_class_peek_parent (klass);
	((XiCoreConnectionResponseHandlerClass *) klass)->finalize = xi_core_connection_response_handler_finalize;
}

static void
xi_core_connection_response_handler_instance_init (XiCoreConnectionResponseHandler * self,
                                                   gpointer klass)
{
	self->ref_count = 1;
}

static void
xi_core_connection_response_handler_finalize (XiCoreConnectionResponseHandler * obj)
{
	XiCoreConnectionResponseHandler * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_CORE_CONNECTION_TYPE_RESPONSE_HANDLER, XiCoreConnectionResponseHandler);
	g_signal_handlers_destroy (self);
	(self->callback_target_destroy_notify == NULL) ? NULL : (self->callback_target_destroy_notify (self->callback_target), NULL);
	self->callback = NULL;
	self->callback_target = NULL;
	self->callback_target_destroy_notify = NULL;
	__vala_JsonNode_free0 (self->result);
}

static GType
xi_core_connection_response_handler_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { xi_core_connection_value_response_handler_init, xi_core_connection_value_response_handler_free_value, xi_core_connection_value_response_handler_copy_value, xi_core_connection_value_response_handler_peek_pointer, "p", xi_core_connection_value_response_handler_collect_value, "p", xi_core_connection_value_response_handler_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (XiCoreConnectionResponseHandlerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_core_connection_response_handler_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiCoreConnectionResponseHandler), 0, (GInstanceInitFunc) xi_core_connection_response_handler_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType xi_core_connection_response_handler_type_id;
	xi_core_connection_response_handler_type_id = g_type_register_fundamental (g_type_fundamental_next (), "XiCoreConnectionResponseHandler", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return xi_core_connection_response_handler_type_id;
}

static GType
xi_core_connection_response_handler_get_type (void)
{
	static volatile gsize xi_core_connection_response_handler_type_id__once = 0;
	if (g_once_init_enter (&xi_core_connection_response_handler_type_id__once)) {
		GType xi_core_connection_response_handler_type_id;
		xi_core_connection_response_handler_type_id = xi_core_connection_response_handler_get_type_once ();
		g_once_init_leave (&xi_core_connection_response_handler_type_id__once, xi_core_connection_response_handler_type_id);
	}
	return xi_core_connection_response_handler_type_id__once;
}

static gpointer
xi_core_connection_response_handler_ref (gpointer instance)
{
	XiCoreConnectionResponseHandler * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

static void
xi_core_connection_response_handler_unref (gpointer instance)
{
	XiCoreConnectionResponseHandler * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		XI_CORE_CONNECTION_RESPONSE_HANDLER_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

static void
xi_value_core_connection_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
xi_value_core_connection_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		xi_core_connection_unref (value->data[0].v_pointer);
	}
}

static void
xi_value_core_connection_copy_value (const GValue* src_value,
                                     GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = xi_core_connection_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
xi_value_core_connection_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
xi_value_core_connection_collect_value (GValue* value,
                                        guint n_collect_values,
                                        GTypeCValue* collect_values,
                                        guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		XiCoreConnection * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = xi_core_connection_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
xi_value_core_connection_lcopy_value (const GValue* value,
                                      guint n_collect_values,
                                      GTypeCValue* collect_values,
                                      guint collect_flags)
{
	XiCoreConnection ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = xi_core_connection_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
xi_param_spec_core_connection (const gchar* name,
                               const gchar* nick,
                               const gchar* blurb,
                               GType object_type,
                               GParamFlags flags)
{
	XiParamSpecCoreConnection* spec;
	g_return_val_if_fail (g_type_is_a (object_type, XI_TYPE_CORE_CONNECTION), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
xi_value_get_core_connection (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_CORE_CONNECTION), NULL);
	return value->data[0].v_pointer;
}

void
xi_value_set_core_connection (GValue* value,
                              gpointer v_object)
{
	XiCoreConnection * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_CORE_CONNECTION));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_CORE_CONNECTION));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		xi_core_connection_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_core_connection_unref (old);
	}
}

void
xi_value_take_core_connection (GValue* value,
                               gpointer v_object)
{
	XiCoreConnection * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_CORE_CONNECTION));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_CORE_CONNECTION));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_core_connection_unref (old);
	}
}

static void
xi_core_connection_class_init (XiCoreConnectionClass * klass,
                               gpointer klass_data)
{
	xi_core_connection_parent_class = g_type_class_peek_parent (klass);
	((XiCoreConnectionClass *) klass)->finalize = xi_core_connection_finalize;
	g_type_class_adjust_private_offset (klass, &XiCoreConnection_private_offset);
	xi_core_connection_signals[XI_CORE_CONNECTION_UPDATE_RECEIVED_SIGNAL] = g_signal_new ("update-received", XI_TYPE_CORE_CONNECTION, G_SIGNAL_RUN_LAST | G_SIGNAL_DETAILED, 0, NULL, NULL, g_cclosure_marshal_VOID__BOXED, G_TYPE_NONE, 1, json_object_get_type ());
	xi_core_connection_signals[XI_CORE_CONNECTION_SCROLL_TO_RECEIVED_SIGNAL] = g_signal_new ("scroll-to-received", XI_TYPE_CORE_CONNECTION, G_SIGNAL_RUN_LAST | G_SIGNAL_DETAILED, 0, NULL, NULL, g_cclosure_user_marshal_VOID__INT64_INT64, G_TYPE_NONE, 2, G_TYPE_INT64, G_TYPE_INT64);
	xi_core_connection_signals[XI_CORE_CONNECTION_DEF_STYLE_RECEIVED_SIGNAL] = g_signal_new ("def-style-received", XI_TYPE_CORE_CONNECTION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__BOXED, G_TYPE_NONE, 1, json_object_get_type ());
	xi_core_connection_signals[XI_CORE_CONNECTION_THEME_CHANGED_RECEIVED_SIGNAL] = g_signal_new ("theme-changed-received", XI_TYPE_CORE_CONNECTION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__STRING_BOXED, G_TYPE_NONE, 2, G_TYPE_STRING, json_object_get_type ());
	xi_core_connection_signals[XI_CORE_CONNECTION_ALERT_RECEIVED_SIGNAL] = g_signal_new ("alert-received", XI_TYPE_CORE_CONNECTION, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
}

static void
xi_core_connection_instance_init (XiCoreConnection * self,
                                  gpointer klass)
{
	self->priv = xi_core_connection_get_instance_private (self);
	self->ref_count = 1;
}

static void
xi_core_connection_finalize (XiCoreConnection * obj)
{
	XiCoreConnection * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_CORE_CONNECTION, XiCoreConnection);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->priv->core_process);
	_g_hash_table_unref0 (self->priv->response_handlers);
}

static GType
xi_core_connection_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { xi_value_core_connection_init, xi_value_core_connection_free_value, xi_value_core_connection_copy_value, xi_value_core_connection_peek_pointer, "p", xi_value_core_connection_collect_value, "p", xi_value_core_connection_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (XiCoreConnectionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_core_connection_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiCoreConnection), 0, (GInstanceInitFunc) xi_core_connection_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType xi_core_connection_type_id;
	xi_core_connection_type_id = g_type_register_fundamental (g_type_fundamental_next (), "XiCoreConnection", &g_define_type_info, &g_define_type_fundamental_info, 0);
	XiCoreConnection_private_offset = g_type_add_instance_private (xi_core_connection_type_id, sizeof (XiCoreConnectionPrivate));
	return xi_core_connection_type_id;
}

GType
xi_core_connection_get_type (void)
{
	static volatile gsize xi_core_connection_type_id__once = 0;
	if (g_once_init_enter (&xi_core_connection_type_id__once)) {
		GType xi_core_connection_type_id;
		xi_core_connection_type_id = xi_core_connection_get_type_once ();
		g_once_init_leave (&xi_core_connection_type_id__once, xi_core_connection_type_id);
	}
	return xi_core_connection_type_id__once;
}

gpointer
xi_core_connection_ref (gpointer instance)
{
	XiCoreConnection * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
xi_core_connection_unref (gpointer instance)
{
	XiCoreConnection * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		XI_CORE_CONNECTION_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

