/* EditViewContainer.c generated by valac 0.56.18, the Vala compiler
 * generated from EditViewContainer.vala, do not modify */

/* Copyright 2017-2018 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_EDIT_VIEW_CONTAINER (xi_edit_view_container_get_type ())
#define XI_EDIT_VIEW_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_EDIT_VIEW_CONTAINER, XiEditViewContainer))
#define XI_EDIT_VIEW_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_EDIT_VIEW_CONTAINER, XiEditViewContainerClass))
#define XI_IS_EDIT_VIEW_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_EDIT_VIEW_CONTAINER))
#define XI_IS_EDIT_VIEW_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_EDIT_VIEW_CONTAINER))
#define XI_EDIT_VIEW_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_EDIT_VIEW_CONTAINER, XiEditViewContainerClass))

typedef struct _XiEditViewContainer XiEditViewContainer;
typedef struct _XiEditViewContainerClass XiEditViewContainerClass;
typedef struct _XiEditViewContainerPrivate XiEditViewContainerPrivate;

#define XI_TYPE_EDIT_VIEW (xi_edit_view_get_type ())
#define XI_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_EDIT_VIEW, XiEditView))
#define XI_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_EDIT_VIEW, XiEditViewClass))
#define XI_IS_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_EDIT_VIEW))
#define XI_IS_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_EDIT_VIEW))
#define XI_EDIT_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_EDIT_VIEW, XiEditViewClass))

typedef struct _XiEditView XiEditView;
typedef struct _XiEditViewClass XiEditViewClass;

#define XI_TYPE_FIND_BAR (xi_find_bar_get_type ())
#define XI_FIND_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_FIND_BAR, XiFindBar))
#define XI_FIND_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_FIND_BAR, XiFindBarClass))
#define XI_IS_FIND_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_FIND_BAR))
#define XI_IS_FIND_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_FIND_BAR))
#define XI_FIND_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_FIND_BAR, XiFindBarClass))

typedef struct _XiFindBar XiFindBar;
typedef struct _XiFindBarClass XiFindBarClass;
enum  {
	XI_EDIT_VIEW_CONTAINER_0_PROPERTY,
	XI_EDIT_VIEW_CONTAINER_NUM_PROPERTIES
};
static GParamSpec* xi_edit_view_container_properties[XI_EDIT_VIEW_CONTAINER_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define XI_TYPE_CORE_CONNECTION (xi_core_connection_get_type ())
#define XI_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnection))
#define XI_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))
#define XI_IS_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_CORE_CONNECTION))
#define XI_IS_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_CORE_CONNECTION))
#define XI_CORE_CONNECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))

typedef struct _XiCoreConnection XiCoreConnection;
typedef struct _XiCoreConnectionClass XiCoreConnectionClass;

struct _XiEditViewContainer {
	GtkBox parent_instance;
	XiEditViewContainerPrivate * priv;
};

struct _XiEditViewContainerClass {
	GtkBoxClass parent_class;
};

struct _XiEditViewContainerPrivate {
	XiEditView* edit_view;
	XiFindBar* find_bar;
};

static gint XiEditViewContainer_private_offset;
static gpointer xi_edit_view_container_parent_class = NULL;

VALA_EXTERN GType xi_edit_view_container_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiEditViewContainer, g_object_unref)
VALA_EXTERN GType xi_edit_view_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiEditView, g_object_unref)
VALA_EXTERN GType xi_find_bar_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiFindBar, g_object_unref)
VALA_EXTERN gpointer xi_core_connection_ref (gpointer instance);
VALA_EXTERN void xi_core_connection_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_core_connection (const gchar* name,
                                           const gchar* nick,
                                           const gchar* blurb,
                                           GType object_type,
                                           GParamFlags flags);
VALA_EXTERN void xi_value_set_core_connection (GValue* value,
                                   gpointer v_object);
VALA_EXTERN void xi_value_take_core_connection (GValue* value,
                                    gpointer v_object);
VALA_EXTERN gpointer xi_value_get_core_connection (const GValue* value);
VALA_EXTERN GType xi_core_connection_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiCoreConnection, xi_core_connection_unref)
VALA_EXTERN XiEditViewContainer* xi_edit_view_container_new (XiCoreConnection* core_connection,
                                                 const gchar* view_id,
                                                 GFile* file);
VALA_EXTERN XiEditViewContainer* xi_edit_view_container_construct (GType object_type,
                                                       XiCoreConnection* core_connection,
                                                       const gchar* view_id,
                                                       GFile* file);
VALA_EXTERN XiEditView* xi_edit_view_new (XiCoreConnection* core_connection,
                              const gchar* view_id,
                              GFile* file);
VALA_EXTERN XiEditView* xi_edit_view_construct (GType object_type,
                                    XiCoreConnection* core_connection,
                                    const gchar* view_id,
                                    GFile* file);
VALA_EXTERN XiFindBar* xi_find_bar_new (XiCoreConnection* core_connection,
                            const gchar* view_id);
VALA_EXTERN XiFindBar* xi_find_bar_construct (GType object_type,
                                  XiCoreConnection* core_connection,
                                  const gchar* view_id);
static void __lambda9_ (XiEditViewContainer* self);
static void ___lambda9__gtk_widget_hide (GtkWidget* _sender,
                                  gpointer self);
static void xi_edit_view_container_real_grab_focus (GtkWidget* base);
VALA_EXTERN XiEditView* xi_edit_view_container_get_edit_view (XiEditViewContainer* self);
VALA_EXTERN void xi_edit_view_container_show_find_bar (XiEditViewContainer* self);
static void xi_edit_view_container_finalize (GObject * obj);
static GType xi_edit_view_container_get_type_once (void);

static inline gpointer
xi_edit_view_container_get_instance_private (XiEditViewContainer* self)
{
	return G_STRUCT_MEMBER_P (self, XiEditViewContainer_private_offset);
}

static void
__lambda9_ (XiEditViewContainer* self)
{
	XiEditView* _tmp0_;
	_tmp0_ = self->priv->edit_view;
	gtk_widget_grab_focus ((GtkWidget*) _tmp0_);
}

static void
___lambda9__gtk_widget_hide (GtkWidget* _sender,
                             gpointer self)
{
	__lambda9_ ((XiEditViewContainer*) self);
}

XiEditViewContainer*
xi_edit_view_container_construct (GType object_type,
                                  XiCoreConnection* core_connection,
                                  const gchar* view_id,
                                  GFile* file)
{
	XiEditViewContainer * self = NULL;
	XiEditView* _tmp0_;
	XiFindBar* _tmp1_;
	XiFindBar* _tmp2_;
	GtkScrolledWindow* scrolled_window = NULL;
	GtkScrolledWindow* _tmp3_;
	XiEditView* _tmp4_;
	XiFindBar* _tmp5_;
	GtkStyleContext* _tmp6_;
	g_return_val_if_fail (core_connection != NULL, NULL);
	g_return_val_if_fail (view_id != NULL, NULL);
	self = (XiEditViewContainer*) g_object_new (object_type, "orientation", GTK_ORIENTATION_VERTICAL, NULL);
	_tmp0_ = xi_edit_view_new (core_connection, view_id, file);
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->edit_view);
	self->priv->edit_view = _tmp0_;
	_tmp1_ = xi_find_bar_new (core_connection, view_id);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->find_bar);
	self->priv->find_bar = _tmp1_;
	_tmp2_ = self->priv->find_bar;
	g_signal_connect_object ((GtkWidget*) _tmp2_, "hide", (GCallback) ___lambda9__gtk_widget_hide, self, 0);
	_tmp3_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp3_);
	scrolled_window = _tmp3_;
	_tmp4_ = self->priv->edit_view;
	gtk_container_add ((GtkContainer*) scrolled_window, (GtkWidget*) _tmp4_);
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) scrolled_window, TRUE, TRUE, (guint) 0);
	_tmp5_ = self->priv->find_bar;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp5_, FALSE, TRUE, (guint) 0);
	_tmp6_ = gtk_widget_get_style_context ((GtkWidget*) self);
	gtk_style_context_add_class (_tmp6_, GTK_STYLE_CLASS_BACKGROUND);
	gtk_widget_show_all ((GtkWidget*) scrolled_window);
	_g_object_unref0 (scrolled_window);
	return self;
}

XiEditViewContainer*
xi_edit_view_container_new (XiCoreConnection* core_connection,
                            const gchar* view_id,
                            GFile* file)
{
	return xi_edit_view_container_construct (XI_TYPE_EDIT_VIEW_CONTAINER, core_connection, view_id, file);
}

static void
xi_edit_view_container_real_grab_focus (GtkWidget* base)
{
	XiEditViewContainer * self;
	XiEditView* _tmp0_;
	self = (XiEditViewContainer*) base;
	_tmp0_ = self->priv->edit_view;
	gtk_widget_grab_focus ((GtkWidget*) _tmp0_);
}

XiEditView*
xi_edit_view_container_get_edit_view (XiEditViewContainer* self)
{
	XiEditView* _tmp0_;
	XiEditView* result;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->edit_view;
	result = _tmp0_;
	return result;
}

void
xi_edit_view_container_show_find_bar (XiEditViewContainer* self)
{
	XiFindBar* _tmp0_;
	XiFindBar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->find_bar;
	gtk_widget_show_all ((GtkWidget*) _tmp0_);
	_tmp1_ = self->priv->find_bar;
	gtk_widget_grab_focus ((GtkWidget*) _tmp1_);
}

static void
xi_edit_view_container_class_init (XiEditViewContainerClass * klass,
                                   gpointer klass_data)
{
	xi_edit_view_container_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &XiEditViewContainer_private_offset);
	((GtkWidgetClass *) klass)->grab_focus = (void (*) (GtkWidget*)) xi_edit_view_container_real_grab_focus;
	G_OBJECT_CLASS (klass)->finalize = xi_edit_view_container_finalize;
}

static void
xi_edit_view_container_instance_init (XiEditViewContainer * self,
                                      gpointer klass)
{
	self->priv = xi_edit_view_container_get_instance_private (self);
}

static void
xi_edit_view_container_finalize (GObject * obj)
{
	XiEditViewContainer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_EDIT_VIEW_CONTAINER, XiEditViewContainer);
	_g_object_unref0 (self->priv->edit_view);
	_g_object_unref0 (self->priv->find_bar);
	G_OBJECT_CLASS (xi_edit_view_container_parent_class)->finalize (obj);
}

static GType
xi_edit_view_container_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (XiEditViewContainerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_edit_view_container_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiEditViewContainer), 0, (GInstanceInitFunc) xi_edit_view_container_instance_init, NULL };
	GType xi_edit_view_container_type_id;
	xi_edit_view_container_type_id = g_type_register_static (gtk_box_get_type (), "XiEditViewContainer", &g_define_type_info, 0);
	XiEditViewContainer_private_offset = g_type_add_instance_private (xi_edit_view_container_type_id, sizeof (XiEditViewContainerPrivate));
	return xi_edit_view_container_type_id;
}

GType
xi_edit_view_container_get_type (void)
{
	static volatile gsize xi_edit_view_container_type_id__once = 0;
	if (g_once_init_enter (&xi_edit_view_container_type_id__once)) {
		GType xi_edit_view_container_type_id;
		xi_edit_view_container_type_id = xi_edit_view_container_get_type_once ();
		g_once_init_leave (&xi_edit_view_container_type_id__once, xi_edit_view_container_type_id);
	}
	return xi_edit_view_container_type_id__once;
}

