/* FindBar.c generated by valac 0.56.18, the Vala compiler
 * generated from FindBar.vala, do not modify */

/* Copyright 2017-2018 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gdk/gdk.h>
#include <json-glib/json-glib.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_FIND_BAR (xi_find_bar_get_type ())
#define XI_FIND_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_FIND_BAR, XiFindBar))
#define XI_FIND_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_FIND_BAR, XiFindBarClass))
#define XI_IS_FIND_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_FIND_BAR))
#define XI_IS_FIND_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_FIND_BAR))
#define XI_FIND_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_FIND_BAR, XiFindBarClass))

typedef struct _XiFindBar XiFindBar;
typedef struct _XiFindBarClass XiFindBarClass;
typedef struct _XiFindBarPrivate XiFindBarPrivate;

#define XI_TYPE_CORE_CONNECTION (xi_core_connection_get_type ())
#define XI_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnection))
#define XI_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))
#define XI_IS_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_CORE_CONNECTION))
#define XI_IS_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_CORE_CONNECTION))
#define XI_CORE_CONNECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))

typedef struct _XiCoreConnection XiCoreConnection;
typedef struct _XiCoreConnectionClass XiCoreConnectionClass;
enum  {
	XI_FIND_BAR_0_PROPERTY,
	XI_FIND_BAR_NUM_PROPERTIES
};
static GParamSpec* xi_find_bar_properties[XI_FIND_BAR_NUM_PROPERTIES];
#define _xi_core_connection_unref0(var) ((var == NULL) ? NULL : (var = (xi_core_connection_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))

struct _XiFindBar {
	GtkActionBar parent_instance;
	XiFindBarPrivate * priv;
};

struct _XiFindBarClass {
	GtkActionBarClass parent_class;
};

struct _XiFindBarPrivate {
	XiCoreConnection* core_connection;
	gchar* view_id;
	GtkEntry* find_entry;
	GtkToggleButton* case_sensitive;
	GtkToggleButton* regex;
	GtkToggleButton* whole_words;
	GtkEntry* replace_entry;
};

static gint XiFindBar_private_offset;
static gpointer xi_find_bar_parent_class = NULL;

VALA_EXTERN GType xi_find_bar_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiFindBar, g_object_unref)
VALA_EXTERN gpointer xi_core_connection_ref (gpointer instance);
VALA_EXTERN void xi_core_connection_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_core_connection (const gchar* name,
                                           const gchar* nick,
                                           const gchar* blurb,
                                           GType object_type,
                                           GParamFlags flags);
VALA_EXTERN void xi_value_set_core_connection (GValue* value,
                                   gpointer v_object);
VALA_EXTERN void xi_value_take_core_connection (GValue* value,
                                    gpointer v_object);
VALA_EXTERN gpointer xi_value_get_core_connection (const GValue* value);
VALA_EXTERN GType xi_core_connection_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiCoreConnection, xi_core_connection_unref)
static void xi_find_bar_find (XiFindBar* self);
VALA_EXTERN void xi_core_connection_send_find (XiCoreConnection* self,
                                   const gchar* view_id,
                                   const gchar* chars,
                                   gboolean case_sensitive,
                                   gboolean regex,
                                   gboolean whole_words);
static void xi_find_bar_find_next (XiFindBar* self);
VALA_EXTERN void xi_core_connection_send_find_next (XiCoreConnection* self,
                                        const gchar* view_id,
                                        gboolean wrap_around,
                                        gboolean allow_same,
                                        const gchar* modify_selection);
static void xi_find_bar_find_previous (XiFindBar* self);
VALA_EXTERN void xi_core_connection_send_find_previous (XiCoreConnection* self,
                                            const gchar* view_id,
                                            gboolean wrap_around,
                                            gboolean allow_same,
                                            const gchar* modify_selection);
static void xi_find_bar_find_all (XiFindBar* self);
VALA_EXTERN void xi_core_connection_send_edit (XiCoreConnection* self,
                                   const gchar* view_id,
                                   const gchar* method,
                                   JsonObject* edit_params);
static void xi_find_bar_replace (XiFindBar* self);
VALA_EXTERN void xi_core_connection_send_replace (XiCoreConnection* self,
                                      const gchar* view_id,
                                      const gchar* chars);
static void xi_find_bar_replace_next (XiFindBar* self);
static void xi_find_bar_replace_all (XiFindBar* self);
VALA_EXTERN XiFindBar* xi_find_bar_new (XiCoreConnection* core_connection,
                            const gchar* view_id);
VALA_EXTERN XiFindBar* xi_find_bar_construct (GType object_type,
                                  XiCoreConnection* core_connection,
                                  const gchar* view_id);
static void _xi_find_bar_find_gtk_editable_changed (GtkEditable* _sender,
                                             gpointer self);
static void _xi_find_bar_find_next_gtk_entry_activate (GtkEntry* _sender,
                                                gpointer self);
static void _xi_find_bar_find_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                  gpointer self);
static void _xi_find_bar_find_previous_gtk_button_clicked (GtkButton* _sender,
                                                    gpointer self);
static void _xi_find_bar_find_next_gtk_button_clicked (GtkButton* _sender,
                                                gpointer self);
static void _xi_find_bar_find_all_gtk_button_clicked (GtkButton* _sender,
                                               gpointer self);
static void __lambda8_ (XiFindBar* self);
static void ___lambda8__gtk_button_clicked (GtkButton* _sender,
                                     gpointer self);
static void _xi_find_bar_replace_gtk_editable_changed (GtkEditable* _sender,
                                                gpointer self);
static void _xi_find_bar_replace_next_gtk_entry_activate (GtkEntry* _sender,
                                                   gpointer self);
static void _xi_find_bar_replace_next_gtk_button_clicked (GtkButton* _sender,
                                                   gpointer self);
static void _xi_find_bar_replace_all_gtk_button_clicked (GtkButton* _sender,
                                                  gpointer self);
static gboolean xi_find_bar_real_key_press_event (GtkWidget* base,
                                           GdkEventKey* event);
static void xi_find_bar_real_show (GtkWidget* base);
VALA_EXTERN void xi_core_connection_send_highlight_find (XiCoreConnection* self,
                                             const gchar* view_id,
                                             gboolean visible);
static void xi_find_bar_real_hide (GtkWidget* base);
static void xi_find_bar_real_grab_focus (GtkWidget* base);
static void xi_find_bar_finalize (GObject * obj);
static GType xi_find_bar_get_type_once (void);

static inline gpointer
xi_find_bar_get_instance_private (XiFindBar* self)
{
	return G_STRUCT_MEMBER_P (self, XiFindBar_private_offset);
}

static void
xi_find_bar_find (XiFindBar* self)
{
	XiCoreConnection* _tmp0_;
	const gchar* _tmp1_;
	GtkEntry* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	GtkToggleButton* _tmp5_;
	gboolean _tmp6_;
	gboolean _tmp7_;
	GtkToggleButton* _tmp8_;
	gboolean _tmp9_;
	gboolean _tmp10_;
	GtkToggleButton* _tmp11_;
	gboolean _tmp12_;
	gboolean _tmp13_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->core_connection;
	_tmp1_ = self->priv->view_id;
	_tmp2_ = self->priv->find_entry;
	_tmp3_ = gtk_entry_get_text (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = self->priv->case_sensitive;
	_tmp6_ = gtk_toggle_button_get_active (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = self->priv->regex;
	_tmp9_ = gtk_toggle_button_get_active (_tmp8_);
	_tmp10_ = _tmp9_;
	_tmp11_ = self->priv->whole_words;
	_tmp12_ = gtk_toggle_button_get_active (_tmp11_);
	_tmp13_ = _tmp12_;
	xi_core_connection_send_find (_tmp0_, _tmp1_, _tmp4_, _tmp7_, _tmp10_, _tmp13_);
}

static void
xi_find_bar_find_next (XiFindBar* self)
{
	XiCoreConnection* _tmp0_;
	const gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->core_connection;
	_tmp1_ = self->priv->view_id;
	xi_core_connection_send_find_next (_tmp0_, _tmp1_, TRUE, FALSE, "set");
}

static void
xi_find_bar_find_previous (XiFindBar* self)
{
	XiCoreConnection* _tmp0_;
	const gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->core_connection;
	_tmp1_ = self->priv->view_id;
	xi_core_connection_send_find_previous (_tmp0_, _tmp1_, TRUE, FALSE, "set");
}

static void
xi_find_bar_find_all (XiFindBar* self)
{
	XiCoreConnection* _tmp0_;
	const gchar* _tmp1_;
	JsonObject* _tmp2_;
	JsonObject* _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->core_connection;
	_tmp1_ = self->priv->view_id;
	_tmp2_ = json_object_new ();
	_tmp3_ = _tmp2_;
	xi_core_connection_send_edit (_tmp0_, _tmp1_, "find_all", _tmp3_);
	_json_object_unref0 (_tmp3_);
}

static void
xi_find_bar_replace (XiFindBar* self)
{
	XiCoreConnection* _tmp0_;
	const gchar* _tmp1_;
	GtkEntry* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->core_connection;
	_tmp1_ = self->priv->view_id;
	_tmp2_ = self->priv->replace_entry;
	_tmp3_ = gtk_entry_get_text (_tmp2_);
	_tmp4_ = _tmp3_;
	xi_core_connection_send_replace (_tmp0_, _tmp1_, _tmp4_);
}

static void
xi_find_bar_replace_next (XiFindBar* self)
{
	XiCoreConnection* _tmp0_;
	const gchar* _tmp1_;
	JsonObject* _tmp2_;
	JsonObject* _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->core_connection;
	_tmp1_ = self->priv->view_id;
	_tmp2_ = json_object_new ();
	_tmp3_ = _tmp2_;
	xi_core_connection_send_edit (_tmp0_, _tmp1_, "replace_next", _tmp3_);
	_json_object_unref0 (_tmp3_);
}

static void
xi_find_bar_replace_all (XiFindBar* self)
{
	XiCoreConnection* _tmp0_;
	const gchar* _tmp1_;
	JsonObject* _tmp2_;
	JsonObject* _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->core_connection;
	_tmp1_ = self->priv->view_id;
	_tmp2_ = json_object_new ();
	_tmp3_ = _tmp2_;
	xi_core_connection_send_edit (_tmp0_, _tmp1_, "replace_all", _tmp3_);
	_json_object_unref0 (_tmp3_);
}

static gpointer
_xi_core_connection_ref0 (gpointer self)
{
	return self ? xi_core_connection_ref (self) : NULL;
}

static void
_xi_find_bar_find_gtk_editable_changed (GtkEditable* _sender,
                                        gpointer self)
{
	xi_find_bar_find ((XiFindBar*) self);
}

static void
_xi_find_bar_find_next_gtk_entry_activate (GtkEntry* _sender,
                                           gpointer self)
{
	xi_find_bar_find_next ((XiFindBar*) self);
}

static void
_xi_find_bar_find_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                             gpointer self)
{
	xi_find_bar_find ((XiFindBar*) self);
}

static void
_xi_find_bar_find_previous_gtk_button_clicked (GtkButton* _sender,
                                               gpointer self)
{
	xi_find_bar_find_previous ((XiFindBar*) self);
}

static void
_xi_find_bar_find_next_gtk_button_clicked (GtkButton* _sender,
                                           gpointer self)
{
	xi_find_bar_find_next ((XiFindBar*) self);
}

static void
_xi_find_bar_find_all_gtk_button_clicked (GtkButton* _sender,
                                          gpointer self)
{
	xi_find_bar_find_all ((XiFindBar*) self);
}

static void
__lambda8_ (XiFindBar* self)
{
	gtk_widget_hide ((GtkWidget*) self);
}

static void
___lambda8__gtk_button_clicked (GtkButton* _sender,
                                gpointer self)
{
	__lambda8_ ((XiFindBar*) self);
}

static void
_xi_find_bar_replace_gtk_editable_changed (GtkEditable* _sender,
                                           gpointer self)
{
	xi_find_bar_replace ((XiFindBar*) self);
}

static void
_xi_find_bar_replace_next_gtk_entry_activate (GtkEntry* _sender,
                                              gpointer self)
{
	xi_find_bar_replace_next ((XiFindBar*) self);
}

static void
_xi_find_bar_replace_next_gtk_button_clicked (GtkButton* _sender,
                                              gpointer self)
{
	xi_find_bar_replace_next ((XiFindBar*) self);
}

static void
_xi_find_bar_replace_all_gtk_button_clicked (GtkButton* _sender,
                                             gpointer self)
{
	xi_find_bar_replace_all ((XiFindBar*) self);
}

XiFindBar*
xi_find_bar_construct (GType object_type,
                       XiCoreConnection* core_connection,
                       const gchar* view_id)
{
	XiFindBar * self = NULL;
	XiCoreConnection* _tmp0_;
	gchar* _tmp1_;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp2_;
	GtkEntry* _tmp3_;
	GtkEntry* _tmp4_;
	GtkEntry* _tmp5_;
	GtkToggleButton* _tmp6_;
	GtkToggleButton* _tmp7_;
	GtkToggleButton* _tmp8_;
	GtkToggleButton* _tmp9_;
	GtkToggleButton* _tmp10_;
	GtkToggleButton* _tmp11_;
	GtkToggleButton* _tmp12_;
	GtkToggleButton* _tmp13_;
	GtkToggleButton* _tmp14_;
	GtkBox* entry_box = NULL;
	GtkBox* _tmp15_;
	GtkStyleContext* _tmp16_;
	GtkEntry* _tmp17_;
	GtkToggleButton* _tmp18_;
	GtkToggleButton* _tmp19_;
	GtkToggleButton* _tmp20_;
	GtkButton* find_prev_button = NULL;
	GtkButton* _tmp21_;
	GtkButton* find_next_button = NULL;
	GtkButton* _tmp22_;
	GtkBox* find_box = NULL;
	GtkBox* _tmp23_;
	GtkStyleContext* _tmp24_;
	GtkButton* find_all_button = NULL;
	GtkButton* _tmp25_;
	GtkButton* close_button = NULL;
	GtkButton* _tmp26_;
	GtkEntry* _tmp27_;
	GtkEntry* _tmp28_;
	GtkEntry* _tmp29_;
	GtkEntry* _tmp30_;
	GtkEntry* _tmp31_;
	GtkButton* replace_button = NULL;
	GtkButton* _tmp32_;
	GtkButton* replace_all_button = NULL;
	GtkButton* _tmp33_;
	g_return_val_if_fail (core_connection != NULL, NULL);
	g_return_val_if_fail (view_id != NULL, NULL);
	self = (XiFindBar*) g_object_new (object_type, NULL);
	_tmp0_ = _xi_core_connection_ref0 (core_connection);
	_xi_core_connection_unref0 (self->priv->core_connection);
	self->priv->core_connection = _tmp0_;
	_tmp1_ = g_strdup (view_id);
	_g_free0 (self->priv->view_id);
	self->priv->view_id = _tmp1_;
	_tmp2_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp2_);
	grid = _tmp2_;
	gtk_grid_set_column_spacing (grid, 6);
	gtk_grid_set_row_spacing (grid, 6);
	gtk_action_bar_pack_start ((GtkActionBar*) self, (GtkWidget*) grid);
	_tmp3_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->find_entry);
	self->priv->find_entry = _tmp3_;
	_tmp4_ = self->priv->find_entry;
	g_signal_connect_object ((GtkEditable*) _tmp4_, "changed", (GCallback) _xi_find_bar_find_gtk_editable_changed, self, 0);
	_tmp5_ = self->priv->find_entry;
	g_signal_connect_object (_tmp5_, "activate", (GCallback) _xi_find_bar_find_next_gtk_entry_activate, self, 0);
	_tmp6_ = (GtkToggleButton*) gtk_toggle_button_new_with_label ("Aa");
	g_object_ref_sink (_tmp6_);
	_g_object_unref0 (self->priv->case_sensitive);
	self->priv->case_sensitive = _tmp6_;
	_tmp7_ = self->priv->case_sensitive;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp7_, "Case Sensitive");
	_tmp8_ = self->priv->case_sensitive;
	g_signal_connect_object (_tmp8_, "toggled", (GCallback) _xi_find_bar_find_gtk_toggle_button_toggled, self, 0);
	_tmp9_ = (GtkToggleButton*) gtk_toggle_button_new_with_label (".*");
	g_object_ref_sink (_tmp9_);
	_g_object_unref0 (self->priv->regex);
	self->priv->regex = _tmp9_;
	_tmp10_ = self->priv->regex;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp10_, "Regular Expression");
	_tmp11_ = self->priv->regex;
	g_signal_connect_object (_tmp11_, "toggled", (GCallback) _xi_find_bar_find_gtk_toggle_button_toggled, self, 0);
	_tmp12_ = (GtkToggleButton*) gtk_toggle_button_new_with_label ("«»");
	g_object_ref_sink (_tmp12_);
	_g_object_unref0 (self->priv->whole_words);
	self->priv->whole_words = _tmp12_;
	_tmp13_ = self->priv->whole_words;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp13_, "Whole Words");
	_tmp14_ = self->priv->whole_words;
	g_signal_connect_object (_tmp14_, "toggled", (GCallback) _xi_find_bar_find_gtk_toggle_button_toggled, self, 0);
	_tmp15_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp15_);
	entry_box = _tmp15_;
	_tmp16_ = gtk_widget_get_style_context ((GtkWidget*) entry_box);
	gtk_style_context_add_class (_tmp16_, GTK_STYLE_CLASS_LINKED);
	_tmp17_ = self->priv->find_entry;
	gtk_box_pack_start (entry_box, (GtkWidget*) _tmp17_, TRUE, TRUE, (guint) 0);
	_tmp18_ = self->priv->case_sensitive;
	gtk_box_pack_start (entry_box, (GtkWidget*) _tmp18_, FALSE, TRUE, (guint) 0);
	_tmp19_ = self->priv->regex;
	gtk_box_pack_start (entry_box, (GtkWidget*) _tmp19_, FALSE, TRUE, (guint) 0);
	_tmp20_ = self->priv->whole_words;
	gtk_box_pack_start (entry_box, (GtkWidget*) _tmp20_, FALSE, TRUE, (guint) 0);
	gtk_widget_set_hexpand ((GtkWidget*) entry_box, TRUE);
	gtk_grid_attach (grid, (GtkWidget*) entry_box, 0, 0, 1, 1);
	_tmp21_ = (GtkButton*) gtk_button_new_from_icon_name ("go-up-symbolic", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp21_);
	find_prev_button = _tmp21_;
	gtk_widget_set_tooltip_text ((GtkWidget*) find_prev_button, "Find Previous");
	g_signal_connect_object (find_prev_button, "clicked", (GCallback) _xi_find_bar_find_previous_gtk_button_clicked, self, 0);
	_tmp22_ = (GtkButton*) gtk_button_new_from_icon_name ("go-down-symbolic", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp22_);
	find_next_button = _tmp22_;
	gtk_widget_set_tooltip_text ((GtkWidget*) find_next_button, "Find Next");
	g_signal_connect_object (find_next_button, "clicked", (GCallback) _xi_find_bar_find_next_gtk_button_clicked, self, 0);
	_tmp23_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp23_);
	find_box = _tmp23_;
	_tmp24_ = gtk_widget_get_style_context ((GtkWidget*) find_box);
	gtk_style_context_add_class (_tmp24_, GTK_STYLE_CLASS_LINKED);
	gtk_box_pack_start (find_box, (GtkWidget*) find_prev_button, TRUE, TRUE, (guint) 0);
	gtk_box_pack_start (find_box, (GtkWidget*) find_next_button, TRUE, TRUE, (guint) 0);
	gtk_grid_attach (grid, (GtkWidget*) find_box, 1, 0, 1, 1);
	_tmp25_ = (GtkButton*) gtk_button_new_with_label ("Find All");
	g_object_ref_sink (_tmp25_);
	find_all_button = _tmp25_;
	g_signal_connect_object (find_all_button, "clicked", (GCallback) _xi_find_bar_find_all_gtk_button_clicked, self, 0);
	gtk_grid_attach (grid, (GtkWidget*) find_all_button, 2, 0, 1, 1);
	_tmp26_ = (GtkButton*) gtk_button_new_from_icon_name ("window-close-symbolic", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp26_);
	close_button = _tmp26_;
	gtk_button_set_relief (close_button, GTK_RELIEF_NONE);
	g_signal_connect_object (close_button, "clicked", (GCallback) ___lambda8__gtk_button_clicked, self, 0);
	gtk_grid_attach (grid, (GtkWidget*) close_button, 3, 0, 1, 1);
	_tmp27_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp27_);
	_g_object_unref0 (self->priv->replace_entry);
	self->priv->replace_entry = _tmp27_;
	_tmp28_ = self->priv->replace_entry;
	g_signal_connect_object ((GtkEditable*) _tmp28_, "changed", (GCallback) _xi_find_bar_replace_gtk_editable_changed, self, 0);
	_tmp29_ = self->priv->replace_entry;
	g_signal_connect_object (_tmp29_, "activate", (GCallback) _xi_find_bar_replace_next_gtk_entry_activate, self, 0);
	_tmp30_ = self->priv->replace_entry;
	gtk_widget_set_hexpand ((GtkWidget*) _tmp30_, TRUE);
	_tmp31_ = self->priv->replace_entry;
	gtk_grid_attach (grid, (GtkWidget*) _tmp31_, 0, 1, 1, 1);
	_tmp32_ = (GtkButton*) gtk_button_new_with_label ("Replace");
	g_object_ref_sink (_tmp32_);
	replace_button = _tmp32_;
	g_signal_connect_object (replace_button, "clicked", (GCallback) _xi_find_bar_replace_next_gtk_button_clicked, self, 0);
	gtk_grid_attach (grid, (GtkWidget*) replace_button, 1, 1, 1, 1);
	_tmp33_ = (GtkButton*) gtk_button_new_with_label ("Replace All");
	g_object_ref_sink (_tmp33_);
	replace_all_button = _tmp33_;
	g_signal_connect_object (replace_all_button, "clicked", (GCallback) _xi_find_bar_replace_all_gtk_button_clicked, self, 0);
	gtk_grid_attach (grid, (GtkWidget*) replace_all_button, 2, 1, 1, 1);
	_g_object_unref0 (replace_all_button);
	_g_object_unref0 (replace_button);
	_g_object_unref0 (close_button);
	_g_object_unref0 (find_all_button);
	_g_object_unref0 (find_box);
	_g_object_unref0 (find_next_button);
	_g_object_unref0 (find_prev_button);
	_g_object_unref0 (entry_box);
	_g_object_unref0 (grid);
	return self;
}

XiFindBar*
xi_find_bar_new (XiCoreConnection* core_connection,
                 const gchar* view_id)
{
	return xi_find_bar_construct (XI_TYPE_FIND_BAR, core_connection, view_id);
}

static gboolean
xi_find_bar_real_key_press_event (GtkWidget* base,
                                  GdkEventKey* event)
{
	XiFindBar * self;
	gboolean result;
	self = (XiFindBar*) base;
	g_return_val_if_fail (event != NULL, FALSE);
	if (event->keyval == GDK_KEY_Escape) {
		gtk_widget_hide ((GtkWidget*) self);
		result = GDK_EVENT_STOP;
		return result;
	}
	result = GDK_EVENT_PROPAGATE;
	return result;
}

static void
xi_find_bar_real_show (GtkWidget* base)
{
	XiFindBar * self;
	XiCoreConnection* _tmp0_;
	const gchar* _tmp1_;
	self = (XiFindBar*) base;
	GTK_WIDGET_CLASS (xi_find_bar_parent_class)->show ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_action_bar_get_type (), GtkActionBar));
	_tmp0_ = self->priv->core_connection;
	_tmp1_ = self->priv->view_id;
	xi_core_connection_send_highlight_find (_tmp0_, _tmp1_, TRUE);
}

static void
xi_find_bar_real_hide (GtkWidget* base)
{
	XiFindBar * self;
	XiCoreConnection* _tmp0_;
	const gchar* _tmp1_;
	self = (XiFindBar*) base;
	GTK_WIDGET_CLASS (xi_find_bar_parent_class)->hide ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_action_bar_get_type (), GtkActionBar));
	_tmp0_ = self->priv->core_connection;
	_tmp1_ = self->priv->view_id;
	xi_core_connection_send_highlight_find (_tmp0_, _tmp1_, FALSE);
}

static void
xi_find_bar_real_grab_focus (GtkWidget* base)
{
	XiFindBar * self;
	GtkEntry* _tmp0_;
	self = (XiFindBar*) base;
	_tmp0_ = self->priv->find_entry;
	gtk_widget_grab_focus ((GtkWidget*) _tmp0_);
}

static void
xi_find_bar_class_init (XiFindBarClass * klass,
                        gpointer klass_data)
{
	xi_find_bar_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &XiFindBar_private_offset);
	((GtkWidgetClass *) klass)->key_press_event = (gboolean (*) (GtkWidget*, GdkEventKey*)) xi_find_bar_real_key_press_event;
	((GtkWidgetClass *) klass)->show = (void (*) (GtkWidget*)) xi_find_bar_real_show;
	((GtkWidgetClass *) klass)->hide = (void (*) (GtkWidget*)) xi_find_bar_real_hide;
	((GtkWidgetClass *) klass)->grab_focus = (void (*) (GtkWidget*)) xi_find_bar_real_grab_focus;
	G_OBJECT_CLASS (klass)->finalize = xi_find_bar_finalize;
}

static void
xi_find_bar_instance_init (XiFindBar * self,
                           gpointer klass)
{
	self->priv = xi_find_bar_get_instance_private (self);
}

static void
xi_find_bar_finalize (GObject * obj)
{
	XiFindBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_FIND_BAR, XiFindBar);
	_xi_core_connection_unref0 (self->priv->core_connection);
	_g_free0 (self->priv->view_id);
	_g_object_unref0 (self->priv->find_entry);
	_g_object_unref0 (self->priv->case_sensitive);
	_g_object_unref0 (self->priv->regex);
	_g_object_unref0 (self->priv->whole_words);
	_g_object_unref0 (self->priv->replace_entry);
	G_OBJECT_CLASS (xi_find_bar_parent_class)->finalize (obj);
}

static GType
xi_find_bar_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (XiFindBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_find_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiFindBar), 0, (GInstanceInitFunc) xi_find_bar_instance_init, NULL };
	GType xi_find_bar_type_id;
	xi_find_bar_type_id = g_type_register_static (gtk_action_bar_get_type (), "XiFindBar", &g_define_type_info, 0);
	XiFindBar_private_offset = g_type_add_instance_private (xi_find_bar_type_id, sizeof (XiFindBarPrivate));
	return xi_find_bar_type_id;
}

GType
xi_find_bar_get_type (void)
{
	static volatile gsize xi_find_bar_type_id__once = 0;
	if (g_once_init_enter (&xi_find_bar_type_id__once)) {
		GType xi_find_bar_type_id;
		xi_find_bar_type_id = xi_find_bar_get_type_once ();
		g_once_init_leave (&xi_find_bar_type_id__once, xi_find_bar_type_id);
	}
	return xi_find_bar_type_id__once;
}

