/* LineCache.c generated by valac 0.56.18, the Vala compiler
 * generated from LineCache.vala, do not modify */

/* Copyright 2017-2018 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <glib-object.h>
#include <glib.h>
#include <pango/pango.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_LINE_CACHE (xi_line_cache_get_type ())
#define XI_LINE_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_LINE_CACHE, XiLineCache))
#define XI_LINE_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_LINE_CACHE, XiLineCacheClass))
#define XI_IS_LINE_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_LINE_CACHE))
#define XI_IS_LINE_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_LINE_CACHE))
#define XI_LINE_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_LINE_CACHE, XiLineCacheClass))

typedef struct _XiLineCache XiLineCache;
typedef struct _XiLineCacheClass XiLineCacheClass;
typedef struct _XiLineCachePrivate XiLineCachePrivate;

#define XI_TYPE_LINE (xi_line_get_type ())
#define XI_LINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_LINE, XiLine))
#define XI_LINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_LINE, XiLineClass))
#define XI_IS_LINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_LINE))
#define XI_IS_LINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_LINE))
#define XI_LINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_LINE, XiLineClass))

typedef struct _XiLine XiLine;
typedef struct _XiLineClass XiLineClass;
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_PangoFontDescription_free0(var) ((var == NULL) ? NULL : (var = (_vala_PangoFontDescription_free (var), NULL)))
#define _xi_line_unref0(var) ((var == NULL) ? NULL : (var = (xi_line_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))
typedef struct _XiParamSpecLineCache XiParamSpecLineCache;

struct _XiLineCache {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XiLineCachePrivate * priv;
};

struct _XiLineCacheClass {
	GTypeClass parent_class;
	void (*finalize) (XiLineCache *self);
};

struct _XiLineCachePrivate {
	GPtrArray* lines;
	gint64 invalid_before;
	gint64 invalid_after;
	PangoContext* context;
	PangoFontDescription* font_description;
};

struct _XiParamSpecLineCache {
	GParamSpec parent_instance;
};

static gint XiLineCache_private_offset;
static gpointer xi_line_cache_parent_class = NULL;

VALA_EXTERN gpointer xi_line_cache_ref (gpointer instance);
VALA_EXTERN void xi_line_cache_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_line_cache (const gchar* name,
                                      const gchar* nick,
                                      const gchar* blurb,
                                      GType object_type,
                                      GParamFlags flags);
VALA_EXTERN void xi_value_set_line_cache (GValue* value,
                              gpointer v_object);
VALA_EXTERN void xi_value_take_line_cache (GValue* value,
                               gpointer v_object);
VALA_EXTERN gpointer xi_value_get_line_cache (const GValue* value);
VALA_EXTERN GType xi_line_cache_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiLineCache, xi_line_cache_unref)
VALA_EXTERN gpointer xi_line_ref (gpointer instance);
VALA_EXTERN void xi_line_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_line (const gchar* name,
                                const gchar* nick,
                                const gchar* blurb,
                                GType object_type,
                                GParamFlags flags);
VALA_EXTERN void xi_value_set_line (GValue* value,
                        gpointer v_object);
VALA_EXTERN void xi_value_take_line (GValue* value,
                         gpointer v_object);
VALA_EXTERN gpointer xi_value_get_line (const GValue* value);
VALA_EXTERN GType xi_line_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiLine, xi_line_unref)
static void _vala_PangoFontDescription_free (PangoFontDescription* self);
VALA_EXTERN XiLineCache* xi_line_cache_new (PangoContext* context,
                                PangoFontDescription* font_description);
VALA_EXTERN XiLineCache* xi_line_cache_construct (GType object_type,
                                      PangoContext* context,
                                      PangoFontDescription* font_description);
static void _xi_line_unref0_ (gpointer var);
static PangoFontDescription* _vala_PangoFontDescription_copy (PangoFontDescription* self);
static void xi_line_cache_add_invalid (GPtrArray* lines,
                                gint64* invalid_before,
                                gint64* invalid_after,
                                gint64 n);
static void xi_line_cache_add_line (GPtrArray* lines,
                             gint64* invalid_before,
                             gint64* invalid_after,
                             XiLine* line);
VALA_EXTERN void xi_line_cache_update (XiLineCache* self,
                           JsonObject* update);
VALA_EXTERN gboolean xi_line_is_wrapped (XiLine* self);
VALA_EXTERN void xi_line_set_number (XiLine* self,
                         gint64 number);
VALA_EXTERN XiLine* xi_line_new (PangoContext* context,
                     PangoFontDescription* font_description,
                     const gchar* text);
VALA_EXTERN XiLine* xi_line_construct (GType object_type,
                           PangoContext* context,
                           PangoFontDescription* font_description,
                           const gchar* text);
VALA_EXTERN void xi_line_set_cursors (XiLine* self,
                          JsonArray* json_cursors);
VALA_EXTERN void xi_line_set_styles (XiLine* self,
                         JsonArray* styles);
VALA_EXTERN gint64 xi_line_cache_get_height (XiLineCache* self);
VALA_EXTERN XiLine* xi_line_cache_get_line (XiLineCache* self,
                                gint64 index);
static void xi_line_cache_finalize (XiLineCache * obj);
static GType xi_line_cache_get_type_once (void);

static inline gpointer
xi_line_cache_get_instance_private (XiLineCache* self)
{
	return G_STRUCT_MEMBER_P (self, XiLineCache_private_offset);
}

static void
_vala_PangoFontDescription_free (PangoFontDescription* self)
{
	g_boxed_free (pango_font_description_get_type (), self);
}

static void
_xi_line_unref0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (xi_line_unref (var), NULL));
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static PangoFontDescription*
_vala_PangoFontDescription_copy (PangoFontDescription* self)
{
	return g_boxed_copy (pango_font_description_get_type (), self);
}

static gpointer
__vala_PangoFontDescription_copy0 (gpointer self)
{
	return self ? _vala_PangoFontDescription_copy (self) : NULL;
}

XiLineCache*
xi_line_cache_construct (GType object_type,
                         PangoContext* context,
                         PangoFontDescription* font_description)
{
	XiLineCache* self = NULL;
	GPtrArray* _tmp0_;
	PangoContext* _tmp1_;
	PangoFontDescription* _tmp2_;
	g_return_val_if_fail (context != NULL, NULL);
	g_return_val_if_fail (font_description != NULL, NULL);
	self = (XiLineCache*) g_type_create_instance (object_type);
	_tmp0_ = g_ptr_array_new_full ((guint) 0, _xi_line_unref0_);
	_g_ptr_array_unref0 (self->priv->lines);
	self->priv->lines = _tmp0_;
	_tmp1_ = _g_object_ref0 (context);
	_g_object_unref0 (self->priv->context);
	self->priv->context = _tmp1_;
	_tmp2_ = __vala_PangoFontDescription_copy0 (font_description);
	__vala_PangoFontDescription_free0 (self->priv->font_description);
	self->priv->font_description = _tmp2_;
	return self;
}

XiLineCache*
xi_line_cache_new (PangoContext* context,
                   PangoFontDescription* font_description)
{
	return xi_line_cache_construct (XI_TYPE_LINE_CACHE, context, font_description);
}

static gint
vala_g_ptr_array_get_length (GPtrArray* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = (gint) self->len;
	return result;
}

static void
xi_line_cache_add_invalid (GPtrArray* lines,
                           gint64* invalid_before,
                           gint64* invalid_after,
                           gint64 n)
{
	gint _tmp0_;
	gint _tmp1_;
	g_return_if_fail (lines != NULL);
	_tmp0_ = vala_g_ptr_array_get_length (lines);
	_tmp1_ = _tmp0_;
	if (_tmp1_ == 0) {
		*invalid_before = (*invalid_before) + n;
	} else {
		*invalid_after = (*invalid_after) + n;
	}
}

static gpointer
_xi_line_ref0 (gpointer self)
{
	return self ? xi_line_ref (self) : NULL;
}

static void
xi_line_cache_add_line (GPtrArray* lines,
                        gint64* invalid_before,
                        gint64* invalid_after,
                        XiLine* line)
{
	g_return_if_fail (lines != NULL);
	if (line != NULL) {
		XiLine* _tmp2_;
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp0_ = FALSE;
				_tmp0_ = TRUE;
				while (TRUE) {
					if (!_tmp0_) {
						gint _tmp1_;
						_tmp1_ = i;
						i = _tmp1_ + 1;
					}
					_tmp0_ = FALSE;
					if (!(((gint64) i) < (*invalid_after))) {
						break;
					}
					g_ptr_array_add (lines, NULL);
				}
			}
		}
		*invalid_after = (gint64) 0;
		_tmp2_ = _xi_line_ref0 (line);
		g_ptr_array_add (lines, _tmp2_);
	} else {
		xi_line_cache_add_invalid (lines, invalid_before, invalid_after, (gint64) 1);
	}
}

static gpointer
_json_array_ref0 (gpointer self)
{
	return self ? json_array_ref (self) : NULL;
}

static gpointer
_json_object_ref0 (gpointer self)
{
	return self ? json_object_ref (self) : NULL;
}

static gpointer
_g_ptr_array_ref0 (gpointer self)
{
	return self ? g_ptr_array_ref (self) : NULL;
}

void
xi_line_cache_update (XiLineCache* self,
                      JsonObject* update)
{
	JsonArray* ops = NULL;
	JsonArray* _tmp0_;
	JsonArray* _tmp1_;
	GPtrArray* new_lines = NULL;
	GPtrArray* _tmp2_;
	gint64 new_invalid_before = 0LL;
	gint64 new_invalid_after = 0LL;
	gint64 index = 0LL;
	GPtrArray* _tmp101_;
	GPtrArray* _tmp102_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (update != NULL);
	_tmp0_ = json_object_get_array_member (update, "ops");
	_tmp1_ = _json_array_ref0 (_tmp0_);
	ops = _tmp1_;
	_tmp2_ = g_ptr_array_new_full ((guint) 0, _xi_line_unref0_);
	new_lines = _tmp2_;
	new_invalid_before = (gint64) 0;
	new_invalid_after = (gint64) 0;
	index = (gint64) 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp3_ = FALSE;
			_tmp3_ = TRUE;
			while (TRUE) {
				JsonArray* _tmp5_;
				JsonObject* op = NULL;
				JsonArray* _tmp6_;
				JsonObject* _tmp7_;
				JsonObject* _tmp8_;
				JsonObject* _tmp9_;
				const gchar* _tmp10_;
				const gchar* _tmp11_;
				GQuark _tmp13_ = 0U;
				static GQuark _tmp12_label0 = 0;
				static GQuark _tmp12_label1 = 0;
				static GQuark _tmp12_label2 = 0;
				static GQuark _tmp12_label3 = 0;
				static GQuark _tmp12_label4 = 0;
				if (!_tmp3_) {
					gint _tmp4_;
					_tmp4_ = i;
					i = _tmp4_ + 1;
				}
				_tmp3_ = FALSE;
				_tmp5_ = ops;
				if (!(((guint) i) < json_array_get_length (_tmp5_))) {
					break;
				}
				_tmp6_ = ops;
				_tmp7_ = json_array_get_object_element (_tmp6_, (guint) i);
				_tmp8_ = _json_object_ref0 (_tmp7_);
				op = _tmp8_;
				_tmp9_ = op;
				_tmp10_ = json_object_get_string_member (_tmp9_, "op");
				_tmp11_ = _tmp10_;
				_tmp13_ = (NULL == _tmp11_) ? 0 : g_quark_from_string (_tmp11_);
				if (_tmp13_ == ((0 != _tmp12_label0) ? _tmp12_label0 : (_tmp12_label0 = g_quark_from_static_string ("copy")))) {
					switch (0) {
						default:
						{
							gint64 n = 0LL;
							JsonObject* _tmp14_;
							gint64 number = 0LL;
							JsonObject* _tmp16_;
							gboolean _tmp17_ = FALSE;
							GPtrArray* _tmp44_;
							_tmp14_ = op;
							n = json_object_get_int_member (_tmp14_, "n");
							if (index < self->priv->invalid_before) {
								gint64 invalid = 0LL;
								GPtrArray* _tmp15_;
								invalid = MIN (n, self->priv->invalid_before - index);
								_tmp15_ = new_lines;
								xi_line_cache_add_invalid (_tmp15_, &new_invalid_before, &new_invalid_after, invalid);
								n -= invalid;
								index += invalid;
							}
							_tmp16_ = op;
							number = json_object_get_int_member (_tmp16_, "ln");
							if (n > ((gint64) 0)) {
								GPtrArray* _tmp18_;
								gint _tmp19_;
								gint _tmp20_;
								_tmp18_ = self->priv->lines;
								_tmp19_ = vala_g_ptr_array_get_length (_tmp18_);
								_tmp20_ = _tmp19_;
								_tmp17_ = index < (self->priv->invalid_before + _tmp20_);
							} else {
								_tmp17_ = FALSE;
							}
							if (_tmp17_) {
								XiLine* line = NULL;
								GPtrArray* _tmp21_;
								gconstpointer _tmp22_;
								XiLine* _tmp23_;
								gboolean _tmp24_ = FALSE;
								XiLine* _tmp25_;
								_tmp21_ = self->priv->lines;
								_tmp22_ = g_ptr_array_index (_tmp21_, (guint) (index - self->priv->invalid_before));
								_tmp23_ = _xi_line_ref0 ((XiLine*) _tmp22_);
								line = _tmp23_;
								_tmp25_ = line;
								if (_tmp25_ == NULL) {
									_tmp24_ = TRUE;
								} else {
									XiLine* _tmp26_;
									_tmp26_ = line;
									_tmp24_ = xi_line_is_wrapped (_tmp26_);
								}
								if (_tmp24_) {
									gint64 _tmp27_;
									_tmp27_ = number;
									number = _tmp27_ + 1;
								}
								_xi_line_unref0 (line);
							}
							while (TRUE) {
								gboolean _tmp28_ = FALSE;
								XiLine* line = NULL;
								GPtrArray* _tmp32_;
								gconstpointer _tmp33_;
								XiLine* _tmp34_;
								gboolean _tmp35_ = FALSE;
								XiLine* _tmp36_;
								GPtrArray* _tmp40_;
								XiLine* _tmp41_;
								gint64 _tmp42_;
								gint64 _tmp43_;
								if (n > ((gint64) 0)) {
									GPtrArray* _tmp29_;
									gint _tmp30_;
									gint _tmp31_;
									_tmp29_ = self->priv->lines;
									_tmp30_ = vala_g_ptr_array_get_length (_tmp29_);
									_tmp31_ = _tmp30_;
									_tmp28_ = index < (self->priv->invalid_before + _tmp31_);
								} else {
									_tmp28_ = FALSE;
								}
								if (!_tmp28_) {
									break;
								}
								_tmp32_ = self->priv->lines;
								_tmp33_ = g_ptr_array_index (_tmp32_, (guint) (index - self->priv->invalid_before));
								_tmp34_ = _xi_line_ref0 ((XiLine*) _tmp33_);
								line = _tmp34_;
								_tmp36_ = line;
								if (_tmp36_ != NULL) {
									XiLine* _tmp37_;
									_tmp37_ = line;
									_tmp35_ = !xi_line_is_wrapped (_tmp37_);
								} else {
									_tmp35_ = FALSE;
								}
								if (_tmp35_) {
									XiLine* _tmp38_;
									gint64 _tmp39_;
									_tmp38_ = line;
									xi_line_set_number (_tmp38_, number);
									_tmp39_ = number;
									number = _tmp39_ + 1;
								}
								_tmp40_ = new_lines;
								_tmp41_ = line;
								xi_line_cache_add_line (_tmp40_, &new_invalid_before, &new_invalid_after, _tmp41_);
								_tmp42_ = n;
								n = _tmp42_ - 1;
								_tmp43_ = index;
								index = _tmp43_ + 1;
								_xi_line_unref0 (line);
							}
							_tmp44_ = new_lines;
							xi_line_cache_add_invalid (_tmp44_, &new_invalid_before, &new_invalid_after, n);
							index += n;
							break;
						}
					}
				} else if (_tmp13_ == ((0 != _tmp12_label1) ? _tmp12_label1 : (_tmp12_label1 = g_quark_from_static_string ("skip")))) {
					switch (0) {
						default:
						{
							gint64 n = 0LL;
							JsonObject* _tmp45_;
							_tmp45_ = op;
							n = json_object_get_int_member (_tmp45_, "n");
							index += n;
							break;
						}
					}
				} else if (_tmp13_ == ((0 != _tmp12_label2) ? _tmp12_label2 : (_tmp12_label2 = g_quark_from_static_string ("invalidate")))) {
					switch (0) {
						default:
						{
							gint64 n = 0LL;
							JsonObject* _tmp46_;
							GPtrArray* _tmp47_;
							_tmp46_ = op;
							n = json_object_get_int_member (_tmp46_, "n");
							_tmp47_ = new_lines;
							xi_line_cache_add_invalid (_tmp47_, &new_invalid_before, &new_invalid_after, n);
							break;
						}
					}
				} else if (_tmp13_ == ((0 != _tmp12_label3) ? _tmp12_label3 : (_tmp12_label3 = g_quark_from_static_string ("ins")))) {
					switch (0) {
						default:
						{
							JsonArray* json_lines = NULL;
							JsonObject* _tmp48_;
							JsonArray* _tmp49_;
							JsonArray* _tmp50_;
							_tmp48_ = op;
							_tmp49_ = json_object_get_array_member (_tmp48_, "lines");
							_tmp50_ = _json_array_ref0 (_tmp49_);
							json_lines = _tmp50_;
							{
								gint j = 0;
								j = 0;
								{
									gboolean _tmp51_ = FALSE;
									_tmp51_ = TRUE;
									while (TRUE) {
										JsonArray* _tmp53_;
										JsonObject* json_line = NULL;
										JsonArray* _tmp54_;
										JsonObject* _tmp55_;
										JsonObject* _tmp56_;
										gchar* text = NULL;
										JsonObject* _tmp57_;
										const gchar* _tmp58_;
										gchar* _tmp59_;
										XiLine* line = NULL;
										PangoContext* _tmp60_;
										PangoFontDescription* _tmp61_;
										const gchar* _tmp62_;
										XiLine* _tmp63_;
										JsonObject* _tmp64_;
										JsonObject* _tmp68_;
										JsonObject* _tmp72_;
										GPtrArray* _tmp76_;
										XiLine* _tmp77_;
										if (!_tmp51_) {
											gint _tmp52_;
											_tmp52_ = j;
											j = _tmp52_ + 1;
										}
										_tmp51_ = FALSE;
										_tmp53_ = json_lines;
										if (!(((guint) j) < json_array_get_length (_tmp53_))) {
											break;
										}
										_tmp54_ = json_lines;
										_tmp55_ = json_array_get_object_element (_tmp54_, (guint) j);
										_tmp56_ = _json_object_ref0 (_tmp55_);
										json_line = _tmp56_;
										_tmp57_ = json_line;
										_tmp58_ = json_object_get_string_member (_tmp57_, "text");
										_tmp59_ = g_strdup (_tmp58_);
										text = _tmp59_;
										_tmp60_ = self->priv->context;
										_tmp61_ = self->priv->font_description;
										_tmp62_ = text;
										_tmp63_ = xi_line_new (_tmp60_, _tmp61_, _tmp62_);
										line = _tmp63_;
										_tmp64_ = json_line;
										if (json_object_has_member (_tmp64_, "ln")) {
											XiLine* _tmp65_;
											JsonObject* _tmp66_;
											_tmp65_ = line;
											_tmp66_ = json_line;
											xi_line_set_number (_tmp65_, json_object_get_int_member (_tmp66_, "ln"));
										} else {
											XiLine* _tmp67_;
											_tmp67_ = line;
											xi_line_set_number (_tmp67_, (gint64) 0);
										}
										_tmp68_ = json_line;
										if (json_object_has_member (_tmp68_, "cursor")) {
											XiLine* _tmp69_;
											JsonObject* _tmp70_;
											JsonArray* _tmp71_;
											_tmp69_ = line;
											_tmp70_ = json_line;
											_tmp71_ = json_object_get_array_member (_tmp70_, "cursor");
											xi_line_set_cursors (_tmp69_, _tmp71_);
										}
										_tmp72_ = json_line;
										if (json_object_has_member (_tmp72_, "styles")) {
											XiLine* _tmp73_;
											JsonObject* _tmp74_;
											JsonArray* _tmp75_;
											_tmp73_ = line;
											_tmp74_ = json_line;
											_tmp75_ = json_object_get_array_member (_tmp74_, "styles");
											xi_line_set_styles (_tmp73_, _tmp75_);
										}
										_tmp76_ = new_lines;
										_tmp77_ = line;
										xi_line_cache_add_line (_tmp76_, &new_invalid_before, &new_invalid_after, _tmp77_);
										_xi_line_unref0 (line);
										_g_free0 (text);
										_json_object_unref0 (json_line);
									}
								}
							}
							_json_array_unref0 (json_lines);
							break;
						}
					}
				} else if (_tmp13_ == ((0 != _tmp12_label4) ? _tmp12_label4 : (_tmp12_label4 = g_quark_from_static_string ("update")))) {
					switch (0) {
						default:
						{
							JsonArray* json_lines = NULL;
							JsonObject* _tmp78_;
							JsonArray* _tmp79_;
							JsonArray* _tmp80_;
							_tmp78_ = op;
							_tmp79_ = json_object_get_array_member (_tmp78_, "lines");
							_tmp80_ = _json_array_ref0 (_tmp79_);
							json_lines = _tmp80_;
							{
								gint j = 0;
								j = 0;
								{
									gboolean _tmp81_ = FALSE;
									_tmp81_ = TRUE;
									while (TRUE) {
										JsonArray* _tmp83_;
										JsonObject* json_line = NULL;
										JsonArray* _tmp84_;
										JsonObject* _tmp85_;
										JsonObject* _tmp86_;
										XiLine* line = NULL;
										GPtrArray* _tmp87_;
										gconstpointer _tmp88_;
										XiLine* _tmp89_;
										JsonObject* _tmp90_;
										JsonObject* _tmp94_;
										GPtrArray* _tmp98_;
										XiLine* _tmp99_;
										gint64 _tmp100_;
										if (!_tmp81_) {
											gint _tmp82_;
											_tmp82_ = j;
											j = _tmp82_ + 1;
										}
										_tmp81_ = FALSE;
										_tmp83_ = json_lines;
										if (!(((guint) j) < json_array_get_length (_tmp83_))) {
											break;
										}
										_tmp84_ = json_lines;
										_tmp85_ = json_array_get_object_element (_tmp84_, (guint) j);
										_tmp86_ = _json_object_ref0 (_tmp85_);
										json_line = _tmp86_;
										_tmp87_ = self->priv->lines;
										_tmp88_ = g_ptr_array_index (_tmp87_, (guint) (index - self->priv->invalid_before));
										_tmp89_ = _xi_line_ref0 ((XiLine*) _tmp88_);
										line = _tmp89_;
										_tmp90_ = json_line;
										if (json_object_has_member (_tmp90_, "cursor")) {
											XiLine* _tmp91_;
											JsonObject* _tmp92_;
											JsonArray* _tmp93_;
											_tmp91_ = line;
											_tmp92_ = json_line;
											_tmp93_ = json_object_get_array_member (_tmp92_, "cursor");
											xi_line_set_cursors (_tmp91_, _tmp93_);
										}
										_tmp94_ = json_line;
										if (json_object_has_member (_tmp94_, "styles")) {
											XiLine* _tmp95_;
											JsonObject* _tmp96_;
											JsonArray* _tmp97_;
											_tmp95_ = line;
											_tmp96_ = json_line;
											_tmp97_ = json_object_get_array_member (_tmp96_, "styles");
											xi_line_set_styles (_tmp95_, _tmp97_);
										}
										_tmp98_ = new_lines;
										_tmp99_ = line;
										xi_line_cache_add_line (_tmp98_, &new_invalid_before, &new_invalid_after, _tmp99_);
										_tmp100_ = index;
										index = _tmp100_ + 1;
										_xi_line_unref0 (line);
										_json_object_unref0 (json_line);
									}
								}
							}
							_json_array_unref0 (json_lines);
							break;
						}
					}
				}
				_json_object_unref0 (op);
			}
		}
	}
	_tmp101_ = new_lines;
	_tmp102_ = _g_ptr_array_ref0 (_tmp101_);
	_g_ptr_array_unref0 (self->priv->lines);
	self->priv->lines = _tmp102_;
	self->priv->invalid_before = new_invalid_before;
	self->priv->invalid_after = new_invalid_after;
	_g_ptr_array_unref0 (new_lines);
	_json_array_unref0 (ops);
}

gint64
xi_line_cache_get_height (XiLineCache* self)
{
	GPtrArray* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gint64 result;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->lines;
	_tmp1_ = vala_g_ptr_array_get_length (_tmp0_);
	_tmp2_ = _tmp1_;
	result = (self->priv->invalid_before + _tmp2_) + self->priv->invalid_after;
	return result;
}

XiLine*
xi_line_cache_get_line (XiLineCache* self,
                        gint64 index)
{
	gboolean _tmp0_ = FALSE;
	GPtrArray* _tmp4_;
	gconstpointer _tmp5_;
	XiLine* _tmp6_;
	XiLine* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (index < self->priv->invalid_before) {
		_tmp0_ = TRUE;
	} else {
		GPtrArray* _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		_tmp1_ = self->priv->lines;
		_tmp2_ = vala_g_ptr_array_get_length (_tmp1_);
		_tmp3_ = _tmp2_;
		_tmp0_ = index >= (self->priv->invalid_before + _tmp3_);
	}
	if (_tmp0_) {
		result = NULL;
		return result;
	}
	_tmp4_ = self->priv->lines;
	_tmp5_ = g_ptr_array_index (_tmp4_, (guint) (index - self->priv->invalid_before));
	_tmp6_ = _xi_line_ref0 ((XiLine*) _tmp5_);
	result = _tmp6_;
	return result;
}

static void
xi_value_line_cache_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
xi_value_line_cache_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		xi_line_cache_unref (value->data[0].v_pointer);
	}
}

static void
xi_value_line_cache_copy_value (const GValue* src_value,
                                GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = xi_line_cache_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
xi_value_line_cache_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
xi_value_line_cache_collect_value (GValue* value,
                                   guint n_collect_values,
                                   GTypeCValue* collect_values,
                                   guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		XiLineCache * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = xi_line_cache_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
xi_value_line_cache_lcopy_value (const GValue* value,
                                 guint n_collect_values,
                                 GTypeCValue* collect_values,
                                 guint collect_flags)
{
	XiLineCache ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = xi_line_cache_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
xi_param_spec_line_cache (const gchar* name,
                          const gchar* nick,
                          const gchar* blurb,
                          GType object_type,
                          GParamFlags flags)
{
	XiParamSpecLineCache* spec;
	g_return_val_if_fail (g_type_is_a (object_type, XI_TYPE_LINE_CACHE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
xi_value_get_line_cache (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_LINE_CACHE), NULL);
	return value->data[0].v_pointer;
}

void
xi_value_set_line_cache (GValue* value,
                         gpointer v_object)
{
	XiLineCache * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_LINE_CACHE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_LINE_CACHE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		xi_line_cache_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_line_cache_unref (old);
	}
}

void
xi_value_take_line_cache (GValue* value,
                          gpointer v_object)
{
	XiLineCache * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_LINE_CACHE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_LINE_CACHE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_line_cache_unref (old);
	}
}

static void
xi_line_cache_class_init (XiLineCacheClass * klass,
                          gpointer klass_data)
{
	xi_line_cache_parent_class = g_type_class_peek_parent (klass);
	((XiLineCacheClass *) klass)->finalize = xi_line_cache_finalize;
	g_type_class_adjust_private_offset (klass, &XiLineCache_private_offset);
}

static void
xi_line_cache_instance_init (XiLineCache * self,
                             gpointer klass)
{
	self->priv = xi_line_cache_get_instance_private (self);
	self->ref_count = 1;
}

static void
xi_line_cache_finalize (XiLineCache * obj)
{
	XiLineCache * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_LINE_CACHE, XiLineCache);
	g_signal_handlers_destroy (self);
	_g_ptr_array_unref0 (self->priv->lines);
	_g_object_unref0 (self->priv->context);
	__vala_PangoFontDescription_free0 (self->priv->font_description);
}

static GType
xi_line_cache_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { xi_value_line_cache_init, xi_value_line_cache_free_value, xi_value_line_cache_copy_value, xi_value_line_cache_peek_pointer, "p", xi_value_line_cache_collect_value, "p", xi_value_line_cache_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (XiLineCacheClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_line_cache_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiLineCache), 0, (GInstanceInitFunc) xi_line_cache_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType xi_line_cache_type_id;
	xi_line_cache_type_id = g_type_register_fundamental (g_type_fundamental_next (), "XiLineCache", &g_define_type_info, &g_define_type_fundamental_info, 0);
	XiLineCache_private_offset = g_type_add_instance_private (xi_line_cache_type_id, sizeof (XiLineCachePrivate));
	return xi_line_cache_type_id;
}

GType
xi_line_cache_get_type (void)
{
	static volatile gsize xi_line_cache_type_id__once = 0;
	if (g_once_init_enter (&xi_line_cache_type_id__once)) {
		GType xi_line_cache_type_id;
		xi_line_cache_type_id = xi_line_cache_get_type_once ();
		g_once_init_leave (&xi_line_cache_type_id__once, xi_line_cache_type_id);
	}
	return xi_line_cache_type_id__once;
}

gpointer
xi_line_cache_ref (gpointer instance)
{
	XiLineCache * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
xi_line_cache_unref (gpointer instance)
{
	XiLineCache * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		XI_LINE_CACHE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

