/* Line.c generated by valac 0.56.18, the Vala compiler
 * generated from Line.vala, do not modify */

/* Copyright 2017-2018 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <glib-object.h>
#include <pango/pango.h>
#include <glib.h>
#include <float.h>
#include <math.h>
#include <gdk/gdk.h>
#include <stdlib.h>
#include <string.h>
#include <json-glib/json-glib.h>
#include <cairo-gobject.h>
#include <pango/pangocairo.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_LINE (xi_line_get_type ())
#define XI_LINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_LINE, XiLine))
#define XI_LINE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_LINE, XiLineClass))
#define XI_IS_LINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_LINE))
#define XI_IS_LINE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_LINE))
#define XI_LINE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_LINE, XiLineClass))

typedef struct _XiLine XiLine;
typedef struct _XiLineClass XiLineClass;
typedef struct _XiLinePrivate XiLinePrivate;

#define XI_LINE_TYPE_BACKGROUND (xi_line_background_get_type ())
typedef struct _XiLineBackground XiLineBackground;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _pango_attribute_destroy0(var) ((var == NULL) ? NULL : (var = (pango_attribute_destroy (var), NULL)))

#define XI_TYPE_STYLE (xi_style_get_type ())
typedef struct _XiStyle XiStyle;

#define XI_TYPE_STYLE_MAP (xi_style_map_get_type ())
#define XI_STYLE_MAP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_STYLE_MAP, XiStyleMap))
#define XI_STYLE_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_STYLE_MAP, XiStyleMapClass))
#define XI_IS_STYLE_MAP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_STYLE_MAP))
#define XI_IS_STYLE_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_STYLE_MAP))
#define XI_STYLE_MAP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_STYLE_MAP, XiStyleMapClass))

typedef struct _XiStyleMap XiStyleMap;
typedef struct _XiStyleMapClass XiStyleMapClass;
#define _xi_style_map_unref0(var) ((var == NULL) ? NULL : (var = (xi_style_map_unref (var), NULL)))
#define _pango_attr_list_unref0(var) ((var == NULL) ? NULL : (var = (pango_attr_list_unref (var), NULL)))

#define XI_TYPE_THEME (xi_theme_get_type ())
#define XI_THEME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_THEME, XiTheme))
#define XI_THEME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_THEME, XiThemeClass))
#define XI_IS_THEME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_THEME))
#define XI_IS_THEME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_THEME))
#define XI_THEME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_THEME, XiThemeClass))

typedef struct _XiTheme XiTheme;
typedef struct _XiThemeClass XiThemeClass;
typedef struct _XiThemePrivate XiThemePrivate;
#define _xi_theme_unref0(var) ((var == NULL) ? NULL : (var = (xi_theme_unref (var), NULL)))
typedef struct _XiParamSpecLine XiParamSpecLine;

struct _XiLine {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XiLinePrivate * priv;
};

struct _XiLineClass {
	GTypeClass parent_class;
	void (*finalize) (XiLine *self);
};

struct _XiLineBackground {
	gdouble x;
	gdouble width;
	GdkRGBA color;
};

struct _XiLinePrivate {
	PangoLayout* layout;
	PangoLayout* number;
	gdouble* cursors;
	gint cursors_length1;
	gint _cursors_size_;
	GPtrArray* backgrounds;
};

struct _XiStyle {
	GdkRGBA* foreground;
	GdkRGBA* background;
	PangoWeight* weight;
	gboolean underline;
	gboolean italic;
};

struct _XiTheme {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XiThemePrivate * priv;
	GdkRGBA foreground;
	GdkRGBA background;
	GdkRGBA caret;
	GdkRGBA line_highlight;
	GdkRGBA selection;
	GdkRGBA gutter;
	GdkRGBA gutter_foreground;
	GdkRGBA find_highlight;
	GdkRGBA find_highlight_foreground;
};

struct _XiThemeClass {
	GTypeClass parent_class;
	void (*finalize) (XiTheme *self);
};

struct _XiParamSpecLine {
	GParamSpec parent_instance;
};

static gint XiLine_private_offset;
static gpointer xi_line_parent_class = NULL;

VALA_EXTERN gpointer xi_line_ref (gpointer instance);
VALA_EXTERN void xi_line_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_line (const gchar* name,
                                const gchar* nick,
                                const gchar* blurb,
                                GType object_type,
                                GParamFlags flags);
VALA_EXTERN void xi_value_set_line (GValue* value,
                        gpointer v_object);
VALA_EXTERN void xi_value_take_line (GValue* value,
                         gpointer v_object);
VALA_EXTERN gpointer xi_value_get_line (const GValue* value);
VALA_EXTERN GType xi_line_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiLine, xi_line_unref)
static GType xi_line_background_get_type (void) G_GNUC_CONST  G_GNUC_UNUSED ;
static XiLineBackground* xi_line_background_dup (const XiLineBackground* self);
static void xi_line_background_free (XiLineBackground* self);
VALA_EXTERN XiLine* xi_line_new (PangoContext* context,
                     PangoFontDescription* font_description,
                     const gchar* text);
VALA_EXTERN XiLine* xi_line_construct (GType object_type,
                           PangoContext* context,
                           PangoFontDescription* font_description,
                           const gchar* text);
VALA_EXTERN void xi_line_set_number (XiLine* self,
                         gint64 number);
VALA_EXTERN gboolean xi_line_is_wrapped (XiLine* self);
VALA_EXTERN void xi_line_set_cursors (XiLine* self,
                          JsonArray* json_cursors);
VALA_EXTERN gdouble xi_line_index_to_x (XiLine* self,
                            gint index);
static void xi_line_set_foreground (PangoAttrList* attributes,
                             guint start_index,
                             guint end_index,
                             GdkRGBA* color);
static void xi_line_set_weight (PangoAttrList* attributes,
                         guint start_index,
                         guint end_index,
                         PangoWeight weight);
static void xi_line_set_underline (PangoAttrList* attributes,
                            guint start_index,
                            guint end_index);
static void xi_line_set_italic (PangoAttrList* attributes,
                         guint start_index,
                         guint end_index);
VALA_EXTERN void xi_line_set_styles (XiLine* self,
                         JsonArray* styles);
static void _xi_line_background_free0_ (gpointer var);
VALA_EXTERN GType xi_style_get_type (void) G_GNUC_CONST ;
VALA_EXTERN XiStyle* xi_style_dup (const XiStyle* self);
VALA_EXTERN void xi_style_free (XiStyle* self);
VALA_EXTERN void xi_style_copy (const XiStyle* self,
                    XiStyle* dest);
VALA_EXTERN void xi_style_destroy (XiStyle* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (XiStyle, xi_style_destroy)
VALA_EXTERN gpointer xi_style_map_ref (gpointer instance);
VALA_EXTERN void xi_style_map_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_style_map (const gchar* name,
                                     const gchar* nick,
                                     const gchar* blurb,
                                     GType object_type,
                                     GParamFlags flags);
VALA_EXTERN void xi_value_set_style_map (GValue* value,
                             gpointer v_object);
VALA_EXTERN void xi_value_take_style_map (GValue* value,
                              gpointer v_object);
VALA_EXTERN gpointer xi_value_get_style_map (const GValue* value);
VALA_EXTERN GType xi_style_map_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiStyleMap, xi_style_map_unref)
VALA_EXTERN XiStyleMap* xi_style_map_get_instance (void);
VALA_EXTERN void xi_style_map_get_style (XiStyleMap* self,
                             gint id,
                             XiStyle* result);
VALA_EXTERN void xi_line_draw_background (XiLine* self,
                              cairo_t* cr,
                              gdouble x,
                              gdouble y,
                              gdouble width,
                              gdouble line_height);
VALA_EXTERN gpointer xi_theme_ref (gpointer instance);
VALA_EXTERN void xi_theme_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_theme (const gchar* name,
                                 const gchar* nick,
                                 const gchar* blurb,
                                 GType object_type,
                                 GParamFlags flags);
VALA_EXTERN void xi_value_set_theme (GValue* value,
                         gpointer v_object);
VALA_EXTERN void xi_value_take_theme (GValue* value,
                          gpointer v_object);
VALA_EXTERN gpointer xi_value_get_theme (const GValue* value);
VALA_EXTERN GType xi_theme_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiTheme, xi_theme_unref)
VALA_EXTERN XiTheme* xi_theme_get_instance (void);
VALA_EXTERN void xi_line_draw (XiLine* self,
                   cairo_t* cr,
                   gdouble x,
                   gdouble y,
                   gdouble ascent);
VALA_EXTERN void xi_line_draw_cursors (XiLine* self,
                           cairo_t* cr,
                           gdouble x,
                           gdouble y,
                           gdouble line_height);
VALA_EXTERN void xi_line_draw_gutter (XiLine* self,
                          cairo_t* cr,
                          gdouble x,
                          gdouble y,
                          gdouble ascent);
VALA_EXTERN gint xi_line_x_to_index (XiLine* self,
                         gdouble x);
static void xi_line_finalize (XiLine * obj);
static GType xi_line_get_type_once (void);

static inline gpointer
xi_line_get_instance_private (XiLine* self)
{
	return G_STRUCT_MEMBER_P (self, XiLine_private_offset);
}

XiLine*
xi_line_construct (GType object_type,
                   PangoContext* context,
                   PangoFontDescription* font_description,
                   const gchar* text)
{
	XiLine* self = NULL;
	PangoLayout* _tmp0_;
	PangoLayout* _tmp1_;
	PangoLayout* _tmp2_;
	PangoLayout* _tmp3_;
	PangoLayout* _tmp4_;
	g_return_val_if_fail (context != NULL, NULL);
	g_return_val_if_fail (font_description != NULL, NULL);
	g_return_val_if_fail (text != NULL, NULL);
	self = (XiLine*) g_type_create_instance (object_type);
	_tmp0_ = pango_layout_new (context);
	_g_object_unref0 (self->priv->layout);
	self->priv->layout = _tmp0_;
	_tmp1_ = self->priv->layout;
	pango_layout_set_text (_tmp1_, text, -1);
	_tmp2_ = self->priv->layout;
	pango_layout_set_font_description (_tmp2_, font_description);
	_tmp3_ = pango_layout_new (context);
	_g_object_unref0 (self->priv->number);
	self->priv->number = _tmp3_;
	_tmp4_ = self->priv->number;
	pango_layout_set_font_description (_tmp4_, font_description);
	return self;
}

XiLine*
xi_line_new (PangoContext* context,
             PangoFontDescription* font_description,
             const gchar* text)
{
	return xi_line_construct (XI_TYPE_LINE, context, font_description, text);
}

void
xi_line_set_number (XiLine* self,
                    gint64 number)
{
	gchar* _tmp0_ = NULL;
	PangoLayout* _tmp3_;
	g_return_if_fail (self != NULL);
	if (number == ((gint64) 0)) {
		gchar* _tmp1_;
		_tmp1_ = g_strdup ("•");
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp1_;
	} else {
		gchar* _tmp2_;
		_tmp2_ = g_strdup_printf ("%" G_GINT64_FORMAT, number);
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp2_;
	}
	_tmp3_ = self->priv->number;
	pango_layout_set_text (_tmp3_, _tmp0_, -1);
	_g_free0 (_tmp0_);
}

gboolean
xi_line_is_wrapped (XiLine* self)
{
	PangoLayout* _tmp0_;
	const gchar* _tmp1_;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->number;
	_tmp1_ = pango_layout_get_text (_tmp0_);
	result = g_strcmp0 (_tmp1_, "•") == 0;
	return result;
}

void
xi_line_set_cursors (XiLine* self,
                     JsonArray* json_cursors)
{
	gint _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (json_cursors != NULL);
	_tmp0_ = (gint) json_array_get_length (json_cursors);
	self->priv->cursors = g_renew (gdouble, self->priv->cursors, (gint) json_array_get_length (json_cursors));
	(_tmp0_ > self->priv->cursors_length1) ? memset (self->priv->cursors + self->priv->cursors_length1, 0, sizeof (gdouble) * (_tmp0_ - self->priv->cursors_length1)) : NULL;
	self->priv->cursors_length1 = _tmp0_;
	self->priv->_cursors_size_ = _tmp0_;
	{
		guint i = 0U;
		i = (guint) 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gdouble* _tmp3_;
				gint _tmp3__length1;
				if (!_tmp1_) {
					guint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				if (!(i < json_array_get_length (json_cursors))) {
					break;
				}
				_tmp3_ = self->priv->cursors;
				_tmp3__length1 = self->priv->cursors_length1;
				_tmp3_[i] = xi_line_index_to_x (self, (gint) json_array_get_int_element (json_cursors, i));
			}
		}
	}
}

static void
xi_line_set_foreground (PangoAttrList* attributes,
                        guint start_index,
                        guint end_index,
                        GdkRGBA* color)
{
	PangoAttribute* attribute = NULL;
	GdkRGBA _tmp0_;
	GdkRGBA _tmp1_;
	GdkRGBA _tmp2_;
	PangoAttribute* _tmp3_;
	PangoAttribute* _tmp4_;
	PangoAttribute* _tmp5_;
	PangoAttribute* _tmp6_;
	GdkRGBA _tmp7_;
	PangoAttribute* _tmp8_;
	PangoAttribute* _tmp9_;
	PangoAttribute* _tmp10_;
	PangoAttribute* _tmp11_;
	g_return_if_fail (attributes != NULL);
	g_return_if_fail (color != NULL);
	_tmp0_ = *color;
	_tmp1_ = *color;
	_tmp2_ = *color;
	_tmp3_ = pango_attr_foreground_new ((guint16) (_tmp0_.red * G_MAXUINT16), (guint16) (_tmp1_.green * G_MAXUINT16), (guint16) (_tmp2_.blue * G_MAXUINT16));
	attribute = _tmp3_;
	_tmp4_ = attribute;
	_tmp4_->start_index = start_index;
	_tmp5_ = attribute;
	_tmp5_->end_index = end_index;
	_tmp6_ = attribute;
	attribute = NULL;
	pango_attr_list_insert (attributes, _tmp6_);
	_tmp7_ = *color;
	_tmp8_ = pango_attr_foreground_alpha_new ((guint16) (_tmp7_.alpha * G_MAXUINT16));
	_pango_attribute_destroy0 (attribute);
	attribute = _tmp8_;
	_tmp9_ = attribute;
	_tmp9_->start_index = start_index;
	_tmp10_ = attribute;
	_tmp10_->end_index = end_index;
	_tmp11_ = attribute;
	attribute = NULL;
	pango_attr_list_insert (attributes, _tmp11_);
	_pango_attribute_destroy0 (attribute);
}

static void
xi_line_set_weight (PangoAttrList* attributes,
                    guint start_index,
                    guint end_index,
                    PangoWeight weight)
{
	PangoAttribute* attribute = NULL;
	PangoAttribute* _tmp0_;
	PangoAttribute* _tmp1_;
	PangoAttribute* _tmp2_;
	PangoAttribute* _tmp3_;
	g_return_if_fail (attributes != NULL);
	_tmp0_ = pango_attr_weight_new (weight);
	attribute = _tmp0_;
	_tmp1_ = attribute;
	_tmp1_->start_index = start_index;
	_tmp2_ = attribute;
	_tmp2_->end_index = end_index;
	_tmp3_ = attribute;
	attribute = NULL;
	pango_attr_list_insert (attributes, _tmp3_);
	_pango_attribute_destroy0 (attribute);
}

static void
xi_line_set_underline (PangoAttrList* attributes,
                       guint start_index,
                       guint end_index)
{
	PangoAttribute* attribute = NULL;
	PangoAttribute* _tmp0_;
	PangoAttribute* _tmp1_;
	PangoAttribute* _tmp2_;
	PangoAttribute* _tmp3_;
	g_return_if_fail (attributes != NULL);
	_tmp0_ = pango_attr_underline_new (PANGO_UNDERLINE_SINGLE);
	attribute = _tmp0_;
	_tmp1_ = attribute;
	_tmp1_->start_index = start_index;
	_tmp2_ = attribute;
	_tmp2_->end_index = end_index;
	_tmp3_ = attribute;
	attribute = NULL;
	pango_attr_list_insert (attributes, _tmp3_);
	_pango_attribute_destroy0 (attribute);
}

static void
xi_line_set_italic (PangoAttrList* attributes,
                    guint start_index,
                    guint end_index)
{
	PangoAttribute* attribute = NULL;
	PangoAttribute* _tmp0_;
	PangoAttribute* _tmp1_;
	PangoAttribute* _tmp2_;
	PangoAttribute* _tmp3_;
	g_return_if_fail (attributes != NULL);
	_tmp0_ = pango_attr_style_new (PANGO_STYLE_ITALIC);
	attribute = _tmp0_;
	_tmp1_ = attribute;
	_tmp1_->start_index = start_index;
	_tmp2_ = attribute;
	_tmp2_->end_index = end_index;
	_tmp3_ = attribute;
	attribute = NULL;
	pango_attr_list_insert (attributes, _tmp3_);
	_pango_attribute_destroy0 (attribute);
}

static void
_xi_line_background_free0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (xi_line_background_free (var), NULL));
}

static gpointer
_xi_line_background_dup0 (gpointer self)
{
	return self ? xi_line_background_dup (self) : NULL;
}

void
xi_line_set_styles (XiLine* self,
                    JsonArray* styles)
{
	GPtrArray* _tmp0_;
	PangoAttrList* attributes = NULL;
	PangoAttrList* _tmp1_;
	guint offset = 0U;
	PangoLayout* _tmp29_;
	PangoAttrList* _tmp30_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (styles != NULL);
	_tmp0_ = g_ptr_array_new_full ((guint) 0, _xi_line_background_free0_);
	_g_ptr_array_unref0 (self->priv->backgrounds);
	self->priv->backgrounds = _tmp0_;
	_tmp1_ = pango_attr_list_new ();
	attributes = _tmp1_;
	offset = (guint) 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				guint start = 0U;
				guint end = 0U;
				gint style_id = 0;
				XiStyle style = {0};
				XiStyleMap* _tmp3_;
				XiStyleMap* _tmp4_;
				XiStyle _tmp5_ = {0};
				XiStyle _tmp6_;
				XiStyle _tmp7_;
				GdkRGBA* _tmp8_;
				XiStyle _tmp13_;
				GdkRGBA* _tmp14_;
				XiStyle _tmp20_;
				PangoWeight* _tmp21_;
				XiStyle _tmp25_;
				XiStyle _tmp27_;
				if (!_tmp2_) {
					i += 3;
				}
				_tmp2_ = FALSE;
				if (!(((guint) i) < json_array_get_length (styles))) {
					break;
				}
				start = offset + ((guint) json_array_get_int_element (styles, (guint) i));
				end = start + ((guint) json_array_get_int_element (styles, (guint) (i + 1)));
				style_id = (gint) json_array_get_int_element (styles, (guint) (i + 2));
				_tmp3_ = xi_style_map_get_instance ();
				_tmp4_ = _tmp3_;
				xi_style_map_get_style (_tmp4_, style_id, &_tmp5_);
				_tmp6_ = _tmp5_;
				_xi_style_map_unref0 (_tmp4_);
				style = _tmp6_;
				_tmp7_ = style;
				_tmp8_ = _tmp7_.foreground;
				if (_tmp8_ != NULL) {
					PangoAttrList* _tmp9_;
					XiStyle _tmp10_;
					GdkRGBA* _tmp11_;
					GdkRGBA _tmp12_;
					_tmp9_ = attributes;
					_tmp10_ = style;
					_tmp11_ = _tmp10_.foreground;
					_tmp12_ = *_tmp11_;
					xi_line_set_foreground (_tmp9_, start, end, &_tmp12_);
				}
				_tmp13_ = style;
				_tmp14_ = _tmp13_.background;
				if (_tmp14_ != NULL) {
					gdouble x = 0.0;
					gdouble width = 0.0;
					GPtrArray* _tmp15_;
					XiStyle _tmp16_;
					GdkRGBA* _tmp17_;
					XiLineBackground _tmp18_ = {0};
					XiLineBackground* _tmp19_;
					x = xi_line_index_to_x (self, (gint) start);
					width = xi_line_index_to_x (self, (gint) end) - x;
					_tmp15_ = self->priv->backgrounds;
					_tmp16_ = style;
					_tmp17_ = _tmp16_.background;
					memset (&_tmp18_, 0, sizeof (XiLineBackground));
					_tmp18_.x = x;
					_tmp18_.width = width;
					_tmp18_.color = *_tmp17_;
					_tmp19_ = _xi_line_background_dup0 (&_tmp18_);
					g_ptr_array_add (_tmp15_, _tmp19_);
				}
				_tmp20_ = style;
				_tmp21_ = _tmp20_.weight;
				if (_tmp21_ != NULL) {
					PangoAttrList* _tmp22_;
					XiStyle _tmp23_;
					PangoWeight* _tmp24_;
					_tmp22_ = attributes;
					_tmp23_ = style;
					_tmp24_ = _tmp23_.weight;
					xi_line_set_weight (_tmp22_, start, end, *_tmp24_);
				}
				_tmp25_ = style;
				if (_tmp25_.underline) {
					PangoAttrList* _tmp26_;
					_tmp26_ = attributes;
					xi_line_set_underline (_tmp26_, start, end);
				}
				_tmp27_ = style;
				if (_tmp27_.italic) {
					PangoAttrList* _tmp28_;
					_tmp28_ = attributes;
					xi_line_set_italic (_tmp28_, start, end);
				}
				offset = end;
				xi_style_destroy (&style);
			}
		}
	}
	_tmp29_ = self->priv->layout;
	_tmp30_ = attributes;
	pango_layout_set_attributes (_tmp29_, _tmp30_);
	_pango_attr_list_unref0 (attributes);
}

static gint
vala_g_ptr_array_get_length (GPtrArray* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = (gint) self->len;
	return result;
}

void
xi_line_draw_background (XiLine* self,
                         cairo_t* cr,
                         gdouble x,
                         gdouble y,
                         gdouble width,
                         gdouble line_height)
{
	gdouble* _tmp0_;
	gint _tmp0__length1;
	g_return_if_fail (self != NULL);
	g_return_if_fail (cr != NULL);
	_tmp0_ = self->priv->cursors;
	_tmp0__length1 = self->priv->cursors_length1;
	if (_tmp0__length1 > 0) {
		XiTheme* _tmp1_;
		XiTheme* _tmp2_;
		GdkRGBA _tmp3_;
		_tmp1_ = xi_theme_get_instance ();
		_tmp2_ = _tmp1_;
		_tmp3_ = _tmp2_->line_highlight;
		gdk_cairo_set_source_rgba (cr, &_tmp3_);
		_xi_theme_unref0 (_tmp2_);
		cairo_rectangle (cr, (gdouble) 0, y, width, line_height);
		cairo_fill (cr);
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp4_ = FALSE;
			_tmp4_ = TRUE;
			while (TRUE) {
				GPtrArray* _tmp6_;
				gint _tmp7_;
				gint _tmp8_;
				GPtrArray* _tmp9_;
				gconstpointer _tmp10_;
				GdkRGBA _tmp11_;
				GPtrArray* _tmp12_;
				gconstpointer _tmp13_;
				GPtrArray* _tmp14_;
				gconstpointer _tmp15_;
				if (!_tmp4_) {
					gint _tmp5_;
					_tmp5_ = i;
					i = _tmp5_ + 1;
				}
				_tmp4_ = FALSE;
				_tmp6_ = self->priv->backgrounds;
				_tmp7_ = vala_g_ptr_array_get_length (_tmp6_);
				_tmp8_ = _tmp7_;
				if (!(i < _tmp8_)) {
					break;
				}
				_tmp9_ = self->priv->backgrounds;
				_tmp10_ = g_ptr_array_index (_tmp9_, (guint) i);
				_tmp11_ = (*((XiLineBackground*) _tmp10_)).color;
				gdk_cairo_set_source_rgba (cr, &_tmp11_);
				_tmp12_ = self->priv->backgrounds;
				_tmp13_ = g_ptr_array_index (_tmp12_, (guint) i);
				_tmp14_ = self->priv->backgrounds;
				_tmp15_ = g_ptr_array_index (_tmp14_, (guint) i);
				cairo_rectangle (cr, x + (*((XiLineBackground*) _tmp13_)).x, y, (*((XiLineBackground*) _tmp15_)).width, line_height);
				cairo_fill (cr);
			}
		}
	}
}

void
xi_line_draw (XiLine* self,
              cairo_t* cr,
              gdouble x,
              gdouble y,
              gdouble ascent)
{
	XiTheme* _tmp0_;
	XiTheme* _tmp1_;
	GdkRGBA _tmp2_;
	PangoLayout* _tmp3_;
	PangoLayoutLine* _tmp4_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (cr != NULL);
	_tmp0_ = xi_theme_get_instance ();
	_tmp1_ = _tmp0_;
	_tmp2_ = _tmp1_->foreground;
	gdk_cairo_set_source_rgba (cr, &_tmp2_);
	_xi_theme_unref0 (_tmp1_);
	cairo_move_to (cr, x, y + ascent);
	_tmp3_ = self->priv->layout;
	_tmp4_ = pango_layout_get_line_readonly (_tmp3_, 0);
	pango_cairo_show_layout_line (cr, _tmp4_);
}

void
xi_line_draw_cursors (XiLine* self,
                      cairo_t* cr,
                      gdouble x,
                      gdouble y,
                      gdouble line_height)
{
	XiTheme* _tmp0_;
	XiTheme* _tmp1_;
	GdkRGBA _tmp2_;
	gdouble* _tmp3_;
	gint _tmp3__length1;
	g_return_if_fail (self != NULL);
	g_return_if_fail (cr != NULL);
	_tmp0_ = xi_theme_get_instance ();
	_tmp1_ = _tmp0_;
	_tmp2_ = _tmp1_->caret;
	gdk_cairo_set_source_rgba (cr, &_tmp2_);
	_xi_theme_unref0 (_tmp1_);
	_tmp3_ = self->priv->cursors;
	_tmp3__length1 = self->priv->cursors_length1;
	{
		gdouble* cursor_collection = NULL;
		gint cursor_collection_length1 = 0;
		gint _cursor_collection_size_ = 0;
		gint cursor_it = 0;
		cursor_collection = _tmp3_;
		cursor_collection_length1 = _tmp3__length1;
		for (cursor_it = 0; cursor_it < cursor_collection_length1; cursor_it = cursor_it + 1) {
			gdouble cursor = 0.0;
			cursor = cursor_collection[cursor_it];
			{
				cairo_rectangle (cr, x + cursor, y, (gdouble) 1, line_height);
				cairo_fill (cr);
			}
		}
	}
}

void
xi_line_draw_gutter (XiLine* self,
                     cairo_t* cr,
                     gdouble x,
                     gdouble y,
                     gdouble ascent)
{
	XiTheme* _tmp0_;
	XiTheme* _tmp1_;
	GdkRGBA _tmp2_;
	PangoRectangle extents = {0};
	PangoLayout* _tmp3_;
	PangoLayoutLine* _tmp4_;
	PangoRectangle _tmp5_ = {0};
	PangoRectangle _tmp6_;
	PangoLayout* _tmp7_;
	PangoLayoutLine* _tmp8_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (cr != NULL);
	_tmp0_ = xi_theme_get_instance ();
	_tmp1_ = _tmp0_;
	_tmp2_ = _tmp1_->gutter_foreground;
	gdk_cairo_set_source_rgba (cr, &_tmp2_);
	_xi_theme_unref0 (_tmp1_);
	_tmp3_ = self->priv->number;
	_tmp4_ = pango_layout_get_line_readonly (_tmp3_, 0);
	pango_layout_line_get_pixel_extents (_tmp4_, NULL, &_tmp5_);
	extents = _tmp5_;
	_tmp6_ = extents;
	cairo_move_to (cr, x - _tmp6_.width, y + ascent);
	_tmp7_ = self->priv->number;
	_tmp8_ = pango_layout_get_line_readonly (_tmp7_, 0);
	pango_cairo_show_layout_line (cr, _tmp8_);
}

gdouble
xi_line_index_to_x (XiLine* self,
                    gint index)
{
	gint x_pos = 0;
	PangoLayout* _tmp0_;
	PangoLayoutLine* _tmp1_;
	gint _tmp2_ = 0;
	gdouble result;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->layout;
	_tmp1_ = pango_layout_get_line_readonly (_tmp0_, 0);
	pango_layout_line_index_to_x (_tmp1_, index, FALSE, &_tmp2_);
	x_pos = _tmp2_;
	result = pango_units_to_double (x_pos);
	return result;
}

static gboolean
string_get_next_char (const gchar* self,
                      gint* index,
                      gunichar* c)
{
	gunichar _vala_c = 0U;
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	_vala_c = g_utf8_get_char (((gchar*) self) + (*index));
	if (_vala_c != ((gunichar) 0)) {
		gchar* _tmp0_;
		_tmp0_ = g_utf8_next_char (((gchar*) self) + (*index));
		*index = (gint) (_tmp0_ - ((gchar*) self));
		result = TRUE;
		if (c) {
			*c = _vala_c;
		}
		return result;
	} else {
		result = FALSE;
		if (c) {
			*c = _vala_c;
		}
		return result;
	}
}

gint
xi_line_x_to_index (XiLine* self,
                    gdouble x)
{
	gint index = 0;
	gint trailing = 0;
	PangoLayout* _tmp0_;
	PangoLayoutLine* _tmp1_;
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->layout;
	_tmp1_ = pango_layout_get_line_readonly (_tmp0_, 0);
	pango_layout_line_x_to_index (_tmp1_, pango_units_from_double (x), &_tmp2_, &_tmp3_);
	index = _tmp2_;
	trailing = _tmp3_;
	{
		gboolean _tmp4_ = FALSE;
		_tmp4_ = TRUE;
		while (TRUE) {
			PangoLayout* _tmp6_;
			const gchar* _tmp7_;
			if (!_tmp4_) {
				gint _tmp5_;
				_tmp5_ = trailing;
				trailing = _tmp5_ - 1;
			}
			_tmp4_ = FALSE;
			if (!(trailing > 0)) {
				break;
			}
			_tmp6_ = self->priv->layout;
			_tmp7_ = pango_layout_get_text (_tmp6_);
			string_get_next_char (_tmp7_, &index, NULL);
		}
	}
	result = index;
	return result;
}

static XiLineBackground*
xi_line_background_dup (const XiLineBackground* self)
{
	XiLineBackground* dup;
	dup = g_new0 (XiLineBackground, 1);
	memcpy (dup, self, sizeof (XiLineBackground));
	return dup;
}

static void
xi_line_background_free (XiLineBackground* self)
{
	g_free (self);
}

static GType
xi_line_background_get_type_once (void)
{
	GType xi_line_background_type_id;
	xi_line_background_type_id = g_boxed_type_register_static ("XiLineBackground", (GBoxedCopyFunc) xi_line_background_dup, (GBoxedFreeFunc) xi_line_background_free);
	return xi_line_background_type_id;
}

static GType
xi_line_background_get_type (void)
{
	static volatile gsize xi_line_background_type_id__once = 0;
	if (g_once_init_enter (&xi_line_background_type_id__once)) {
		GType xi_line_background_type_id;
		xi_line_background_type_id = xi_line_background_get_type_once ();
		g_once_init_leave (&xi_line_background_type_id__once, xi_line_background_type_id);
	}
	return xi_line_background_type_id__once;
}

static void
xi_value_line_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
xi_value_line_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		xi_line_unref (value->data[0].v_pointer);
	}
}

static void
xi_value_line_copy_value (const GValue* src_value,
                          GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = xi_line_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
xi_value_line_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
xi_value_line_collect_value (GValue* value,
                             guint n_collect_values,
                             GTypeCValue* collect_values,
                             guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		XiLine * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = xi_line_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
xi_value_line_lcopy_value (const GValue* value,
                           guint n_collect_values,
                           GTypeCValue* collect_values,
                           guint collect_flags)
{
	XiLine ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = xi_line_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
xi_param_spec_line (const gchar* name,
                    const gchar* nick,
                    const gchar* blurb,
                    GType object_type,
                    GParamFlags flags)
{
	XiParamSpecLine* spec;
	g_return_val_if_fail (g_type_is_a (object_type, XI_TYPE_LINE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
xi_value_get_line (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_LINE), NULL);
	return value->data[0].v_pointer;
}

void
xi_value_set_line (GValue* value,
                   gpointer v_object)
{
	XiLine * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_LINE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_LINE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		xi_line_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_line_unref (old);
	}
}

void
xi_value_take_line (GValue* value,
                    gpointer v_object)
{
	XiLine * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_LINE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_LINE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_line_unref (old);
	}
}

static void
xi_line_class_init (XiLineClass * klass,
                    gpointer klass_data)
{
	xi_line_parent_class = g_type_class_peek_parent (klass);
	((XiLineClass *) klass)->finalize = xi_line_finalize;
	g_type_class_adjust_private_offset (klass, &XiLine_private_offset);
}

static void
xi_line_instance_init (XiLine * self,
                       gpointer klass)
{
	self->priv = xi_line_get_instance_private (self);
	self->ref_count = 1;
}

static void
xi_line_finalize (XiLine * obj)
{
	XiLine * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_LINE, XiLine);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->priv->layout);
	_g_object_unref0 (self->priv->number);
	self->priv->cursors = (g_free (self->priv->cursors), NULL);
	_g_ptr_array_unref0 (self->priv->backgrounds);
}

static GType
xi_line_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { xi_value_line_init, xi_value_line_free_value, xi_value_line_copy_value, xi_value_line_peek_pointer, "p", xi_value_line_collect_value, "p", xi_value_line_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (XiLineClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_line_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiLine), 0, (GInstanceInitFunc) xi_line_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType xi_line_type_id;
	xi_line_type_id = g_type_register_fundamental (g_type_fundamental_next (), "XiLine", &g_define_type_info, &g_define_type_fundamental_info, 0);
	XiLine_private_offset = g_type_add_instance_private (xi_line_type_id, sizeof (XiLinePrivate));
	return xi_line_type_id;
}

GType
xi_line_get_type (void)
{
	static volatile gsize xi_line_type_id__once = 0;
	if (g_once_init_enter (&xi_line_type_id__once)) {
		GType xi_line_type_id;
		xi_line_type_id = xi_line_get_type_once ();
		g_once_init_leave (&xi_line_type_id__once, xi_line_type_id);
	}
	return xi_line_type_id__once;
}

gpointer
xi_line_ref (gpointer instance)
{
	XiLine * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
xi_line_unref (gpointer instance)
{
	XiLine * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		XI_LINE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

