/* Notebook.c generated by valac 0.56.18, the Vala compiler
 * generated from Notebook.vala, do not modify */

/* Copyright 2016-2018 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_NOTEBOOK (xi_notebook_get_type ())
#define XI_NOTEBOOK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_NOTEBOOK, XiNotebook))
#define XI_NOTEBOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_NOTEBOOK, XiNotebookClass))
#define XI_IS_NOTEBOOK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_NOTEBOOK))
#define XI_IS_NOTEBOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_NOTEBOOK))
#define XI_NOTEBOOK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_NOTEBOOK, XiNotebookClass))

typedef struct _XiNotebook XiNotebook;
typedef struct _XiNotebookClass XiNotebookClass;
typedef struct _XiNotebookPrivate XiNotebookPrivate;
enum  {
	XI_NOTEBOOK_0_PROPERTY,
	XI_NOTEBOOK_NUM_PROPERTIES
};
static GParamSpec* xi_notebook_properties[XI_NOTEBOOK_NUM_PROPERTIES];

#define XI_TYPE_EDIT_VIEW_CONTAINER (xi_edit_view_container_get_type ())
#define XI_EDIT_VIEW_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_EDIT_VIEW_CONTAINER, XiEditViewContainer))
#define XI_EDIT_VIEW_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_EDIT_VIEW_CONTAINER, XiEditViewContainerClass))
#define XI_IS_EDIT_VIEW_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_EDIT_VIEW_CONTAINER))
#define XI_IS_EDIT_VIEW_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_EDIT_VIEW_CONTAINER))
#define XI_EDIT_VIEW_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_EDIT_VIEW_CONTAINER, XiEditViewContainerClass))

typedef struct _XiEditViewContainer XiEditViewContainer;
typedef struct _XiEditViewContainerClass XiEditViewContainerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;

#define XI_TYPE_EDIT_VIEW (xi_edit_view_get_type ())
#define XI_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_EDIT_VIEW, XiEditView))
#define XI_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_EDIT_VIEW, XiEditViewClass))
#define XI_IS_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_EDIT_VIEW))
#define XI_IS_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_EDIT_VIEW))
#define XI_EDIT_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_EDIT_VIEW, XiEditViewClass))

typedef struct _XiEditView XiEditView;
typedef struct _XiEditViewClass XiEditViewClass;

#define XI_TYPE_CORE_CONNECTION (xi_core_connection_get_type ())
#define XI_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnection))
#define XI_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))
#define XI_IS_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_CORE_CONNECTION))
#define XI_IS_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_CORE_CONNECTION))
#define XI_CORE_CONNECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))

typedef struct _XiCoreConnection XiCoreConnection;
typedef struct _XiCoreConnectionClass XiCoreConnectionClass;

struct _XiNotebook {
	GtkNotebook parent_instance;
	XiNotebookPrivate * priv;
};

struct _XiNotebookClass {
	GtkNotebookClass parent_class;
};

struct _Block1Data {
	int _ref_count_;
	XiNotebook* self;
	XiEditViewContainer* container;
};

static gpointer xi_notebook_parent_class = NULL;

VALA_EXTERN GType xi_notebook_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiNotebook, g_object_unref)
VALA_EXTERN XiNotebook* xi_notebook_new (void);
VALA_EXTERN XiNotebook* xi_notebook_construct (GType object_type);
VALA_EXTERN GType xi_edit_view_container_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiEditViewContainer, g_object_unref)
static GtkBox* xi_notebook_create_tab_label (XiNotebook* self,
                                      XiEditViewContainer* container);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
VALA_EXTERN GType xi_edit_view_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiEditView, g_object_unref)
VALA_EXTERN XiEditView* xi_edit_view_container_get_edit_view (XiEditViewContainer* self);
VALA_EXTERN const gchar* xi_edit_view_get_label (XiEditView* self);
static void __lambda10_ (Block1Data* _data1_);
static void ___lambda10__gtk_button_clicked (GtkButton* _sender,
                                      gpointer self);
VALA_EXTERN gpointer xi_core_connection_ref (gpointer instance);
VALA_EXTERN void xi_core_connection_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_core_connection (const gchar* name,
                                           const gchar* nick,
                                           const gchar* blurb,
                                           GType object_type,
                                           GParamFlags flags);
VALA_EXTERN void xi_value_set_core_connection (GValue* value,
                                   gpointer v_object);
VALA_EXTERN void xi_value_take_core_connection (GValue* value,
                                    gpointer v_object);
VALA_EXTERN gpointer xi_value_get_core_connection (const GValue* value);
VALA_EXTERN GType xi_core_connection_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiCoreConnection, xi_core_connection_unref)
VALA_EXTERN void xi_notebook_add_edit_view (XiNotebook* self,
                                XiCoreConnection* core_connection,
                                const gchar* view_id,
                                GFile* file);
VALA_EXTERN XiEditViewContainer* xi_edit_view_container_new (XiCoreConnection* core_connection,
                                                 const gchar* view_id,
                                                 GFile* file);
VALA_EXTERN XiEditViewContainer* xi_edit_view_container_construct (GType object_type,
                                                       XiCoreConnection* core_connection,
                                                       const gchar* view_id,
                                                       GFile* file);
VALA_EXTERN XiEditViewContainer* xi_notebook_get_current_edit_view (XiNotebook* self);
static void xi_notebook_real_grab_focus (GtkWidget* base);
static GType xi_notebook_get_type_once (void);

XiNotebook*
xi_notebook_construct (GType object_type)
{
	XiNotebook * self = NULL;
	self = (XiNotebook*) g_object_new (object_type, "scrollable", TRUE, "show-border", FALSE, NULL);
	return self;
}

XiNotebook*
xi_notebook_new (void)
{
	return xi_notebook_construct (XI_TYPE_NOTEBOOK);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		XiNotebook* self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->container);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}

static void
__lambda10_ (Block1Data* _data1_)
{
	XiNotebook* self;
	gint index = 0;
	self = _data1_->self;
	index = gtk_notebook_page_num ((GtkNotebook*) self, (GtkWidget*) _data1_->container);
	gtk_notebook_remove_page ((GtkNotebook*) self, index);
}

static void
___lambda10__gtk_button_clicked (GtkButton* _sender,
                                 gpointer self)
{
	__lambda10_ (self);
}

static GtkBox*
xi_notebook_create_tab_label (XiNotebook* self,
                              XiEditViewContainer* container)
{
	Block1Data* _data1_;
	XiEditViewContainer* _tmp0_;
	XiEditView* edit_view = NULL;
	XiEditView* _tmp1_;
	GtkBox* box = NULL;
	GtkBox* _tmp2_;
	GtkLabel* label = NULL;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	GtkLabel* _tmp5_;
	GtkButton* close_button = NULL;
	GtkButton* _tmp6_;
	GtkImage* close_image = NULL;
	GtkImage* _tmp7_;
	GtkImage* image = NULL;
	GtkImage* _tmp8_;
	GtkBox* result;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (container != NULL, NULL);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_tmp0_ = _g_object_ref0 (container);
	_g_object_unref0 (_data1_->container);
	_data1_->container = _tmp0_;
	_tmp1_ = xi_edit_view_container_get_edit_view (_data1_->container);
	edit_view = _tmp1_;
	_tmp2_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp2_);
	box = _tmp2_;
	_tmp3_ = xi_edit_view_get_label (edit_view);
	_tmp4_ = _tmp3_;
	_tmp5_ = (GtkLabel*) gtk_label_new (_tmp4_);
	g_object_ref_sink (_tmp5_);
	label = _tmp5_;
	g_object_bind_property_with_closures ((GObject*) edit_view, "label", (GObject*) label, "label", G_BINDING_DEFAULT, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)));
	gtk_box_set_center_widget (box, (GtkWidget*) label);
	_tmp6_ = (GtkButton*) gtk_button_new ();
	g_object_ref_sink (_tmp6_);
	close_button = _tmp6_;
	_tmp7_ = (GtkImage*) gtk_image_new_from_icon_name ("window-close-symbolic", (GtkIconSize) GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp7_);
	close_image = _tmp7_;
	gtk_container_add ((GtkContainer*) close_button, (GtkWidget*) close_image);
	gtk_button_set_relief (close_button, GTK_RELIEF_NONE);
	gtk_widget_set_focus_on_click ((GtkWidget*) close_button, FALSE);
	g_signal_connect_data (close_button, "clicked", (GCallback) ___lambda10__gtk_button_clicked, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	gtk_box_pack_end (box, (GtkWidget*) close_button, FALSE, TRUE, (guint) 0);
	_tmp8_ = (GtkImage*) gtk_image_new_from_icon_name ("media-record-symbolic", (GtkIconSize) GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp8_);
	image = _tmp8_;
	g_object_bind_property_with_closures ((GObject*) edit_view, "has-unsaved-changes", (GObject*) image, "visible", G_BINDING_DEFAULT, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, (GClosureNotify) NULL)));
	gtk_box_pack_end (box, (GtkWidget*) image, FALSE, TRUE, (guint) 0);
	gtk_widget_show ((GtkWidget*) label);
	gtk_widget_show_all ((GtkWidget*) close_button);
	result = box;
	_g_object_unref0 (image);
	_g_object_unref0 (close_image);
	_g_object_unref0 (close_button);
	_g_object_unref0 (label);
	block1_data_unref (_data1_);
	_data1_ = NULL;
	return result;
}

void
xi_notebook_add_edit_view (XiNotebook* self,
                           XiCoreConnection* core_connection,
                           const gchar* view_id,
                           GFile* file)
{
	XiEditViewContainer* container = NULL;
	XiEditViewContainer* _tmp0_;
	GtkBox* label = NULL;
	GtkBox* _tmp1_;
	GValue _tmp2_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (core_connection != NULL);
	g_return_if_fail (view_id != NULL);
	_tmp0_ = xi_edit_view_container_new (core_connection, view_id, file);
	g_object_ref_sink (_tmp0_);
	container = _tmp0_;
	_tmp1_ = xi_notebook_create_tab_label (self, container);
	label = _tmp1_;
	gtk_notebook_append_page ((GtkNotebook*) self, (GtkWidget*) container, (GtkWidget*) label);
	gtk_notebook_set_tab_reorderable ((GtkNotebook*) self, (GtkWidget*) container, TRUE);
	g_value_init (&_tmp2_, G_TYPE_BOOLEAN);
	g_value_set_boolean (&_tmp2_, TRUE);
	gtk_container_child_set_property ((GtkContainer*) self, (GtkWidget*) container, "tab-expand", &_tmp2_);
	G_IS_VALUE (&_tmp2_) ? (g_value_unset (&_tmp2_), NULL) : NULL;
	gtk_widget_show ((GtkWidget*) container);
	gtk_widget_show ((GtkWidget*) label);
	gtk_notebook_set_current_page ((GtkNotebook*) self, gtk_notebook_page_num ((GtkNotebook*) self, (GtkWidget*) container));
	gtk_widget_grab_focus ((GtkWidget*) container);
	_g_object_unref0 (label);
	_g_object_unref0 (container);
}

XiEditViewContainer*
xi_notebook_get_current_edit_view (XiNotebook* self)
{
	gint index = 0;
	GtkWidget* _tmp0_;
	XiEditViewContainer* result;
	g_return_val_if_fail (self != NULL, NULL);
	index = gtk_notebook_get_current_page ((GtkNotebook*) self);
	_tmp0_ = gtk_notebook_get_nth_page ((GtkNotebook*) self, index);
	result = XI_IS_EDIT_VIEW_CONTAINER (_tmp0_) ? ((XiEditViewContainer*) _tmp0_) : NULL;
	return result;
}

static void
xi_notebook_real_grab_focus (GtkWidget* base)
{
	XiNotebook * self;
	XiEditViewContainer* _tmp0_;
	self = (XiNotebook*) base;
	_tmp0_ = xi_notebook_get_current_edit_view (self);
	gtk_widget_grab_focus ((GtkWidget*) _tmp0_);
}

static void
xi_notebook_class_init (XiNotebookClass * klass,
                        gpointer klass_data)
{
	xi_notebook_parent_class = g_type_class_peek_parent (klass);
	((GtkWidgetClass *) klass)->grab_focus = (void (*) (GtkWidget*)) xi_notebook_real_grab_focus;
}

static void
xi_notebook_instance_init (XiNotebook * self,
                           gpointer klass)
{
}

static GType
xi_notebook_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (XiNotebookClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_notebook_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiNotebook), 0, (GInstanceInitFunc) xi_notebook_instance_init, NULL };
	GType xi_notebook_type_id;
	xi_notebook_type_id = g_type_register_static (gtk_notebook_get_type (), "XiNotebook", &g_define_type_info, 0);
	return xi_notebook_type_id;
}

GType
xi_notebook_get_type (void)
{
	static volatile gsize xi_notebook_type_id__once = 0;
	if (g_once_init_enter (&xi_notebook_type_id__once)) {
		GType xi_notebook_type_id;
		xi_notebook_type_id = xi_notebook_get_type_once ();
		g_once_init_leave (&xi_notebook_type_id__once, xi_notebook_type_id);
	}
	return xi_notebook_type_id__once;
}

