/* StyleMap.c generated by valac 0.56.18, the Vala compiler
 * generated from StyleMap.vala, do not modify */

/* Copyright 2017 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <glib-object.h>
#include <glib.h>
#include <gdk/gdk.h>
#include <pango/pango.h>
#include <json-glib/json-glib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_STYLE_MAP (xi_style_map_get_type ())
#define XI_STYLE_MAP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_STYLE_MAP, XiStyleMap))
#define XI_STYLE_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_STYLE_MAP, XiStyleMapClass))
#define XI_IS_STYLE_MAP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_STYLE_MAP))
#define XI_IS_STYLE_MAP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_STYLE_MAP))
#define XI_STYLE_MAP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_STYLE_MAP, XiStyleMapClass))

typedef struct _XiStyleMap XiStyleMap;
typedef struct _XiStyleMapClass XiStyleMapClass;
typedef struct _XiStyleMapPrivate XiStyleMapPrivate;

#define XI_TYPE_STYLE (xi_style_get_type ())
typedef struct _XiStyle XiStyle;
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))
#define _xi_style_map_unref0(var) ((var == NULL) ? NULL : (var = (xi_style_map_unref (var), NULL)))
#define __vala_GdkRGBA_free0(var) ((var == NULL) ? NULL : (var = (_vala_GdkRGBA_free (var), NULL)))
#define _g_free0(var) ((var == NULL) ? NULL : (var = (g_free (var), NULL)))

#define XI_TYPE_THEME (xi_theme_get_type ())
#define XI_THEME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_THEME, XiTheme))
#define XI_THEME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_THEME, XiThemeClass))
#define XI_IS_THEME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_THEME))
#define XI_IS_THEME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_THEME))
#define XI_THEME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_THEME, XiThemeClass))

typedef struct _XiTheme XiTheme;
typedef struct _XiThemeClass XiThemeClass;
typedef struct _XiThemePrivate XiThemePrivate;
#define _xi_theme_unref0(var) ((var == NULL) ? NULL : (var = (xi_theme_unref (var), NULL)))
typedef struct _XiParamSpecStyleMap XiParamSpecStyleMap;

struct _XiStyleMap {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XiStyleMapPrivate * priv;
};

struct _XiStyleMapClass {
	GTypeClass parent_class;
	void (*finalize) (XiStyleMap *self);
};

struct _XiStyle {
	GdkRGBA* foreground;
	GdkRGBA* background;
	PangoWeight* weight;
	gboolean underline;
	gboolean italic;
};

struct _XiStyleMapPrivate {
	GPtrArray* map;
};

struct _XiTheme {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XiThemePrivate * priv;
	GdkRGBA foreground;
	GdkRGBA background;
	GdkRGBA caret;
	GdkRGBA line_highlight;
	GdkRGBA selection;
	GdkRGBA gutter;
	GdkRGBA gutter_foreground;
	GdkRGBA find_highlight;
	GdkRGBA find_highlight_foreground;
};

struct _XiThemeClass {
	GTypeClass parent_class;
	void (*finalize) (XiTheme *self);
};

struct _XiParamSpecStyleMap {
	GParamSpec parent_instance;
};

static gint XiStyleMap_private_offset;
static gpointer xi_style_map_parent_class = NULL;
static XiStyleMap* xi_style_map_instance;
static XiStyleMap* xi_style_map_instance = NULL;

VALA_EXTERN gpointer xi_style_map_ref (gpointer instance);
VALA_EXTERN void xi_style_map_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_style_map (const gchar* name,
                                     const gchar* nick,
                                     const gchar* blurb,
                                     GType object_type,
                                     GParamFlags flags);
VALA_EXTERN void xi_value_set_style_map (GValue* value,
                             gpointer v_object);
VALA_EXTERN void xi_value_take_style_map (GValue* value,
                              gpointer v_object);
VALA_EXTERN gpointer xi_value_get_style_map (const GValue* value);
VALA_EXTERN GType xi_style_map_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiStyleMap, xi_style_map_unref)
VALA_EXTERN GType xi_style_get_type (void) G_GNUC_CONST ;
VALA_EXTERN XiStyle* xi_style_dup (const XiStyle* self);
VALA_EXTERN void xi_style_free (XiStyle* self);
VALA_EXTERN void xi_style_copy (const XiStyle* self,
                    XiStyle* dest);
VALA_EXTERN void xi_style_destroy (XiStyle* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (XiStyle, xi_style_destroy)
VALA_EXTERN XiStyleMap* xi_style_map_get_instance (void);
VALA_EXTERN XiStyleMap* xi_style_map_new (void);
VALA_EXTERN XiStyleMap* xi_style_map_construct (GType object_type);
static void _xi_style_free0_ (gpointer var);
VALA_EXTERN void xi_style_map_def_style (XiStyleMap* self,
                             JsonObject* json_style);
VALA_EXTERN void xi_utilities_convert_color (guint32 color,
                                 GdkRGBA* result);
static GdkRGBA* _vala_GdkRGBA_copy (GdkRGBA* self);
static void _vala_GdkRGBA_free (GdkRGBA* self);
static PangoWeight* _pango_weight_dup (PangoWeight* self);
VALA_EXTERN void xi_style_map_get_style (XiStyleMap* self,
                             gint id,
                             XiStyle* result);
VALA_EXTERN gpointer xi_theme_ref (gpointer instance);
VALA_EXTERN void xi_theme_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_theme (const gchar* name,
                                 const gchar* nick,
                                 const gchar* blurb,
                                 GType object_type,
                                 GParamFlags flags);
VALA_EXTERN void xi_value_set_theme (GValue* value,
                         gpointer v_object);
VALA_EXTERN void xi_value_take_theme (GValue* value,
                          gpointer v_object);
VALA_EXTERN gpointer xi_value_get_theme (const GValue* value);
VALA_EXTERN GType xi_theme_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiTheme, xi_theme_unref)
VALA_EXTERN XiTheme* xi_theme_get_instance (void);
static void xi_style_map_finalize (XiStyleMap * obj);
static GType xi_style_map_get_type_once (void);

static inline gpointer
xi_style_map_get_instance_private (XiStyleMap* self)
{
	return G_STRUCT_MEMBER_P (self, XiStyleMap_private_offset);
}

static gpointer
_xi_style_map_ref0 (gpointer self)
{
	return self ? xi_style_map_ref (self) : NULL;
}

XiStyleMap*
xi_style_map_get_instance (void)
{
	XiStyleMap* _tmp0_;
	XiStyleMap* _tmp2_;
	XiStyleMap* _tmp3_;
	XiStyleMap* result;
	_tmp0_ = xi_style_map_instance;
	if (_tmp0_ == NULL) {
		XiStyleMap* _tmp1_;
		_tmp1_ = xi_style_map_new ();
		_xi_style_map_unref0 (xi_style_map_instance);
		xi_style_map_instance = _tmp1_;
	}
	_tmp2_ = xi_style_map_instance;
	_tmp3_ = _xi_style_map_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}

static void
_xi_style_free0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (xi_style_free (var), NULL));
}

XiStyleMap*
xi_style_map_construct (GType object_type)
{
	XiStyleMap* self = NULL;
	GPtrArray* _tmp0_;
	self = (XiStyleMap*) g_type_create_instance (object_type);
	_tmp0_ = g_ptr_array_new_full ((guint) 0, _xi_style_free0_);
	_g_ptr_array_unref0 (self->priv->map);
	self->priv->map = _tmp0_;
	return self;
}

XiStyleMap*
xi_style_map_new (void)
{
	return xi_style_map_construct (XI_TYPE_STYLE_MAP);
}

static GdkRGBA*
_vala_GdkRGBA_copy (GdkRGBA* self)
{
	return g_boxed_copy (gdk_rgba_get_type (), self);
}

static gpointer
__vala_GdkRGBA_copy0 (gpointer self)
{
	return self ? _vala_GdkRGBA_copy (self) : NULL;
}

static void
_vala_GdkRGBA_free (GdkRGBA* self)
{
	g_boxed_free (gdk_rgba_get_type (), self);
}

static PangoWeight*
_pango_weight_dup (PangoWeight* self)
{
	PangoWeight* dup;
	dup = g_new0 (PangoWeight, 1);
	memcpy (dup, self, sizeof (PangoWeight));
	return dup;
}

static gpointer
__pango_weight_dup0 (gpointer self)
{
	return self ? _pango_weight_dup (self) : NULL;
}

static gint
vala_g_ptr_array_get_length (GPtrArray* self)
{
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = (gint) self->len;
	return result;
}

static void
g_ptr_array_set (GPtrArray* self,
                 guint index,
                 gpointer data)
{
	gpointer _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = data;
	data = NULL;
	g_ptr_array_add (self, _tmp0_);
	g_ptr_array_remove_index_fast (self, index);
}

static gpointer
_xi_style_dup0 (gpointer self)
{
	return self ? xi_style_dup (self) : NULL;
}

void
xi_style_map_def_style (XiStyleMap* self,
                        JsonObject* json_style)
{
	gint id = 0;
	XiStyle style = {0};
	GPtrArray* _tmp6_;
	gint _tmp7_;
	gint _tmp8_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (json_style != NULL);
	id = (gint) json_object_get_int_member (json_style, "id");
	memset (&style, 0, sizeof (XiStyle));
	if (json_object_has_member (json_style, "fg_color")) {
		guint32 fg_color = 0U;
		GdkRGBA _tmp0_ = {0};
		GdkRGBA* _tmp1_;
		fg_color = (guint32) json_object_get_int_member (json_style, "fg_color");
		xi_utilities_convert_color (fg_color, &_tmp0_);
		_tmp1_ = __vala_GdkRGBA_copy0 (&_tmp0_);
		__vala_GdkRGBA_free0 (style.foreground);
		style.foreground = _tmp1_;
	}
	if (json_object_has_member (json_style, "bg_color")) {
		guint32 bg_color = 0U;
		GdkRGBA _tmp2_ = {0};
		GdkRGBA* _tmp3_;
		bg_color = (guint32) json_object_get_int_member (json_style, "bg_color");
		xi_utilities_convert_color (bg_color, &_tmp2_);
		_tmp3_ = __vala_GdkRGBA_copy0 (&_tmp2_);
		__vala_GdkRGBA_free0 (style.background);
		style.background = _tmp3_;
	}
	if (json_object_has_member (json_style, "weight")) {
		PangoWeight _tmp4_;
		PangoWeight* _tmp5_;
		_tmp4_ = (PangoWeight) json_object_get_int_member (json_style, "weight");
		_tmp5_ = __pango_weight_dup0 (&_tmp4_);
		_g_free0 (style.weight);
		style.weight = _tmp5_;
	}
	if (json_object_has_member (json_style, "underline")) {
		style.underline = json_object_get_boolean_member (json_style, "underline");
	}
	if (json_object_has_member (json_style, "italic")) {
		style.italic = json_object_get_boolean_member (json_style, "italic");
	}
	_tmp6_ = self->priv->map;
	_tmp7_ = vala_g_ptr_array_get_length (_tmp6_);
	_tmp8_ = _tmp7_;
	if (id < _tmp8_) {
		GPtrArray* _tmp9_;
		XiStyle _tmp10_;
		XiStyle _tmp11_;
		XiStyle* _tmp12_;
		_tmp9_ = self->priv->map;
		_tmp10_ = style;
		_tmp11_ = _tmp10_;
		_tmp12_ = _xi_style_dup0 (&_tmp11_);
		g_ptr_array_set (_tmp9_, (guint) id, _tmp12_);
	} else {
		GPtrArray* _tmp19_;
		XiStyle _tmp20_;
		XiStyle _tmp21_;
		XiStyle* _tmp22_;
		{
			gint i = 0;
			GPtrArray* _tmp13_;
			gint _tmp14_;
			gint _tmp15_;
			_tmp13_ = self->priv->map;
			_tmp14_ = vala_g_ptr_array_get_length (_tmp13_);
			_tmp15_ = _tmp14_;
			i = _tmp15_;
			{
				gboolean _tmp16_ = FALSE;
				_tmp16_ = TRUE;
				while (TRUE) {
					GPtrArray* _tmp18_;
					if (!_tmp16_) {
						gint _tmp17_;
						_tmp17_ = i;
						i = _tmp17_ + 1;
					}
					_tmp16_ = FALSE;
					if (!(i < id)) {
						break;
					}
					_tmp18_ = self->priv->map;
					g_ptr_array_add (_tmp18_, NULL);
				}
			}
		}
		_tmp19_ = self->priv->map;
		_tmp20_ = style;
		_tmp21_ = _tmp20_;
		_tmp22_ = _xi_style_dup0 (&_tmp21_);
		g_ptr_array_add (_tmp19_, _tmp22_);
	}
	xi_style_destroy (&style);
}

void
xi_style_map_get_style (XiStyleMap* self,
                        gint id,
                        XiStyle* result)
{
	g_return_if_fail (self != NULL);
	switch (id) {
		case 0:
		{
			XiTheme* _tmp0_;
			XiTheme* _tmp1_;
			GdkRGBA _tmp2_;
			GdkRGBA* _tmp3_;
			XiStyle _tmp4_ = {0};
			XiStyle _tmp5_;
			_tmp0_ = xi_theme_get_instance ();
			_tmp1_ = _tmp0_;
			_tmp2_ = _tmp1_->selection;
			_tmp3_ = __vala_GdkRGBA_copy0 (&_tmp2_);
			memset (&_tmp4_, 0, sizeof (XiStyle));
			__vala_GdkRGBA_free0 (_tmp4_.background);
			_tmp4_.background = _tmp3_;
			_tmp5_ = _tmp4_;
			_xi_theme_unref0 (_tmp1_);
			*result = _tmp5_;
			return;
		}
		case 1:
		{
			XiTheme* _tmp6_;
			XiTheme* _tmp7_;
			GdkRGBA _tmp8_;
			GdkRGBA* _tmp9_;
			XiTheme* _tmp10_;
			XiTheme* _tmp11_;
			GdkRGBA _tmp12_;
			GdkRGBA* _tmp13_;
			XiStyle _tmp14_ = {0};
			XiStyle _tmp15_;
			_tmp6_ = xi_theme_get_instance ();
			_tmp7_ = _tmp6_;
			_tmp8_ = _tmp7_->find_highlight_foreground;
			_tmp9_ = __vala_GdkRGBA_copy0 (&_tmp8_);
			_tmp10_ = xi_theme_get_instance ();
			_tmp11_ = _tmp10_;
			_tmp12_ = _tmp11_->find_highlight;
			_tmp13_ = __vala_GdkRGBA_copy0 (&_tmp12_);
			memset (&_tmp14_, 0, sizeof (XiStyle));
			__vala_GdkRGBA_free0 (_tmp14_.foreground);
			_tmp14_.foreground = _tmp9_;
			__vala_GdkRGBA_free0 (_tmp14_.background);
			_tmp14_.background = _tmp13_;
			_tmp15_ = _tmp14_;
			_xi_theme_unref0 (_tmp11_);
			_xi_theme_unref0 (_tmp7_);
			*result = _tmp15_;
			return;
		}
		default:
		{
			GPtrArray* _tmp16_;
			gconstpointer _tmp17_;
			XiStyle _tmp18_;
			XiStyle _tmp19_ = {0};
			_tmp16_ = self->priv->map;
			_tmp17_ = g_ptr_array_index (_tmp16_, (guint) id);
			_tmp18_ = *((XiStyle*) _tmp17_);
			xi_style_copy (&_tmp18_, &_tmp19_);
			*result = _tmp19_;
			return;
		}
	}
}

static void
xi_value_style_map_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
xi_value_style_map_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		xi_style_map_unref (value->data[0].v_pointer);
	}
}

static void
xi_value_style_map_copy_value (const GValue* src_value,
                               GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = xi_style_map_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
xi_value_style_map_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
xi_value_style_map_collect_value (GValue* value,
                                  guint n_collect_values,
                                  GTypeCValue* collect_values,
                                  guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		XiStyleMap * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = xi_style_map_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
xi_value_style_map_lcopy_value (const GValue* value,
                                guint n_collect_values,
                                GTypeCValue* collect_values,
                                guint collect_flags)
{
	XiStyleMap ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = xi_style_map_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
xi_param_spec_style_map (const gchar* name,
                         const gchar* nick,
                         const gchar* blurb,
                         GType object_type,
                         GParamFlags flags)
{
	XiParamSpecStyleMap* spec;
	g_return_val_if_fail (g_type_is_a (object_type, XI_TYPE_STYLE_MAP), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
xi_value_get_style_map (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_STYLE_MAP), NULL);
	return value->data[0].v_pointer;
}

void
xi_value_set_style_map (GValue* value,
                        gpointer v_object)
{
	XiStyleMap * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_STYLE_MAP));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_STYLE_MAP));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		xi_style_map_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_style_map_unref (old);
	}
}

void
xi_value_take_style_map (GValue* value,
                         gpointer v_object)
{
	XiStyleMap * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_STYLE_MAP));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_STYLE_MAP));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_style_map_unref (old);
	}
}

static void
xi_style_map_class_init (XiStyleMapClass * klass,
                         gpointer klass_data)
{
	xi_style_map_parent_class = g_type_class_peek_parent (klass);
	((XiStyleMapClass *) klass)->finalize = xi_style_map_finalize;
	g_type_class_adjust_private_offset (klass, &XiStyleMap_private_offset);
}

static void
xi_style_map_instance_init (XiStyleMap * self,
                            gpointer klass)
{
	self->priv = xi_style_map_get_instance_private (self);
	self->ref_count = 1;
}

static void
xi_style_map_finalize (XiStyleMap * obj)
{
	XiStyleMap * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_STYLE_MAP, XiStyleMap);
	g_signal_handlers_destroy (self);
	_g_ptr_array_unref0 (self->priv->map);
}

static GType
xi_style_map_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { xi_value_style_map_init, xi_value_style_map_free_value, xi_value_style_map_copy_value, xi_value_style_map_peek_pointer, "p", xi_value_style_map_collect_value, "p", xi_value_style_map_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (XiStyleMapClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_style_map_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiStyleMap), 0, (GInstanceInitFunc) xi_style_map_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType xi_style_map_type_id;
	xi_style_map_type_id = g_type_register_fundamental (g_type_fundamental_next (), "XiStyleMap", &g_define_type_info, &g_define_type_fundamental_info, 0);
	XiStyleMap_private_offset = g_type_add_instance_private (xi_style_map_type_id, sizeof (XiStyleMapPrivate));
	return xi_style_map_type_id;
}

GType
xi_style_map_get_type (void)
{
	static volatile gsize xi_style_map_type_id__once = 0;
	if (g_once_init_enter (&xi_style_map_type_id__once)) {
		GType xi_style_map_type_id;
		xi_style_map_type_id = xi_style_map_get_type_once ();
		g_once_init_leave (&xi_style_map_type_id__once, xi_style_map_type_id);
	}
	return xi_style_map_type_id__once;
}

gpointer
xi_style_map_ref (gpointer instance)
{
	XiStyleMap * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
xi_style_map_unref (gpointer instance)
{
	XiStyleMap * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		XI_STYLE_MAP_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

