/* Style.c generated by valac 0.56.18, the Vala compiler
 * generated from Style.vala, do not modify */

/* Copyright 2017 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <glib-object.h>
#include <gdk/gdk.h>
#include <pango/pango.h>
#include <glib.h>
#include <string.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_STYLE (xi_style_get_type ())
typedef struct _XiStyle XiStyle;
#define __vala_GdkRGBA_free0(var) ((var == NULL) ? NULL : (var = (_vala_GdkRGBA_free (var), NULL)))
#define _g_free0(var) ((var == NULL) ? NULL : (var = (g_free (var), NULL)))

struct _XiStyle {
	GdkRGBA* foreground;
	GdkRGBA* background;
	PangoWeight* weight;
	gboolean underline;
	gboolean italic;
};

VALA_EXTERN GType xi_style_get_type (void) G_GNUC_CONST ;
VALA_EXTERN XiStyle* xi_style_dup (const XiStyle* self);
VALA_EXTERN void xi_style_free (XiStyle* self);
VALA_EXTERN void xi_style_copy (const XiStyle* self,
                    XiStyle* dest);
VALA_EXTERN void xi_style_destroy (XiStyle* self);
G_DEFINE_AUTO_CLEANUP_CLEAR_FUNC (XiStyle, xi_style_destroy)
static void _vala_GdkRGBA_free (GdkRGBA* self);
static GdkRGBA* _vala_GdkRGBA_copy (GdkRGBA* self);
static PangoWeight* _pango_weight_dup (PangoWeight* self);

static void
_vala_GdkRGBA_free (GdkRGBA* self)
{
	g_boxed_free (gdk_rgba_get_type (), self);
}

static GdkRGBA*
_vala_GdkRGBA_copy (GdkRGBA* self)
{
	return g_boxed_copy (gdk_rgba_get_type (), self);
}

static gpointer
__vala_GdkRGBA_copy0 (gpointer self)
{
	return self ? _vala_GdkRGBA_copy (self) : NULL;
}

static PangoWeight*
_pango_weight_dup (PangoWeight* self)
{
	PangoWeight* dup;
	dup = g_new0 (PangoWeight, 1);
	memcpy (dup, self, sizeof (PangoWeight));
	return dup;
}

static gpointer
__pango_weight_dup0 (gpointer self)
{
	return self ? _pango_weight_dup (self) : NULL;
}

void
xi_style_copy (const XiStyle* self,
               XiStyle* dest)
{
	GdkRGBA* _tmp0_;
	GdkRGBA* _tmp1_;
	GdkRGBA* _tmp2_;
	GdkRGBA* _tmp3_;
	PangoWeight* _tmp4_;
	PangoWeight* _tmp5_;
	_tmp0_ = (*self).foreground;
	_tmp1_ = __vala_GdkRGBA_copy0 (_tmp0_);
	__vala_GdkRGBA_free0 ((*dest).foreground);
	(*dest).foreground = _tmp1_;
	_tmp2_ = (*self).background;
	_tmp3_ = __vala_GdkRGBA_copy0 (_tmp2_);
	__vala_GdkRGBA_free0 ((*dest).background);
	(*dest).background = _tmp3_;
	_tmp4_ = (*self).weight;
	_tmp5_ = __pango_weight_dup0 (_tmp4_);
	_g_free0 ((*dest).weight);
	(*dest).weight = _tmp5_;
	(*dest).underline = (*self).underline;
	(*dest).italic = (*self).italic;
}

void
xi_style_destroy (XiStyle* self)
{
	__vala_GdkRGBA_free0 ((*self).foreground);
	__vala_GdkRGBA_free0 ((*self).background);
	_g_free0 ((*self).weight);
}

XiStyle*
xi_style_dup (const XiStyle* self)
{
	XiStyle* dup;
	dup = g_new0 (XiStyle, 1);
	xi_style_copy (self, dup);
	return dup;
}

void
xi_style_free (XiStyle* self)
{
	xi_style_destroy (self);
	g_free (self);
}

static GType
xi_style_get_type_once (void)
{
	GType xi_style_type_id;
	xi_style_type_id = g_boxed_type_register_static ("XiStyle", (GBoxedCopyFunc) xi_style_dup, (GBoxedFreeFunc) xi_style_free);
	return xi_style_type_id;
}

GType
xi_style_get_type (void)
{
	static volatile gsize xi_style_type_id__once = 0;
	if (g_once_init_enter (&xi_style_type_id__once)) {
		GType xi_style_type_id;
		xi_style_type_id = xi_style_get_type_once ();
		g_once_init_leave (&xi_style_type_id__once, xi_style_type_id);
	}
	return xi_style_type_id__once;
}

