/* Theme.c generated by valac 0.56.18, the Vala compiler
 * generated from Theme.vala, do not modify */

/* Copyright 2017 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <glib-object.h>
#include <gdk/gdk.h>
#include <glib.h>
#include <json-glib/json-glib.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_THEME (xi_theme_get_type ())
#define XI_THEME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_THEME, XiTheme))
#define XI_THEME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_THEME, XiThemeClass))
#define XI_IS_THEME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_THEME))
#define XI_IS_THEME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_THEME))
#define XI_THEME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_THEME, XiThemeClass))

typedef struct _XiTheme XiTheme;
typedef struct _XiThemeClass XiThemeClass;
typedef struct _XiThemePrivate XiThemePrivate;
#define _xi_theme_unref0(var) ((var == NULL) ? NULL : (var = (xi_theme_unref (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
typedef struct _XiParamSpecTheme XiParamSpecTheme;

struct _XiTheme {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XiThemePrivate * priv;
	GdkRGBA foreground;
	GdkRGBA background;
	GdkRGBA caret;
	GdkRGBA line_highlight;
	GdkRGBA selection;
	GdkRGBA gutter;
	GdkRGBA gutter_foreground;
	GdkRGBA find_highlight;
	GdkRGBA find_highlight_foreground;
};

struct _XiThemeClass {
	GTypeClass parent_class;
	void (*finalize) (XiTheme *self);
};

struct _XiParamSpecTheme {
	GParamSpec parent_instance;
};

static gpointer xi_theme_parent_class = NULL;
static XiTheme* xi_theme_instance;
static XiTheme* xi_theme_instance = NULL;

VALA_EXTERN gpointer xi_theme_ref (gpointer instance);
VALA_EXTERN void xi_theme_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_theme (const gchar* name,
                                 const gchar* nick,
                                 const gchar* blurb,
                                 GType object_type,
                                 GParamFlags flags);
VALA_EXTERN void xi_value_set_theme (GValue* value,
                         gpointer v_object);
VALA_EXTERN void xi_value_take_theme (GValue* value,
                          gpointer v_object);
VALA_EXTERN gpointer xi_value_get_theme (const GValue* value);
VALA_EXTERN GType xi_theme_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiTheme, xi_theme_unref)
VALA_EXTERN XiTheme* xi_theme_get_instance (void);
VALA_EXTERN XiTheme* xi_theme_new (void);
VALA_EXTERN XiTheme* xi_theme_construct (GType object_type);
static void xi_theme_decode_color (JsonObject* theme,
                            const gchar* color_name,
                            GdkRGBA* result);
VALA_EXTERN void xi_theme_set_from_json (XiTheme* self,
                             JsonObject* theme);
static void xi_theme_finalize (XiTheme * obj);
static GType xi_theme_get_type_once (void);

static gpointer
_xi_theme_ref0 (gpointer self)
{
	return self ? xi_theme_ref (self) : NULL;
}

XiTheme*
xi_theme_get_instance (void)
{
	XiTheme* _tmp0_;
	XiTheme* _tmp2_;
	XiTheme* _tmp3_;
	XiTheme* result;
	_tmp0_ = xi_theme_instance;
	if (_tmp0_ == NULL) {
		XiTheme* _tmp1_;
		_tmp1_ = xi_theme_new ();
		_xi_theme_unref0 (xi_theme_instance);
		xi_theme_instance = _tmp1_;
	}
	_tmp2_ = xi_theme_instance;
	_tmp3_ = _xi_theme_ref0 (_tmp2_);
	result = _tmp3_;
	return result;
}

static gpointer
_json_object_ref0 (gpointer self)
{
	return self ? json_object_ref (self) : NULL;
}

static void
xi_theme_decode_color (JsonObject* theme,
                       const gchar* color_name,
                       GdkRGBA* result)
{
	JsonObject* color = NULL;
	JsonObject* _tmp1_;
	JsonObject* _tmp2_;
	JsonObject* _tmp3_;
	gint64 r = 0LL;
	JsonObject* _tmp5_;
	gint64 g = 0LL;
	JsonObject* _tmp6_;
	gint64 b = 0LL;
	JsonObject* _tmp7_;
	gint64 a = 0LL;
	JsonObject* _tmp8_;
	GdkRGBA _tmp9_ = {0};
	g_return_if_fail (theme != NULL);
	g_return_if_fail (color_name != NULL);
	if (!json_object_has_member (theme, color_name)) {
		GdkRGBA _tmp0_ = {0};
		memset (&_tmp0_, 0, sizeof (GdkRGBA));
		*result = _tmp0_;
		return;
	}
	_tmp1_ = json_object_get_object_member (theme, color_name);
	_tmp2_ = _json_object_ref0 (_tmp1_);
	color = _tmp2_;
	_tmp3_ = color;
	if (_tmp3_ == NULL) {
		GdkRGBA _tmp4_ = {0};
		memset (&_tmp4_, 0, sizeof (GdkRGBA));
		*result = _tmp4_;
		_json_object_unref0 (color);
		return;
	}
	_tmp5_ = color;
	r = json_object_get_int_member (_tmp5_, "r");
	_tmp6_ = color;
	g = json_object_get_int_member (_tmp6_, "g");
	_tmp7_ = color;
	b = json_object_get_int_member (_tmp7_, "b");
	_tmp8_ = color;
	a = json_object_get_int_member (_tmp8_, "a");
	memset (&_tmp9_, 0, sizeof (GdkRGBA));
	_tmp9_.red = r / 255.0;
	_tmp9_.green = g / 255.0;
	_tmp9_.blue = b / 255.0;
	_tmp9_.alpha = a / 255.0;
	*result = _tmp9_;
	_json_object_unref0 (color);
	return;
}

void
xi_theme_set_from_json (XiTheme* self,
                        JsonObject* theme)
{
	GdkRGBA _tmp0_ = {0};
	GdkRGBA _tmp1_ = {0};
	GdkRGBA _tmp2_ = {0};
	GdkRGBA _tmp3_ = {0};
	GdkRGBA _tmp4_ = {0};
	GdkRGBA _tmp5_ = {0};
	GdkRGBA _tmp6_ = {0};
	GdkRGBA _tmp7_ = {0};
	GdkRGBA _tmp8_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (theme != NULL);
	xi_theme_decode_color (theme, "foreground", &_tmp0_);
	self->foreground = _tmp0_;
	xi_theme_decode_color (theme, "background", &_tmp1_);
	self->background = _tmp1_;
	xi_theme_decode_color (theme, "caret", &_tmp2_);
	self->caret = _tmp2_;
	xi_theme_decode_color (theme, "line_highlight", &_tmp3_);
	self->line_highlight = _tmp3_;
	xi_theme_decode_color (theme, "selection", &_tmp4_);
	self->selection = _tmp4_;
	xi_theme_decode_color (theme, "gutter", &_tmp5_);
	self->gutter = _tmp5_;
	xi_theme_decode_color (theme, "gutter_foreground", &_tmp6_);
	self->gutter_foreground = _tmp6_;
	xi_theme_decode_color (theme, "find_highlight", &_tmp7_);
	self->find_highlight = _tmp7_;
	xi_theme_decode_color (theme, "find_highlight_foreground", &_tmp8_);
	self->find_highlight_foreground = _tmp8_;
}

XiTheme*
xi_theme_construct (GType object_type)
{
	XiTheme* self = NULL;
	self = (XiTheme*) g_type_create_instance (object_type);
	return self;
}

XiTheme*
xi_theme_new (void)
{
	return xi_theme_construct (XI_TYPE_THEME);
}

static void
xi_value_theme_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
xi_value_theme_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		xi_theme_unref (value->data[0].v_pointer);
	}
}

static void
xi_value_theme_copy_value (const GValue* src_value,
                           GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = xi_theme_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
xi_value_theme_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
xi_value_theme_collect_value (GValue* value,
                              guint n_collect_values,
                              GTypeCValue* collect_values,
                              guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		XiTheme * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = xi_theme_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
xi_value_theme_lcopy_value (const GValue* value,
                            guint n_collect_values,
                            GTypeCValue* collect_values,
                            guint collect_flags)
{
	XiTheme ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = xi_theme_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
xi_param_spec_theme (const gchar* name,
                     const gchar* nick,
                     const gchar* blurb,
                     GType object_type,
                     GParamFlags flags)
{
	XiParamSpecTheme* spec;
	g_return_val_if_fail (g_type_is_a (object_type, XI_TYPE_THEME), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
xi_value_get_theme (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_THEME), NULL);
	return value->data[0].v_pointer;
}

void
xi_value_set_theme (GValue* value,
                    gpointer v_object)
{
	XiTheme * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_THEME));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_THEME));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		xi_theme_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_theme_unref (old);
	}
}

void
xi_value_take_theme (GValue* value,
                     gpointer v_object)
{
	XiTheme * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_THEME));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_THEME));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_theme_unref (old);
	}
}

static void
xi_theme_class_init (XiThemeClass * klass,
                     gpointer klass_data)
{
	xi_theme_parent_class = g_type_class_peek_parent (klass);
	((XiThemeClass *) klass)->finalize = xi_theme_finalize;
}

static void
xi_theme_instance_init (XiTheme * self,
                        gpointer klass)
{
	self->ref_count = 1;
}

static void
xi_theme_finalize (XiTheme * obj)
{
	XiTheme * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_THEME, XiTheme);
	g_signal_handlers_destroy (self);
}

static GType
xi_theme_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { xi_value_theme_init, xi_value_theme_free_value, xi_value_theme_copy_value, xi_value_theme_peek_pointer, "p", xi_value_theme_collect_value, "p", xi_value_theme_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (XiThemeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_theme_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiTheme), 0, (GInstanceInitFunc) xi_theme_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType xi_theme_type_id;
	xi_theme_type_id = g_type_register_fundamental (g_type_fundamental_next (), "XiTheme", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return xi_theme_type_id;
}

GType
xi_theme_get_type (void)
{
	static volatile gsize xi_theme_type_id__once = 0;
	if (g_once_init_enter (&xi_theme_type_id__once)) {
		GType xi_theme_type_id;
		xi_theme_type_id = xi_theme_get_type_once ();
		g_once_init_leave (&xi_theme_type_id__once, xi_theme_type_id);
	}
	return xi_theme_type_id__once;
}

gpointer
xi_theme_ref (gpointer instance)
{
	XiTheme * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
xi_theme_unref (gpointer instance)
{
	XiTheme * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		XI_THEME_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

