/* Utilities.c generated by valac 0.56.18, the Vala compiler
 * generated from Utilities.vala, do not modify */

/* Copyright 2017-2018 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <glib-object.h>
#include <glib.h>
#include <gdk/gdk.h>
#include <string.h>
#include <gobject/gvaluecollector.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_UTILITIES (xi_utilities_get_type ())
#define XI_UTILITIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_UTILITIES, XiUtilities))
#define XI_UTILITIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_UTILITIES, XiUtilitiesClass))
#define XI_IS_UTILITIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_UTILITIES))
#define XI_IS_UTILITIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_UTILITIES))
#define XI_UTILITIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_UTILITIES, XiUtilitiesClass))

typedef struct _XiUtilities XiUtilities;
typedef struct _XiUtilitiesClass XiUtilitiesClass;
typedef struct _XiUtilitiesPrivate XiUtilitiesPrivate;
typedef struct _XiParamSpecUtilities XiParamSpecUtilities;

struct _XiUtilities {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XiUtilitiesPrivate * priv;
};

struct _XiUtilitiesClass {
	GTypeClass parent_class;
	void (*finalize) (XiUtilities *self);
};

struct _XiParamSpecUtilities {
	GParamSpec parent_instance;
};

static gpointer xi_utilities_parent_class = NULL;

VALA_EXTERN gpointer xi_utilities_ref (gpointer instance);
VALA_EXTERN void xi_utilities_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_utilities (const gchar* name,
                                     const gchar* nick,
                                     const gchar* blurb,
                                     GType object_type,
                                     GParamFlags flags);
VALA_EXTERN void xi_value_set_utilities (GValue* value,
                             gpointer v_object);
VALA_EXTERN void xi_value_take_utilities (GValue* value,
                              gpointer v_object);
VALA_EXTERN gpointer xi_value_get_utilities (const GValue* value);
VALA_EXTERN GType xi_utilities_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiUtilities, xi_utilities_unref)
VALA_EXTERN void xi_utilities_convert_color (guint32 color,
                                 GdkRGBA* result);
VALA_EXTERN gint xi_utilities_get_digits (gint64 number);
VALA_EXTERN XiUtilities* xi_utilities_new (void);
VALA_EXTERN XiUtilities* xi_utilities_construct (GType object_type);
static void xi_utilities_finalize (XiUtilities * obj);
static GType xi_utilities_get_type_once (void);

void
xi_utilities_convert_color (guint32 color,
                            GdkRGBA* result)
{
	GdkRGBA _tmp0_ = {0};
	memset (&_tmp0_, 0, sizeof (GdkRGBA));
	_tmp0_.red = ((color >> 16) & 0xFF) / 255.0;
	_tmp0_.green = ((color >> 8) & 0xFF) / 255.0;
	_tmp0_.blue = (color & 0xFF) / 255.0;
	_tmp0_.alpha = ((color >> 24) & 0xFF) / 255.0;
	*result = _tmp0_;
	return;
}

gint
xi_utilities_get_digits (gint64 number)
{
	gint _result_ = 0;
	gint result;
	_result_ = 1;
	while (TRUE) {
		gint _tmp0_;
		if (!(number >= ((gint64) 10))) {
			break;
		}
		_tmp0_ = _result_;
		_result_ = _tmp0_ + 1;
		number = number / 10;
	}
	result = _result_;
	return result;
}

XiUtilities*
xi_utilities_construct (GType object_type)
{
	XiUtilities* self = NULL;
	self = (XiUtilities*) g_type_create_instance (object_type);
	return self;
}

XiUtilities*
xi_utilities_new (void)
{
	return xi_utilities_construct (XI_TYPE_UTILITIES);
}

static void
xi_value_utilities_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}

static void
xi_value_utilities_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		xi_utilities_unref (value->data[0].v_pointer);
	}
}

static void
xi_value_utilities_copy_value (const GValue* src_value,
                               GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = xi_utilities_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}

static gpointer
xi_value_utilities_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}

static gchar*
xi_value_utilities_collect_value (GValue* value,
                                  guint n_collect_values,
                                  GTypeCValue* collect_values,
                                  guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		XiUtilities * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = xi_utilities_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}

static gchar*
xi_value_utilities_lcopy_value (const GValue* value,
                                guint n_collect_values,
                                GTypeCValue* collect_values,
                                guint collect_flags)
{
	XiUtilities ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = xi_utilities_ref (value->data[0].v_pointer);
	}
	return NULL;
}

GParamSpec*
xi_param_spec_utilities (const gchar* name,
                         const gchar* nick,
                         const gchar* blurb,
                         GType object_type,
                         GParamFlags flags)
{
	XiParamSpecUtilities* spec;
	g_return_val_if_fail (g_type_is_a (object_type, XI_TYPE_UTILITIES), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}

gpointer
xi_value_get_utilities (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_UTILITIES), NULL);
	return value->data[0].v_pointer;
}

void
xi_value_set_utilities (GValue* value,
                        gpointer v_object)
{
	XiUtilities * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_UTILITIES));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_UTILITIES));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		xi_utilities_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_utilities_unref (old);
	}
}

void
xi_value_take_utilities (GValue* value,
                         gpointer v_object)
{
	XiUtilities * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, XI_TYPE_UTILITIES));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, XI_TYPE_UTILITIES));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		xi_utilities_unref (old);
	}
}

static void
xi_utilities_class_init (XiUtilitiesClass * klass,
                         gpointer klass_data)
{
	xi_utilities_parent_class = g_type_class_peek_parent (klass);
	((XiUtilitiesClass *) klass)->finalize = xi_utilities_finalize;
}

static void
xi_utilities_instance_init (XiUtilities * self,
                            gpointer klass)
{
	self->ref_count = 1;
}

static void
xi_utilities_finalize (XiUtilities * obj)
{
	XiUtilities * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_UTILITIES, XiUtilities);
	g_signal_handlers_destroy (self);
}

static GType
xi_utilities_get_type_once (void)
{
	static const GTypeValueTable g_define_type_value_table = { xi_value_utilities_init, xi_value_utilities_free_value, xi_value_utilities_copy_value, xi_value_utilities_peek_pointer, "p", xi_value_utilities_collect_value, "p", xi_value_utilities_lcopy_value };
	static const GTypeInfo g_define_type_info = { sizeof (XiUtilitiesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_utilities_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiUtilities), 0, (GInstanceInitFunc) xi_utilities_instance_init, &g_define_type_value_table };
	static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
	GType xi_utilities_type_id;
	xi_utilities_type_id = g_type_register_fundamental (g_type_fundamental_next (), "XiUtilities", &g_define_type_info, &g_define_type_fundamental_info, 0);
	return xi_utilities_type_id;
}

GType
xi_utilities_get_type (void)
{
	static volatile gsize xi_utilities_type_id__once = 0;
	if (g_once_init_enter (&xi_utilities_type_id__once)) {
		GType xi_utilities_type_id;
		xi_utilities_type_id = xi_utilities_get_type_once ();
		g_once_init_leave (&xi_utilities_type_id__once, xi_utilities_type_id);
	}
	return xi_utilities_type_id__once;
}

gpointer
xi_utilities_ref (gpointer instance)
{
	XiUtilities * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}

void
xi_utilities_unref (gpointer instance)
{
	XiUtilities * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		XI_UTILITIES_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}

