/* Window.c generated by valac 0.56.18, the Vala compiler
 * generated from Window.vala, do not modify */

/* Copyright 2017-2018 Elias Aebi*/
/**/
/* Licensed under the Apache License, Version 2.0 (the "License");*/
/* you may not use this file except in compliance with the License.*/
/* You may obtain a copy of the License at*/
/**/
/*     http://www.apache.org/licenses/LICENSE-2.0*/
/**/
/* Unless required by applicable law or agreed to in writing, software*/
/* distributed under the License is distributed on an "AS IS" BASIS,*/
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and*/
/* limitations under the License.*/

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define XI_TYPE_WINDOW (xi_window_get_type ())
#define XI_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_WINDOW, XiWindow))
#define XI_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_WINDOW, XiWindowClass))
#define XI_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_WINDOW))
#define XI_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_WINDOW))
#define XI_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_WINDOW, XiWindowClass))

typedef struct _XiWindow XiWindow;
typedef struct _XiWindowClass XiWindowClass;
typedef struct _XiWindowPrivate XiWindowPrivate;

#define XI_TYPE_CORE_CONNECTION (xi_core_connection_get_type ())
#define XI_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnection))
#define XI_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))
#define XI_IS_CORE_CONNECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_CORE_CONNECTION))
#define XI_IS_CORE_CONNECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_CORE_CONNECTION))
#define XI_CORE_CONNECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_CORE_CONNECTION, XiCoreConnectionClass))

typedef struct _XiCoreConnection XiCoreConnection;
typedef struct _XiCoreConnectionClass XiCoreConnectionClass;

#define XI_TYPE_NOTEBOOK (xi_notebook_get_type ())
#define XI_NOTEBOOK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_NOTEBOOK, XiNotebook))
#define XI_NOTEBOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_NOTEBOOK, XiNotebookClass))
#define XI_IS_NOTEBOOK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_NOTEBOOK))
#define XI_IS_NOTEBOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_NOTEBOOK))
#define XI_NOTEBOOK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_NOTEBOOK, XiNotebookClass))

typedef struct _XiNotebook XiNotebook;
typedef struct _XiNotebookClass XiNotebookClass;
enum  {
	XI_WINDOW_0_PROPERTY,
	XI_WINDOW_NUM_PROPERTIES
};
static GParamSpec* xi_window_properties[XI_WINDOW_NUM_PROPERTIES];
#define _xi_core_connection_unref0(var) ((var == NULL) ? NULL : (var = (xi_core_connection_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define XI_TYPE_EDIT_VIEW_CONTAINER (xi_edit_view_container_get_type ())
#define XI_EDIT_VIEW_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_EDIT_VIEW_CONTAINER, XiEditViewContainer))
#define XI_EDIT_VIEW_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_EDIT_VIEW_CONTAINER, XiEditViewContainerClass))
#define XI_IS_EDIT_VIEW_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_EDIT_VIEW_CONTAINER))
#define XI_IS_EDIT_VIEW_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_EDIT_VIEW_CONTAINER))
#define XI_EDIT_VIEW_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_EDIT_VIEW_CONTAINER, XiEditViewContainerClass))

typedef struct _XiEditViewContainer XiEditViewContainer;
typedef struct _XiEditViewContainerClass XiEditViewContainerClass;
typedef struct _Block2Data Block2Data;
#define _g_free0(var) (var = (g_free (var), NULL))

#define XI_TYPE_EDIT_VIEW (xi_edit_view_get_type ())
#define XI_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XI_TYPE_EDIT_VIEW, XiEditView))
#define XI_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XI_TYPE_EDIT_VIEW, XiEditViewClass))
#define XI_IS_EDIT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XI_TYPE_EDIT_VIEW))
#define XI_IS_EDIT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XI_TYPE_EDIT_VIEW))
#define XI_EDIT_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XI_TYPE_EDIT_VIEW, XiEditViewClass))

typedef struct _XiEditView XiEditView;
typedef struct _XiEditViewClass XiEditViewClass;
typedef struct _Block3Data Block3Data;

struct _XiWindow {
	GtkApplicationWindow parent_instance;
	XiWindowPrivate * priv;
};

struct _XiWindowClass {
	GtkApplicationWindowClass parent_class;
};

struct _XiWindowPrivate {
	XiCoreConnection* core_connection;
	XiNotebook* notebook;
	GtkFileChooserNative* dialog;
};

struct _Block2Data {
	int _ref_count_;
	XiWindow* self;
	GFile* file;
};

struct _Block3Data {
	int _ref_count_;
	XiWindow* self;
	XiEditView* edit_view;
};

static gint XiWindow_private_offset;
static gpointer xi_window_parent_class = NULL;

VALA_EXTERN GType xi_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiWindow, g_object_unref)
VALA_EXTERN gpointer xi_core_connection_ref (gpointer instance);
VALA_EXTERN void xi_core_connection_unref (gpointer instance);
VALA_EXTERN GParamSpec* xi_param_spec_core_connection (const gchar* name,
                                           const gchar* nick,
                                           const gchar* blurb,
                                           GType object_type,
                                           GParamFlags flags);
VALA_EXTERN void xi_value_set_core_connection (GValue* value,
                                   gpointer v_object);
VALA_EXTERN void xi_value_take_core_connection (GValue* value,
                                    gpointer v_object);
VALA_EXTERN gpointer xi_value_get_core_connection (const GValue* value);
VALA_EXTERN GType xi_core_connection_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiCoreConnection, xi_core_connection_unref)
VALA_EXTERN GType xi_notebook_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiNotebook, g_object_unref)
VALA_EXTERN XiWindow* xi_window_new (GtkApplication* application,
                         XiCoreConnection* core_connection);
VALA_EXTERN XiWindow* xi_window_construct (GType object_type,
                               GtkApplication* application,
                               XiCoreConnection* core_connection);
static void __lambda11_ (XiWindow* self);
VALA_EXTERN void xi_window_add_new_tab (XiWindow* self,
                            GFile* file);
static void ___lambda11__g_simple_action_activate (GSimpleAction* _sender,
                                            GVariant* parameter,
                                            gpointer self);
static void xi_window_open (XiWindow* self);
static void _xi_window_open_g_simple_action_activate (GSimpleAction* _sender,
                                               GVariant* parameter,
                                               gpointer self);
static void xi_window_save (XiWindow* self);
static void _xi_window_save_g_simple_action_activate (GSimpleAction* _sender,
                                               GVariant* parameter,
                                               gpointer self);
static void xi_window_save_as (XiWindow* self);
static void _xi_window_save_as_g_simple_action_activate (GSimpleAction* _sender,
                                                  GVariant* parameter,
                                                  gpointer self);
static void __lambda15_ (XiWindow* self);
VALA_EXTERN GType xi_edit_view_container_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiEditViewContainer, g_object_unref)
VALA_EXTERN XiEditViewContainer* xi_notebook_get_current_edit_view (XiNotebook* self);
VALA_EXTERN void xi_edit_view_container_show_find_bar (XiEditViewContainer* self);
static void ___lambda15__g_simple_action_activate (GSimpleAction* _sender,
                                            GVariant* parameter,
                                            gpointer self);
VALA_EXTERN XiNotebook* xi_notebook_new (void);
VALA_EXTERN XiNotebook* xi_notebook_construct (GType object_type);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
VALA_EXTERN void xi_core_connection_send_new_view (XiCoreConnection* self,
                                       const gchar* file_path,
                                       GAsyncReadyCallback _callback_,
                                       gpointer _user_data_);
VALA_EXTERN gchar* xi_core_connection_send_new_view_finish (XiCoreConnection* self,
                                                GAsyncResult* _res_);
static void __lambda12_ (Block2Data* _data2_,
                  GObject* obj,
                  GAsyncResult* res);
VALA_EXTERN void xi_notebook_add_edit_view (XiNotebook* self,
                                XiCoreConnection* core_connection,
                                const gchar* view_id,
                                GFile* file);
static void ___lambda12__gasync_ready_callback (GObject* source_object,
                                         GAsyncResult* res,
                                         gpointer self);
static void __lambda13_ (XiWindow* self,
                  gint response);
static void _g_object_unref0_ (gpointer var);
static inline void _g_slist_free__g_object_unref0_ (GSList* self);
static void ___lambda13__gtk_native_dialog_response (GtkNativeDialog* _sender,
                                              gint response_id,
                                              gpointer self);
VALA_EXTERN GType xi_edit_view_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (XiEditView, g_object_unref)
VALA_EXTERN XiEditView* xi_edit_view_container_get_edit_view (XiEditViewContainer* self);
VALA_EXTERN gboolean xi_edit_view_save (XiEditView* self);
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
static void __lambda14_ (Block3Data* _data3_,
                  gint response);
VALA_EXTERN void xi_edit_view_save_as (XiEditView* self,
                           GFile* file);
static void ___lambda14__gtk_native_dialog_response (GtkNativeDialog* _sender,
                                              gint response_id,
                                              gpointer self);
static void xi_window_finalize (GObject * obj);
static GType xi_window_get_type_once (void);

static inline gpointer
xi_window_get_instance_private (XiWindow* self)
{
	return G_STRUCT_MEMBER_P (self, XiWindow_private_offset);
}

static gpointer
_xi_core_connection_ref0 (gpointer self)
{
	return self ? xi_core_connection_ref (self) : NULL;
}

static void
__lambda11_ (XiWindow* self)
{
	xi_window_add_new_tab (self, NULL);
}

static void
___lambda11__g_simple_action_activate (GSimpleAction* _sender,
                                       GVariant* parameter,
                                       gpointer self)
{
	__lambda11_ ((XiWindow*) self);
}

static void
_xi_window_open_g_simple_action_activate (GSimpleAction* _sender,
                                          GVariant* parameter,
                                          gpointer self)
{
	xi_window_open ((XiWindow*) self);
}

static void
_xi_window_save_g_simple_action_activate (GSimpleAction* _sender,
                                          GVariant* parameter,
                                          gpointer self)
{
	xi_window_save ((XiWindow*) self);
}

static void
_xi_window_save_as_g_simple_action_activate (GSimpleAction* _sender,
                                             GVariant* parameter,
                                             gpointer self)
{
	xi_window_save_as ((XiWindow*) self);
}

static void
__lambda15_ (XiWindow* self)
{
	XiNotebook* _tmp0_;
	XiEditViewContainer* _tmp1_;
	_tmp0_ = self->priv->notebook;
	_tmp1_ = xi_notebook_get_current_edit_view (_tmp0_);
	xi_edit_view_container_show_find_bar (_tmp1_);
}

static void
___lambda15__g_simple_action_activate (GSimpleAction* _sender,
                                       GVariant* parameter,
                                       gpointer self)
{
	__lambda15_ ((XiWindow*) self);
}

XiWindow*
xi_window_construct (GType object_type,
                     GtkApplication* application,
                     XiCoreConnection* core_connection)
{
	XiWindow * self = NULL;
	XiCoreConnection* _tmp0_;
	GSimpleAction* new_tab_action = NULL;
	GSimpleAction* _tmp1_;
	GSimpleAction* open_action = NULL;
	GSimpleAction* _tmp2_;
	GSimpleAction* save_action = NULL;
	GSimpleAction* _tmp3_;
	GSimpleAction* save_as_action = NULL;
	GSimpleAction* _tmp4_;
	GSimpleAction* find_action = NULL;
	GSimpleAction* _tmp5_;
	GtkHeaderBar* header_bar = NULL;
	GtkHeaderBar* _tmp6_;
	GtkButton* new_button = NULL;
	GtkButton* _tmp7_;
	GtkButton* open_button = NULL;
	GtkButton* _tmp8_;
	GtkButton* save_button = NULL;
	GtkButton* _tmp9_;
	XiNotebook* _tmp10_;
	XiNotebook* _tmp11_;
	g_return_val_if_fail (application != NULL, NULL);
	g_return_val_if_fail (core_connection != NULL, NULL);
	self = (XiWindow*) g_object_new (object_type, "application", application, NULL);
	_tmp0_ = _xi_core_connection_ref0 (core_connection);
	_xi_core_connection_unref0 (self->priv->core_connection);
	self->priv->core_connection = _tmp0_;
	gtk_window_set_default_size ((GtkWindow*) self, 800, 550);
	_tmp1_ = g_simple_action_new ("new-tab", NULL);
	new_tab_action = _tmp1_;
	g_signal_connect_object (new_tab_action, "activate", (GCallback) ___lambda11__g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) new_tab_action);
	_tmp2_ = g_simple_action_new ("open", NULL);
	open_action = _tmp2_;
	g_signal_connect_object (open_action, "activate", (GCallback) _xi_window_open_g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) open_action);
	_tmp3_ = g_simple_action_new ("save", NULL);
	save_action = _tmp3_;
	g_signal_connect_object (save_action, "activate", (GCallback) _xi_window_save_g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) save_action);
	_tmp4_ = g_simple_action_new ("save-as", NULL);
	save_as_action = _tmp4_;
	g_signal_connect_object (save_as_action, "activate", (GCallback) _xi_window_save_as_g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) save_as_action);
	_tmp5_ = g_simple_action_new ("find", NULL);
	find_action = _tmp5_;
	g_signal_connect_object (find_action, "activate", (GCallback) ___lambda15__g_simple_action_activate, self, 0);
	g_action_map_add_action ((GActionMap*) self, (GAction*) find_action);
	_tmp6_ = (GtkHeaderBar*) gtk_header_bar_new ();
	g_object_ref_sink (_tmp6_);
	header_bar = _tmp6_;
	gtk_header_bar_set_show_close_button (header_bar, TRUE);
	gtk_header_bar_set_title (header_bar, "Xi");
	_tmp7_ = (GtkButton*) gtk_button_new_from_icon_name ("document-new-symbolic", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp7_);
	new_button = _tmp7_;
	gtk_widget_set_tooltip_text ((GtkWidget*) new_button, "New File");
	gtk_actionable_set_action_name ((GtkActionable*) new_button, "win.new-tab");
	gtk_header_bar_pack_start (header_bar, (GtkWidget*) new_button);
	_tmp8_ = (GtkButton*) gtk_button_new_from_icon_name ("document-open-symbolic", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp8_);
	open_button = _tmp8_;
	gtk_widget_set_tooltip_text ((GtkWidget*) open_button, "Open File");
	gtk_actionable_set_action_name ((GtkActionable*) open_button, "win.open");
	gtk_header_bar_pack_start (header_bar, (GtkWidget*) open_button);
	_tmp9_ = (GtkButton*) gtk_button_new_from_icon_name ("document-save-symbolic", (GtkIconSize) GTK_ICON_SIZE_BUTTON);
	g_object_ref_sink (_tmp9_);
	save_button = _tmp9_;
	gtk_widget_set_tooltip_text ((GtkWidget*) save_button, "Save File");
	gtk_actionable_set_action_name ((GtkActionable*) save_button, "win.save");
	gtk_header_bar_pack_end (header_bar, (GtkWidget*) save_button);
	gtk_window_set_titlebar ((GtkWindow*) self, (GtkWidget*) header_bar);
	_tmp10_ = xi_notebook_new ();
	g_object_ref_sink (_tmp10_);
	_g_object_unref0 (self->priv->notebook);
	self->priv->notebook = _tmp10_;
	_tmp11_ = self->priv->notebook;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp11_);
	_g_object_unref0 (save_button);
	_g_object_unref0 (open_button);
	_g_object_unref0 (new_button);
	_g_object_unref0 (header_bar);
	_g_object_unref0 (find_action);
	_g_object_unref0 (save_as_action);
	_g_object_unref0 (save_action);
	_g_object_unref0 (open_action);
	_g_object_unref0 (new_tab_action);
	return self;
}

XiWindow*
xi_window_new (GtkApplication* application,
               XiCoreConnection* core_connection)
{
	return xi_window_construct (XI_TYPE_WINDOW, application, core_connection);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static Block2Data*
block2_data_ref (Block2Data* _data2_)
{
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}

static void
block2_data_unref (void * _userdata_)
{
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		XiWindow* self;
		self = _data2_->self;
		_g_object_unref0 (_data2_->file);
		_g_object_unref0 (self);
		g_slice_free (Block2Data, _data2_);
	}
}

static void
__lambda12_ (Block2Data* _data2_,
             GObject* obj,
             GAsyncResult* res)
{
	XiWindow* self;
	gchar* view_id = NULL;
	XiCoreConnection* _tmp0_;
	gchar* _tmp1_;
	XiNotebook* _tmp2_;
	XiCoreConnection* _tmp3_;
	self = _data2_->self;
	g_return_if_fail (res != NULL);
	_tmp0_ = self->priv->core_connection;
	_tmp1_ = xi_core_connection_send_new_view_finish (_tmp0_, res);
	view_id = _tmp1_;
	_tmp2_ = self->priv->notebook;
	_tmp3_ = self->priv->core_connection;
	xi_notebook_add_edit_view (_tmp2_, _tmp3_, view_id, _data2_->file);
	_g_free0 (view_id);
}

static void
___lambda12__gasync_ready_callback (GObject* source_object,
                                    GAsyncResult* res,
                                    gpointer self)
{
	__lambda12_ (self, source_object, res);
	block2_data_unref (self);
}

void
xi_window_add_new_tab (XiWindow* self,
                       GFile* file)
{
	Block2Data* _data2_;
	GFile* _tmp0_;
	gchar* _tmp1_ = NULL;
	XiCoreConnection* _tmp3_;
	g_return_if_fail (self != NULL);
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	_data2_->self = g_object_ref (self);
	_tmp0_ = _g_object_ref0 (file);
	_g_object_unref0 (_data2_->file);
	_data2_->file = _tmp0_;
	if (_data2_->file != NULL) {
		gchar* _tmp2_;
		_tmp2_ = g_file_get_path (_data2_->file);
		_g_free0 (_tmp1_);
		_tmp1_ = _tmp2_;
	} else {
		_g_free0 (_tmp1_);
		_tmp1_ = NULL;
	}
	_tmp3_ = self->priv->core_connection;
	xi_core_connection_send_new_view (_tmp3_, _tmp1_, ___lambda12__gasync_ready_callback, block2_data_ref (_data2_));
	_g_free0 (_tmp1_);
	block2_data_unref (_data2_);
	_data2_ = NULL;
}

static void
_g_object_unref0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}

static inline void
_g_slist_free__g_object_unref0_ (GSList* self)
{
	g_slist_free_full (self, (GDestroyNotify) _g_object_unref0_);
}

static void
__lambda13_ (XiWindow* self,
             gint response)
{
	GtkFileChooserNative* _tmp4_;
	if (response == ((gint) GTK_RESPONSE_ACCEPT)) {
		GtkFileChooserNative* _tmp0_;
		GSList* _tmp1_;
		_tmp0_ = self->priv->dialog;
		_tmp1_ = gtk_file_chooser_get_files ((GtkFileChooser*) _tmp0_);
		{
			GSList* file_collection = NULL;
			GSList* file_it = NULL;
			file_collection = _tmp1_;
			for (file_it = file_collection; file_it != NULL; file_it = file_it->next) {
				GFile* _tmp2_;
				GFile* file = NULL;
				_tmp2_ = _g_object_ref0 ((GFile*) file_it->data);
				file = _tmp2_;
				{
					GFile* _tmp3_;
					_tmp3_ = file;
					xi_window_add_new_tab (self, _tmp3_);
					_g_object_unref0 (file);
				}
			}
			(file_collection == NULL) ? NULL : (file_collection = (_g_slist_free__g_object_unref0_ (file_collection), NULL));
		}
	}
	_tmp4_ = self->priv->dialog;
	gtk_native_dialog_destroy ((GtkNativeDialog*) _tmp4_);
}

static void
___lambda13__gtk_native_dialog_response (GtkNativeDialog* _sender,
                                         gint response_id,
                                         gpointer self)
{
	__lambda13_ ((XiWindow*) self, response_id);
}

static void
xi_window_open (XiWindow* self)
{
	GtkFileChooserNative* _tmp0_;
	GtkFileChooserNative* _tmp1_;
	GtkFileChooserNative* _tmp2_;
	GtkFileChooserNative* _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_file_chooser_native_new (NULL, (GtkWindow*) self, GTK_FILE_CHOOSER_ACTION_OPEN, NULL, NULL);
	_g_object_unref0 (self->priv->dialog);
	self->priv->dialog = _tmp0_;
	_tmp1_ = self->priv->dialog;
	gtk_file_chooser_set_select_multiple ((GtkFileChooser*) _tmp1_, TRUE);
	_tmp2_ = self->priv->dialog;
	g_signal_connect_object ((GtkNativeDialog*) _tmp2_, "response", (GCallback) ___lambda13__gtk_native_dialog_response, self, 0);
	_tmp3_ = self->priv->dialog;
	gtk_native_dialog_show ((GtkNativeDialog*) _tmp3_);
}

static void
xi_window_save (XiWindow* self)
{
	XiEditView* edit_view = NULL;
	XiNotebook* _tmp0_;
	XiEditViewContainer* _tmp1_;
	XiEditView* _tmp2_;
	XiEditView* _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->notebook;
	_tmp1_ = xi_notebook_get_current_edit_view (_tmp0_);
	_tmp2_ = xi_edit_view_container_get_edit_view (_tmp1_);
	edit_view = _tmp2_;
	_tmp3_ = edit_view;
	if (!xi_edit_view_save (_tmp3_)) {
		xi_window_save_as (self);
	}
}

static Block3Data*
block3_data_ref (Block3Data* _data3_)
{
	g_atomic_int_inc (&_data3_->_ref_count_);
	return _data3_;
}

static void
block3_data_unref (void * _userdata_)
{
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
		XiWindow* self;
		self = _data3_->self;
		_g_object_unref0 (_data3_->edit_view);
		_g_object_unref0 (self);
		g_slice_free (Block3Data, _data3_);
	}
}

static void
__lambda14_ (Block3Data* _data3_,
             gint response)
{
	XiWindow* self;
	GtkFileChooserNative* _tmp3_;
	self = _data3_->self;
	if (response == ((gint) GTK_RESPONSE_ACCEPT)) {
		GtkFileChooserNative* _tmp0_;
		GFile* _tmp1_;
		GFile* _tmp2_;
		_tmp0_ = self->priv->dialog;
		_tmp1_ = gtk_file_chooser_get_file ((GtkFileChooser*) _tmp0_);
		_tmp2_ = _tmp1_;
		xi_edit_view_save_as (_data3_->edit_view, _tmp2_);
		_g_object_unref0 (_tmp2_);
	}
	_tmp3_ = self->priv->dialog;
	gtk_native_dialog_destroy ((GtkNativeDialog*) _tmp3_);
}

static void
___lambda14__gtk_native_dialog_response (GtkNativeDialog* _sender,
                                         gint response_id,
                                         gpointer self)
{
	__lambda14_ (self, response_id);
}

static void
xi_window_save_as (XiWindow* self)
{
	Block3Data* _data3_;
	XiNotebook* _tmp0_;
	XiEditViewContainer* _tmp1_;
	XiEditView* _tmp2_;
	XiEditView* _tmp3_;
	GtkFileChooserNative* _tmp4_;
	GtkFileChooserNative* _tmp5_;
	GtkFileChooserNative* _tmp6_;
	GtkFileChooserNative* _tmp7_;
	g_return_if_fail (self != NULL);
	_data3_ = g_slice_new0 (Block3Data);
	_data3_->_ref_count_ = 1;
	_data3_->self = g_object_ref (self);
	_tmp0_ = self->priv->notebook;
	_tmp1_ = xi_notebook_get_current_edit_view (_tmp0_);
	_tmp2_ = xi_edit_view_container_get_edit_view (_tmp1_);
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_data3_->edit_view = _tmp3_;
	_tmp4_ = gtk_file_chooser_native_new (NULL, (GtkWindow*) self, GTK_FILE_CHOOSER_ACTION_SAVE, NULL, NULL);
	_g_object_unref0 (self->priv->dialog);
	self->priv->dialog = _tmp4_;
	_tmp5_ = self->priv->dialog;
	gtk_file_chooser_set_do_overwrite_confirmation ((GtkFileChooser*) _tmp5_, TRUE);
	_tmp6_ = self->priv->dialog;
	g_signal_connect_data ((GtkNativeDialog*) _tmp6_, "response", (GCallback) ___lambda14__gtk_native_dialog_response, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
	_tmp7_ = self->priv->dialog;
	gtk_native_dialog_show ((GtkNativeDialog*) _tmp7_);
	block3_data_unref (_data3_);
	_data3_ = NULL;
}

static void
xi_window_class_init (XiWindowClass * klass,
                      gpointer klass_data)
{
	xi_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &XiWindow_private_offset);
	G_OBJECT_CLASS (klass)->finalize = xi_window_finalize;
}

static void
xi_window_instance_init (XiWindow * self,
                         gpointer klass)
{
	self->priv = xi_window_get_instance_private (self);
}

static void
xi_window_finalize (GObject * obj)
{
	XiWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, XI_TYPE_WINDOW, XiWindow);
	_xi_core_connection_unref0 (self->priv->core_connection);
	_g_object_unref0 (self->priv->notebook);
	_g_object_unref0 (self->priv->dialog);
	G_OBJECT_CLASS (xi_window_parent_class)->finalize (obj);
}

static GType
xi_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (XiWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) xi_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (XiWindow), 0, (GInstanceInitFunc) xi_window_instance_init, NULL };
	GType xi_window_type_id;
	xi_window_type_id = g_type_register_static (gtk_application_window_get_type (), "XiWindow", &g_define_type_info, 0);
	XiWindow_private_offset = g_type_add_instance_private (xi_window_type_id, sizeof (XiWindowPrivate));
	return xi_window_type_id;
}

GType
xi_window_get_type (void)
{
	static volatile gsize xi_window_type_id__once = 0;
	if (g_once_init_enter (&xi_window_type_id__once)) {
		GType xi_window_type_id;
		xi_window_type_id = xi_window_get_type_once ();
		g_once_init_leave (&xi_window_type_id__once, xi_window_type_id);
	}
	return xi_window_type_id__once;
}

